import { defaultLocale, type Locale } from "@/i18n/routing";

type AccountType = "individual" | "osgb" | "enterprise";

type DemoLocalePack = {
  demoPrefix: string;
  accountTypeLabels: Record<AccountType, string>;
  companySuffixes: Record<AccountType, string>;
  documentTitleSuffixes: Record<AccountType, string>;
  documentBody: string;
  taskTitleSuffix: string;
  taskDescription: string;
  workspaceNote: string;
  mail: {
    subject: string;
    previewNote: string;
    greeting: string;
    readyLine: string;
    accountLabel: string;
    usernameLabel: string;
    passwordLabel: string;
    loginLabel: string;
    resetLabel: string;
    passwordNote: string;
  };
};

const DEMO_LOCALE_PACKS: Record<Locale, DemoLocalePack> = {
  tr: {
    demoPrefix: "Demo",
    accountTypeLabels: {
      individual: "Bireysel",
      osgb: "OSGB",
      enterprise: "Kurumsal",
    },
    companySuffixes: {
      individual: "Demo Calisma Alani",
      osgb: "Demo Firmasi",
      enterprise: "Demo Kampusu",
    },
    documentTitleSuffixes: {
      individual: "Risk Degerlendirmesi Ozeti",
      osgb: "Personel ve Sozlesme Dosyasi",
      enterprise: "Yonetim Sistemi Proseduru",
    },
    documentBody:
      "Bu kayit demo olusturucu tarafindan uretildi. Demo ortaminda akis, onay ve yayin kontrolunu gostermek icin kullanilir.",
    taskTitleSuffix: "demo kontrol listesi",
    taskDescription:
      "Demo olusturucu tarafindan eklendi. Bu gorev, is takibi ve atama akislarini gostermek icin olusturuldu.",
    workspaceNote: "Demo olusturucu tarafindan uretildi.",
    mail: {
      subject: "RiskNova demo hesabin hazir",
      previewNote: "Demo hesabi olusturuldu. Ilk giristen sonra sifre yenilemesi zorunludur.",
      greeting: "Merhaba",
      readyLine: "Sizin icin {accountType} demo hesabi hazirlandi.",
      accountLabel: "Demo hesabi",
      usernameLabel: "Kullanici adi",
      passwordLabel: "Gecici sifre",
      loginLabel: "Giris",
      resetLabel: "Sifre yenileme",
      passwordNote: "Ilk giristen sonra sifrenizi degistirmeniz gerekir.",
    },
  },
  en: {
    demoPrefix: "Demo",
    accountTypeLabels: {
      individual: "Individual",
      osgb: "OSGB",
      enterprise: "Enterprise",
    },
    companySuffixes: {
      individual: "Demo Workspace",
      osgb: "Demo Company",
      enterprise: "Demo Campus",
    },
    documentTitleSuffixes: {
      individual: "Risk Assessment Summary",
      osgb: "Personnel and Contract File",
      enterprise: "Management System Procedure",
    },
    documentBody:
      "This record was generated by the demo builder. It is used to showcase workflow, approval, and publishing controls in the demo environment.",
    taskTitleSuffix: "demo checklist",
    taskDescription:
      "Added by the demo builder. This task is created to demonstrate task tracking and assignment flows.",
    workspaceNote: "Generated by the demo builder.",
    mail: {
      subject: "Your RiskNova demo account is ready",
      previewNote: "The demo account is ready. The user must change the password after the first sign-in.",
      greeting: "Hello",
      readyLine: "Your {accountType} demo account is ready.",
      accountLabel: "Demo account",
      usernameLabel: "Username",
      passwordLabel: "Temporary password",
      loginLabel: "Login",
      resetLabel: "Reset password",
      passwordNote: "The user must change the password after the first sign-in.",
    },
  },
  ar: {
    demoPrefix: "عرض تجريبي",
    accountTypeLabels: {
      individual: "فردي",
      osgb: "OSGB",
      enterprise: "مؤسسي",
    },
    companySuffixes: {
      individual: "مساحة عمل تجريبية",
      osgb: "شركة تجريبية",
      enterprise: "حرم تجريبي",
    },
    documentTitleSuffixes: {
      individual: "ملخص تقييم المخاطر",
      osgb: "ملف الموظفين والعقود",
      enterprise: "إجراء نظام الإدارة",
    },
    documentBody:
      "تم إنشاء هذا السجل بواسطة منشئ العرض التجريبي لاستخدامه في عرض سير العمل والموافقات والنشر داخل بيئة العرض.",
    taskTitleSuffix: "قائمة فحص تجريبية",
    taskDescription:
      "أضيفت بواسطة منشئ العرض التجريبي لإظهار سير تعقب المهام والتعيينات.",
    workspaceNote: "تم إنشاؤه بواسطة منشئ العرض التجريبي.",
    mail: {
      subject: "حساب RiskNova التجريبي جاهز",
      previewNote: "تم إنشاء الحساب التجريبي ويجب تغيير كلمة المرور بعد أول تسجيل دخول.",
      greeting: "مرحبا",
      readyLine: "تم تجهيز حساب {accountType} التجريبي لك.",
      accountLabel: "الحساب التجريبي",
      usernameLabel: "اسم المستخدم",
      passwordLabel: "كلمة المرور المؤقتة",
      loginLabel: "تسجيل الدخول",
      resetLabel: "إعادة تعيين كلمة المرور",
      passwordNote: "يجب تغيير كلمة المرور بعد أول تسجيل دخول.",
    },
  },
  ru: {
    demoPrefix: "Демо",
    accountTypeLabels: {
      individual: "Индивидуальный",
      osgb: "OSGB",
      enterprise: "Корпоративный",
    },
    companySuffixes: {
      individual: "Демо рабочее пространство",
      osgb: "Демо компания",
      enterprise: "Демо кампус",
    },
    documentTitleSuffixes: {
      individual: "Сводка по оценке рисков",
      osgb: "Файл персонала и договоров",
      enterprise: "Процедура системы управления",
    },
    documentBody:
      "Эта запись создана генератором демо и используется для показа процессов, согласования и публикации в демо-среде.",
    taskTitleSuffix: "демо контрольный список",
    taskDescription:
      "Добавлено генератором демо для демонстрации потоков задач и назначений.",
    workspaceNote: "Создано генератором демо.",
    mail: {
      subject: "Ваш демо-аккаунт RiskNova готов",
      previewNote: "Демо-аккаунт создан. После первого входа пароль нужно сменить.",
      greeting: "Здравствуйте",
      readyLine: "Для вас подготовлен демо-аккаунт типа {accountType}.",
      accountLabel: "Демо-аккаунт",
      usernameLabel: "Логин",
      passwordLabel: "Временный пароль",
      loginLabel: "Вход",
      resetLabel: "Смена пароля",
      passwordNote: "После первого входа пароль необходимо сменить.",
    },
  },
  de: {
    demoPrefix: "Demo",
    accountTypeLabels: {
      individual: "Individuell",
      osgb: "OSGB",
      enterprise: "Unternehmen",
    },
    companySuffixes: {
      individual: "Demo-Arbeitsbereich",
      osgb: "Demo-Firma",
      enterprise: "Demo-Campus",
    },
    documentTitleSuffixes: {
      individual: "Zusammenfassung der Risikobewertung",
      osgb: "Personal- und Vertragsakte",
      enterprise: "Managementsystem-Verfahren",
    },
    documentBody:
      "Dieser Eintrag wurde vom Demo-Generator erstellt und zeigt Workflow-, Freigabe- und Veroeffentlichungsprozesse in der Demo-Umgebung.",
    taskTitleSuffix: "Demo-Checkliste",
    taskDescription:
      "Vom Demo-Generator erstellt, um Aufgabenverfolgung und Zuweisungsablaeufe zu demonstrieren.",
    workspaceNote: "Vom Demo-Generator erstellt.",
    mail: {
      subject: "Ihr RiskNova-Demokonto ist bereit",
      previewNote: "Das Demokonto wurde erstellt. Nach der ersten Anmeldung muss das Passwort geaendert werden.",
      greeting: "Hallo",
      readyLine: "Ihr {accountType}-Demokonto ist bereit.",
      accountLabel: "Demokonto",
      usernameLabel: "Benutzername",
      passwordLabel: "Temporäres Passwort",
      loginLabel: "Anmeldung",
      resetLabel: "Passwort zurücksetzen",
      passwordNote: "Nach der ersten Anmeldung muss das Passwort geaendert werden.",
    },
  },
  fr: {
    demoPrefix: "Demo",
    accountTypeLabels: {
      individual: "Individuel",
      osgb: "OSGB",
      enterprise: "Entreprise",
    },
    companySuffixes: {
      individual: "Espace de travail demo",
      osgb: "Societe demo",
      enterprise: "Campus demo",
    },
    documentTitleSuffixes: {
      individual: "Resume de l'evaluation des risques",
      osgb: "Dossier du personnel et des contrats",
      enterprise: "Procedure du systeme de gestion",
    },
    documentBody:
      "Cet enregistrement a ete genere par le createur de demo pour illustrer les flux, validations et publications dans l'environnement de demonstration.",
    taskTitleSuffix: "liste de controle demo",
    taskDescription:
      "Ajoute par le createur de demo pour montrer le suivi des taches et des affectations.",
    workspaceNote: "Genere par le createur de demo.",
    mail: {
      subject: "Votre compte de demo RiskNova est pret",
      previewNote: "Le compte de demo est pret. Le mot de passe doit etre change apres la premiere connexion.",
      greeting: "Bonjour",
      readyLine: "Votre compte de demo {accountType} est pret.",
      accountLabel: "Compte de demo",
      usernameLabel: "Identifiant",
      passwordLabel: "Mot de passe temporaire",
      loginLabel: "Connexion",
      resetLabel: "Reinitialisation du mot de passe",
      passwordNote: "Le mot de passe doit etre change apres la premiere connexion.",
    },
  },
  es: {
    demoPrefix: "Demo",
    accountTypeLabels: {
      individual: "Individual",
      osgb: "OSGB",
      enterprise: "Empresarial",
    },
    companySuffixes: {
      individual: "Espacio de trabajo demo",
      osgb: "Empresa demo",
      enterprise: "Campus demo",
    },
    documentTitleSuffixes: {
      individual: "Resumen de evaluacion de riesgos",
      osgb: "Expediente de personal y contratos",
      enterprise: "Procedimiento del sistema de gestion",
    },
    documentBody:
      "Este registro fue generado por el creador de demos para mostrar flujos, aprobaciones y publicaciones en el entorno demo.",
    taskTitleSuffix: "lista de verificacion demo",
    taskDescription:
      "Agregado por el creador de demos para mostrar el seguimiento de tareas y asignaciones.",
    workspaceNote: "Generado por el creador de demos.",
    mail: {
      subject: "Tu cuenta demo de RiskNova esta lista",
      previewNote: "La cuenta demo esta lista. La contrasena debe cambiarse tras el primer acceso.",
      greeting: "Hola",
      readyLine: "Tu cuenta demo de tipo {accountType} esta lista.",
      accountLabel: "Cuenta demo",
      usernameLabel: "Usuario",
      passwordLabel: "Contrasena temporal",
      loginLabel: "Acceso",
      resetLabel: "Restablecer contrasena",
      passwordNote: "La contrasena debe cambiarse tras el primer acceso.",
    },
  },
  zh: {
    demoPrefix: "演示",
    accountTypeLabels: {
      individual: "个人",
      osgb: "OSGB",
      enterprise: "企业",
    },
    companySuffixes: {
      individual: "演示工作区",
      osgb: "演示公司",
      enterprise: "演示园区",
    },
    documentTitleSuffixes: {
      individual: "风险评估摘要",
      osgb: "人员与合同档案",
      enterprise: "管理体系流程",
    },
    documentBody:
      "该记录由演示创建器生成，用于展示演示环境中的流程、审批和发布控制。",
    taskTitleSuffix: "演示检查清单",
    taskDescription:
      "由演示创建器添加，用于展示任务跟踪和指派流程。",
    workspaceNote: "由演示创建器生成。",
    mail: {
      subject: "您的 RiskNova 演示账号已就绪",
      previewNote: "演示账号已创建，首次登录后必须修改密码。",
      greeting: "您好",
      readyLine: "已为您准备好 {accountType} 演示账号。",
      accountLabel: "演示账号",
      usernameLabel: "用户名",
      passwordLabel: "临时密码",
      loginLabel: "登录",
      resetLabel: "重置密码",
      passwordNote: "首次登录后必须修改密码。",
    },
  },
  ja: {
    demoPrefix: "デモ",
    accountTypeLabels: {
      individual: "個人",
      osgb: "OSGB",
      enterprise: "企業",
    },
    companySuffixes: {
      individual: "デモワークスペース",
      osgb: "デモ会社",
      enterprise: "デモキャンパス",
    },
    documentTitleSuffixes: {
      individual: "リスク評価サマリー",
      osgb: "人員と契約ファイル",
      enterprise: "管理システム手順書",
    },
    documentBody:
      "この記録はデモビルダーによって作成され、デモ環境でのワークフロー、承認、公開管理を示すために使用されます。",
    taskTitleSuffix: "デモチェックリスト",
    taskDescription:
      "デモビルダーによって追加され、タスク追跡と割り当てフローを示します。",
    workspaceNote: "デモビルダーによって作成されました。",
    mail: {
      subject: "RiskNova デモアカウントの準備ができました",
      previewNote: "デモアカウントが作成されました。初回ログイン後にパスワード変更が必要です。",
      greeting: "こんにちは",
      readyLine: "{accountType} デモアカウントの準備ができました。",
      accountLabel: "デモアカウント",
      usernameLabel: "ユーザー名",
      passwordLabel: "一時パスワード",
      loginLabel: "ログイン",
      resetLabel: "パスワード再設定",
      passwordNote: "初回ログイン後にパスワード変更が必要です。",
    },
  },
  ko: {
    demoPrefix: "데모",
    accountTypeLabels: {
      individual: "개인",
      osgb: "OSGB",
      enterprise: "기업",
    },
    companySuffixes: {
      individual: "데모 작업공간",
      osgb: "데모 회사",
      enterprise: "데모 캠퍼스",
    },
    documentTitleSuffixes: {
      individual: "위험성 평가 요약",
      osgb: "인력 및 계약 문서",
      enterprise: "관리 체계 절차서",
    },
    documentBody:
      "이 기록은 데모 생성기가 만들었으며 데모 환경의 워크플로우, 승인, 배포 제어를 보여주기 위해 사용됩니다.",
    taskTitleSuffix: "데모 체크리스트",
    taskDescription:
      "데모 생성기가 추가했으며 작업 추적과 배정 흐름을 보여줍니다.",
    workspaceNote: "데모 생성기로 생성되었습니다.",
    mail: {
      subject: "RiskNova 데모 계정이 준비되었습니다",
      previewNote: "데모 계정이 생성되었습니다. 첫 로그인 후 비밀번호를 변경해야 합니다.",
      greeting: "안녕하세요",
      readyLine: "{accountType} 데모 계정이 준비되었습니다.",
      accountLabel: "데모 계정",
      usernameLabel: "사용자 이름",
      passwordLabel: "임시 비밀번호",
      loginLabel: "로그인",
      resetLabel: "비밀번호 재설정",
      passwordNote: "첫 로그인 후 비밀번호를 변경해야 합니다.",
    },
  },
  hi: {
    demoPrefix: "डेमो",
    accountTypeLabels: {
      individual: "व्यक्तिगत",
      osgb: "OSGB",
      enterprise: "एंटरप्राइज़",
    },
    companySuffixes: {
      individual: "डेमो वर्कस्पेस",
      osgb: "डेमो कंपनी",
      enterprise: "डेमो कैंपस",
    },
    documentTitleSuffixes: {
      individual: "जोखिम मूल्यांकन सारांश",
      osgb: "कर्मचारी और अनुबंध फ़ाइल",
      enterprise: "प्रबंधन प्रणाली प्रक्रिया",
    },
    documentBody:
      "यह रिकॉर्ड डेमो बिल्डर द्वारा बनाया गया है और डेमो वातावरण में वर्कफ़्लो, अनुमोदन और प्रकाशन नियंत्रण दिखाने के लिए उपयोग किया जाता है।",
    taskTitleSuffix: "डेमो चेकलिस्ट",
    taskDescription:
      "डेमो बिल्डर द्वारा जोड़ा गया ताकि कार्य ट्रैकिंग और असाइनमेंट प्रवाह दिखाया जा सके।",
    workspaceNote: "डेमो बिल्डर द्वारा बनाया गया।",
    mail: {
      subject: "आपका RiskNova डेमो खाता तैयार है",
      previewNote: "डेमो खाता तैयार है। पहली लॉगिन के बाद पासवर्ड बदलना आवश्यक है।",
      greeting: "नमस्ते",
      readyLine: "आपका {accountType} डेमो खाता तैयार है।",
      accountLabel: "डेमो खाता",
      usernameLabel: "यूज़रनेम",
      passwordLabel: "अस्थायी पासवर्ड",
      loginLabel: "लॉगिन",
      resetLabel: "पासवर्ड रीसेट",
      passwordNote: "पहली लॉगिन के बाद पासवर्ड बदलना आवश्यक है।",
    },
  },
  az: {
    demoPrefix: "Demo",
    accountTypeLabels: {
      individual: "Ferdi",
      osgb: "OSGB",
      enterprise: "Korporativ",
    },
    companySuffixes: {
      individual: "Demo Is Sahesi",
      osgb: "Demo Sirketi",
      enterprise: "Demo Kampusu",
    },
    documentTitleSuffixes: {
      individual: "Risk Qiymetlendirme Xulasesi",
      osgb: "Personal ve Muqavile Fayli",
      enterprise: "Idareetme Sistemi Proseduru",
    },
    documentBody:
      "Bu qeyd demo qurucusu terefinden yaradilib ve demo muhiti daxilinde axin, tesdiq ve paylasim idaresini gostermek ucun istifade olunur.",
    taskTitleSuffix: "demo yoxlama siyahisi",
    taskDescription:
      "Demo qurucusu terefinden elave edilib. Bu tapsiriq is takibi ve teyinat axinlarini gostermek ucun yaradilib.",
    workspaceNote: "Demo qurucusu terefinden yaradilib.",
    mail: {
      subject: "RiskNova demo hesabiniz hazirdir",
      previewNote: "Demo hesabi hazirdir. Ilk girisden sonra sifreni deyismek lazimdir.",
      greeting: "Salam",
      readyLine: "Sizin ucun {accountType} demo hesabi hazirlandi.",
      accountLabel: "Demo hesabi",
      usernameLabel: "Istifadeci adi",
      passwordLabel: "Muvveqqeti sifre",
      loginLabel: "Giris",
      resetLabel: "Sifreni yenile",
      passwordNote: "Ilk girisden sonra sifreni deyismek lazimdir.",
    },
  },
  id: {
    demoPrefix: "Demo",
    accountTypeLabels: {
      individual: "Individual",
      osgb: "OSGB",
      enterprise: "Enterprise",
    },
    companySuffixes: {
      individual: "Ruang Kerja Demo",
      osgb: "Perusahaan Demo",
      enterprise: "Kampus Demo",
    },
    documentTitleSuffixes: {
      individual: "Ringkasan Penilaian Risiko",
      osgb: "Berkas Personel dan Kontrak",
      enterprise: "Prosedur Sistem Manajemen",
    },
    documentBody:
      "Catatan ini dibuat oleh pembuat demo untuk menampilkan alur kerja, persetujuan, dan penerbitan di lingkungan demo.",
    taskTitleSuffix: "daftar periksa demo",
    taskDescription:
      "Ditambahkan oleh pembuat demo untuk menampilkan alur pelacakan tugas dan penugasan.",
    workspaceNote: "Dibuat oleh pembuat demo.",
    mail: {
      subject: "Akun demo RiskNova Anda siap",
      previewNote: "Akun demo siap. Pengguna harus mengganti kata sandi setelah login pertama.",
      greeting: "Halo",
      readyLine: "Akun demo {accountType} Anda sudah siap.",
      accountLabel: "Akun demo",
      usernameLabel: "Nama pengguna",
      passwordLabel: "Kata sandi sementara",
      loginLabel: "Masuk",
      resetLabel: "Atur ulang kata sandi",
      passwordNote: "Pengguna harus mengganti kata sandi setelah login pertama.",
    },
  },
};

export function getDemoLocalePack(locale: Locale) {
  return DEMO_LOCALE_PACKS[locale] ?? DEMO_LOCALE_PACKS[defaultLocale];
}

export function getLocalizedAccountTypeLabel(locale: Locale, accountType: AccountType) {
  return getDemoLocalePack(locale).accountTypeLabels[accountType];
}

export function buildLocalizedOrganizationName(
  locale: Locale,
  accountType: AccountType,
  displayName: string,
) {
  const pack = getDemoLocalePack(locale);
  return `${pack.demoPrefix} - ${displayName} ${pack.accountTypeLabels[accountType]}`.slice(0, 120);
}

export function buildLocalizedCompanyName(
  locale: Locale,
  accountType: AccountType,
  inputName: string | undefined,
  displayName: string,
) {
  if (inputName?.trim()) return inputName.trim();
  return `${displayName} ${getDemoLocalePack(locale).companySuffixes[accountType]}`.slice(0, 180);
}

export function buildLocalizedDemoDocument(
  locale: Locale,
  accountType: AccountType,
  companyName: string,
) {
  const pack = getDemoLocalePack(locale);
  const title = `${companyName} ${pack.documentTitleSuffixes[accountType]}`.slice(0, 180);
  const groupKey =
    accountType === "osgb"
      ? "personel-ozluk"
      : accountType === "enterprise"
        ? "prosedurler"
        : "risk-degerlendirme";

  return {
    title,
    groupKey,
    contentJson: {
      type: "doc",
      content: [
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: pack.documentBody,
            },
          ],
        },
      ],
    },
  };
}

export function buildLocalizedDemoTask(locale: Locale, companyName: string) {
  const pack = getDemoLocalePack(locale);
  return {
    title: `${companyName} ${pack.taskTitleSuffix}`.slice(0, 180),
    description: pack.taskDescription,
  };
}

export function getLocalizedWorkspaceNote(locale: Locale) {
  return getDemoLocalePack(locale).workspaceNote;
}

export function getLocalizedDemoMailCopy(locale: Locale) {
  return getDemoLocalePack(locale).mail;
}

export type DemoStarterPrompt = {
  title: string;
  description: string;
  prompt: string;
};

function localizedGroupKey(accountType: AccountType) {
  if (accountType === "osgb") return "personel-ozluk";
  if (accountType === "enterprise") return "prosedurler";
  return "risk-degerlendirme";
}

function pickLocalized(locale: Locale, values: Partial<Record<Locale, string>>, fallback: string) {
  return values[locale] ?? fallback;
}

export function buildLocalizedNovaStarterPrompts(
  locale: Locale,
  accountType: AccountType,
  companyName: string,
): DemoStarterPrompt[] {
  const accountLabel = getLocalizedAccountTypeLabel(locale, accountType);

  switch (locale) {
    case "en":
      return [
        {
          title: "First action plan",
          description: "Ask Nova to prepare the first demo roadmap.",
          prompt: `Prepare a first-week action plan for the ${accountLabel} demo account linked to ${companyName}.`,
        },
        {
          title: "Documents and gaps",
          description: "List missing documents and approval bottlenecks.",
          prompt: `Review ${companyName} and summarize missing documents, approval gaps, and the first actions I should take.`,
        },
        {
          title: "Training and risk priorities",
          description: "Start with operational priorities in one answer.",
          prompt: `For ${companyName}, summarize the initial training, risk, and follow-up priorities I should review first.`,
        },
      ];
    case "ar":
      return [
        {
          title: "خطة العمل الأولى",
          description: "اطلب من Nova إعداد خارطة طريق العرض التجريبي.",
          prompt: `جهز لي خطة عمل للأسبوع الأول لحساب العرض التجريبي من نوع ${accountLabel} المرتبط بـ ${companyName}.`,
        },
        {
          title: "الوثائق والثغرات",
          description: "اعرض الوثائق الناقصة ونقاط التعثر في الموافقات.",
          prompt: `راجع ${companyName} وقدم ملخصاً للوثائق الناقصة وفجوات الموافقة وأول الإجراءات التي يجب أن أتخذها.`,
        },
        {
          title: "أولويات التدريب والمخاطر",
          description: "ابدأ بأولويات التشغيل في إجابة واحدة.",
          prompt: `بالنسبة إلى ${companyName}، لخص أولويات التدريب والمخاطر والمتابعة التي يجب أن أراجعها أولاً.`,
        },
      ];
    case "ru":
      return [
        {
          title: "Первый план действий",
          description: "Попросите Nova подготовить дорожную карту демо.",
          prompt: `Подготовь план действий на первую неделю для демо-аккаунта типа ${accountLabel}, связанного с ${companyName}.`,
        },
        {
          title: "Документы и пробелы",
          description: "Покажи недостающие документы и узкие места согласования.",
          prompt: `Проверь ${companyName} и кратко опиши недостающие документы, пробелы согласования и первые шаги для меня.`,
        },
        {
          title: "Приоритеты обучения и рисков",
          description: "Собери операционные приоритеты в одном ответе.",
          prompt: `Для ${companyName} кратко опиши первоочередные задачи по обучению, рискам и последующим действиям.`,
        },
      ];
    case "de":
      return [
        {
          title: "Erster Aktionsplan",
          description: "Lass Nova eine Roadmap fuer die Demo vorbereiten.",
          prompt: `Erstelle einen Aktionsplan fuer die erste Woche des ${accountLabel}-Demokontos zu ${companyName}.`,
        },
        {
          title: "Dokumente und Luecken",
          description: "Zeige fehlende Dokumente und Freigabeblockaden.",
          prompt: `Pruefe ${companyName} und fasse fehlende Dokumente, Freigabeluecken und die ersten noetigen Schritte zusammen.`,
        },
        {
          title: "Training und Risiko-Prioritaeten",
          description: "Starte mit operativen Prioritaeten in einer Antwort.",
          prompt: `Fasse fuer ${companyName} die wichtigsten Trainings-, Risiko- und Folgeprioritaeten zusammen, die ich zuerst pruefen sollte.`,
        },
      ];
    case "fr":
      return [
        {
          title: "Premier plan d'action",
          description: "Demande a Nova de preparer la feuille de route de la demo.",
          prompt: `Prepare un plan d'action pour la premiere semaine du compte demo ${accountLabel} lie a ${companyName}.`,
        },
        {
          title: "Documents et manques",
          description: "Liste les documents manquants et les blocages de validation.",
          prompt: `Analyse ${companyName} et resume les documents manquants, les blocages de validation et les premieres actions a lancer.`,
        },
        {
          title: "Priorites formation et risque",
          description: "Commence par les priorites operationnelles.",
          prompt: `Pour ${companyName}, resume les priorites initiales de formation, de risque et de suivi que je dois verifier en premier.`,
        },
      ];
    case "es":
      return [
        {
          title: "Primer plan de accion",
          description: "Pide a Nova la hoja de ruta inicial de la demo.",
          prompt: `Prepara un plan de accion para la primera semana de la cuenta demo ${accountLabel} vinculada a ${companyName}.`,
        },
        {
          title: "Documentos y brechas",
          description: "Resume documentos faltantes y bloqueos de aprobacion.",
          prompt: `Revisa ${companyName} y resume los documentos faltantes, las brechas de aprobacion y las primeras acciones recomendadas.`,
        },
        {
          title: "Prioridades de formacion y riesgo",
          description: "Empieza con prioridades operativas en una sola respuesta.",
          prompt: `Para ${companyName}, resume las prioridades iniciales de formacion, riesgo y seguimiento que debo revisar primero.`,
        },
      ];
    case "zh":
      return [
        {
          title: "首周行动计划",
          description: "让 Nova 生成演示账号的首周路线图。",
          prompt: `请为关联 ${companyName} 的 ${accountLabel} 演示账号制定首周行动计划。`,
        },
        {
          title: "文档与缺口",
          description: "总结缺失文档和审批堵点。",
          prompt: `请检查 ${companyName}，总结缺失文档、审批缺口以及我应先处理的事项。`,
        },
        {
          title: "培训与风险优先级",
          description: "一次性给出运营优先事项。",
          prompt: `针对 ${companyName}，请总结我首先应查看的培训、风险和跟进优先事项。`,
        },
      ];
    case "ja":
      return [
        {
          title: "最初のアクションプラン",
          description: "Nova にデモ用の初週ロードマップを作らせます。",
          prompt: `${companyName} に紐づく ${accountLabel} デモアカウント向けに、最初の1週間のアクションプランを作成してください。`,
        },
        {
          title: "文書と不足点",
          description: "不足文書と承認の詰まりを整理します。",
          prompt: `${companyName} を確認し、不足している文書、承認上のギャップ、最初に取るべき対応を要約してください。`,
        },
        {
          title: "教育とリスクの優先事項",
          description: "運用上の優先事項を一度に整理します。",
          prompt: `${companyName} について、最初に確認すべき教育・リスク・フォローアップの優先事項を要約してください。`,
        },
      ];
    case "ko":
      return [
        {
          title: "첫 주 실행 계획",
          description: "Nova가 데모 계정의 첫 주 로드맵을 준비합니다.",
          prompt: `${companyName}에 연결된 ${accountLabel} 데모 계정의 첫 주 실행 계획을 준비해 주세요.`,
        },
        {
          title: "문서와 공백",
          description: "누락 문서와 승인 병목을 정리합니다.",
          prompt: `${companyName}를 검토하고 누락 문서, 승인 공백, 제가 먼저 처리해야 할 작업을 요약해 주세요.`,
        },
        {
          title: "교육과 리스크 우선순위",
          description: "운영 우선순위를 한 번에 정리합니다.",
          prompt: `${companyName}에 대해 먼저 검토해야 할 교육, 리스크, 후속조치 우선순위를 요약해 주세요.`,
        },
      ];
    case "hi":
      return [
        {
          title: "पहला एक्शन प्लान",
          description: "Nova से डेमो का शुरुआती रोडमैप तैयार कराएं।",
          prompt: `${companyName} से जुड़े ${accountLabel} डेमो खाते के लिए पहले सप्ताह की कार्ययोजना तैयार करें।`,
        },
        {
          title: "दस्तावेज़ और कमी",
          description: "लापता दस्तावेज़ और अनुमोदन गैप बताएं।",
          prompt: `${companyName} की समीक्षा करें और लापता दस्तावेज़, अनुमोदन अंतराल और पहले किए जाने वाले कार्यों का सार दें।`,
        },
        {
          title: "प्रशिक्षण और जोखिम प्राथमिकताएँ",
          description: "संचालन प्राथमिकताओं को एक उत्तर में शुरू करें।",
          prompt: `${companyName} के लिए शुरुआती प्रशिक्षण, जोखिम और फॉलो-अप प्राथमिकताओं का सार दें जिन्हें मुझे पहले देखना चाहिए।`,
        },
      ];
    case "az":
      return [
        {
          title: "Ilk hereket plani",
          description: "Nova demo hesabinin ilk heftesini planlasin.",
          prompt: `${companyName} ile bagli ${accountLabel} demo hesabi ucun ilk heftelik hereket plani hazirla.`,
        },
        {
          title: "Senedler ve bosluqlar",
          description: "Catismayan senedleri ve tesdiq gecikmelerini cixart.",
          prompt: `${companyName} ucun catismayan senedleri, tesdiq bosluqlarini ve ilk goreceyim addimlari xulasə et.`,
        },
        {
          title: "Təlim ve risk prioritetleri",
          description: "Operativ prioritetleri bir cavabda topla.",
          prompt: `${companyName} ucun ilk baxmali oldugum təlim, risk ve davam prioritetlerini xulasə et.`,
        },
      ];
    case "id":
      return [
        {
          title: "Rencana aksi pertama",
          description: "Minta Nova menyiapkan roadmap demo minggu pertama.",
          prompt: `Siapkan rencana aksi minggu pertama untuk akun demo ${accountLabel} yang terhubung dengan ${companyName}.`,
        },
        {
          title: "Dokumen dan celah",
          description: "Ringkas dokumen yang kurang dan hambatan persetujuan.",
          prompt: `Tinjau ${companyName} dan ringkas dokumen yang kurang, celah persetujuan, dan tindakan pertama yang harus saya ambil.`,
        },
        {
          title: "Prioritas pelatihan dan risiko",
          description: "Mulai dari prioritas operasional dalam satu jawaban.",
          prompt: `Untuk ${companyName}, ringkas prioritas awal pelatihan, risiko, dan tindak lanjut yang harus saya tinjau terlebih dahulu.`,
        },
      ];
    case "tr":
    default:
      return [
        {
          title: "Ilk aksiyon plani",
          description: "Nova'dan demo hesabin ilk hafta yol haritasini cikar.",
          prompt: `${companyName} baglamindaki ${accountLabel} demo hesabi icin ilk hafta aksiyon planini cikar.`,
        },
        {
          title: "Dokuman ve onay bosluklari",
          description: "Eksik belge ve onay bekleyen alanlari ozetle.",
          prompt: `${companyName} icin eksik dokumanlari, onay bosluklarini ve ilk yapmam gereken isleri ozetle.`,
        },
        {
          title: "Egitim ve risk oncelikleri",
          description: "Ilk bakilacak operasyon onceliklerini tek cevapta topla.",
          prompt: `${companyName} icin once hangi egitim, risk ve takip basliklarina bakmam gerektigini ozetle.`,
        },
      ];
  }
}

export function buildLocalizedWelcomeDocument(
  locale: Locale,
  accountType: AccountType,
  organizationName: string,
  companyName: string,
  prompts: DemoStarterPrompt[],
) {
  const titleSuffix = pickLocalized(
    locale,
    {
      tr: "Hos Geldin ve Hizli Baslangic",
      en: "Welcome and Quick Start",
      ar: "الترحيب والبداية السريعة",
      ru: "Приветствие и быстрый старт",
      de: "Willkommen und Schnellstart",
      fr: "Bienvenue et demarrage rapide",
      es: "Bienvenida e inicio rapido",
      zh: "欢迎与快速开始",
      ja: "ようこそとクイックスタート",
      ko: "환영 및 빠른 시작",
      hi: "स्वागत और त्वरित शुरुआत",
      az: "Xos gelmisiniz ve suretli baslangic",
      id: "Selamat datang dan mulai cepat",
    },
    "Hos Geldin ve Hizli Baslangic",
  );

  const intro = pickLocalized(
    locale,
    {
      tr: `${organizationName} demo hesabina hos geldiniz. Bu dokuman, ${companyName} uzerinden ilerleyeceginiz ilk demoyu hizlandirmak icin olusturuldu.`,
      en: `Welcome to the ${organizationName} demo account. This document helps you start the first walkthrough for ${companyName}.`,
      ar: `مرحباً بك في حساب ${organizationName} التجريبي. تم إعداد هذا المستند لتسريع أول جولة لك على ${companyName}.`,
      ru: `Добро пожаловать в демо-аккаунт ${organizationName}. Этот документ поможет быстро начать первую демонстрацию по ${companyName}.`,
      de: `Willkommen im Demokonto ${organizationName}. Dieses Dokument beschleunigt Ihren ersten Durchlauf fuer ${companyName}.`,
      fr: `Bienvenue dans le compte de demo ${organizationName}. Ce document vous aide a demarrer la premiere visite pour ${companyName}.`,
      es: `Bienvenido a la cuenta demo ${organizationName}. Este documento acelera tu primer recorrido sobre ${companyName}.`,
      zh: `欢迎使用 ${organizationName} 演示账号。此文档可帮助你快速开始围绕 ${companyName} 的首次演示。`,
      ja: `${organizationName} デモアカウントへようこそ。この文書は ${companyName} を中心とした最初のデモ案内を素早く始めるためのものです。`,
      ko: `${organizationName} 데모 계정에 오신 것을 환영합니다. 이 문서는 ${companyName} 기준의 첫 데모 진행을 빠르게 시작하도록 도와줍니다.`,
      hi: `${organizationName} डेमो खाते में आपका स्वागत है। यह दस्तावेज़ ${companyName} के लिए पहली डेमो यात्रा शुरू करने में मदद करेगा।`,
      az: `${organizationName} demo hesabina xos gelmisiniz. Bu sened ${companyName} uzre ilk gosterisiniz ucun suretli baslangic verir.`,
      id: `Selamat datang di akun demo ${organizationName}. Dokumen ini membantu memulai tur pertama untuk ${companyName}.`,
    },
    `${organizationName} demo hesabina hos geldiniz. Bu dokuman, ${companyName} uzerinden ilerleyeceginiz ilk demoyu hizlandirmak icin olusturuldu.`,
  );

  const stepsLead = pickLocalized(
    locale,
    {
      tr: "Once su adimlari deneyin:",
      en: "Start with these steps:",
      ar: "ابدأ بهذه الخطوات:",
      ru: "Начните с этих шагов:",
      de: "Starten Sie mit diesen Schritten:",
      fr: "Commencez par ces etapes :",
      es: "Empieza con estos pasos:",
      zh: "建议先尝试以下步骤：",
      ja: "まずは次の手順を試してください:",
      ko: "먼저 다음 단계를 시도하세요:",
      hi: "पहले ये चरण आज़माएँ:",
      az: "Evvelce bu addimlari yoxlayin:",
      id: "Mulailah dengan langkah berikut:",
    },
    "Once su adimlari deneyin:",
  );

  const lines = [
    intro,
    stepsLead,
    ...prompts.map((item, index) => `${index + 1}. ${item.title}: ${item.prompt}`),
  ];

  return {
    title: `${organizationName} ${titleSuffix}`.slice(0, 180),
    groupKey: localizedGroupKey(accountType),
    contentJson: {
      type: "doc",
      content: lines.map((text) => ({
        type: "paragraph",
        content: [{ type: "text", text }],
      })),
    },
  };
}

export function buildLocalizedTrainingSeed(locale: Locale, companyName: string) {
  return {
    title: pickLocalized(
      locale,
      {
        tr: `${companyName} Demo Oryantasyon Egitimi`,
        en: `${companyName} Demo Orientation Training`,
        ar: `${companyName} تدريب التهيئة التجريبي`,
        ru: `${companyName} демо-ориентационное обучение`,
        de: `${companyName} Demo-Einweisung`,
        fr: `${companyName} formation d'orientation demo`,
        es: `${companyName} capacitacion inicial demo`,
        zh: `${companyName} 演示入门培训`,
        ja: `${companyName} デモ導入トレーニング`,
        ko: `${companyName} 데모 오리엔테이션 교육`,
        hi: `${companyName} डेमो ओरिएंटेशन प्रशिक्षण`,
        az: `${companyName} Demo Oriyentasiya Telimi`,
        id: `${companyName} Pelatihan Orientasi Demo`,
      },
      `${companyName} Demo Oryantasyon Egitimi`,
    ),
    trainerName: "RiskNova Demo",
    notes: pickLocalized(
      locale,
      {
        tr: "Ilk demo kurulumu ile birlikte otomatik olusturulan oryantasyon egitimi kaydi.",
        en: "Orientation training record automatically created together with the first demo setup.",
        ar: "سجل تدريب تمهيدي أُنشئ تلقائياً مع إعداد العرض الأول.",
        ru: "Запись вводного обучения, автоматически созданная вместе с первой настройкой демо.",
        de: "Automatisch mit dem ersten Demo-Setup erstellter Einweisungseintrag.",
        fr: "Enregistrement de formation d'accueil cree automatiquement avec la premiere configuration demo.",
        es: "Registro de capacitacion inicial creado automaticamente con la primera configuracion demo.",
        zh: "随首次演示配置自动创建的入门培训记录。",
        ja: "最初のデモ設定と同時に自動作成された導入トレーニング記録です。",
        ko: "첫 데모 설정과 함께 자동 생성된 오리엔테이션 교육 기록입니다.",
        hi: "पहली डेमो सेटअप के साथ स्वचालित रूप से बनाया गया ओरिएंटेशन प्रशिक्षण रिकॉर्ड।",
        az: "Ilk demo qurulusu ile birlikde avtomatik yaradilan oriyentasiya telimi qeydi.",
        id: "Catatan pelatihan orientasi yang dibuat otomatis bersama penyiapan demo pertama.",
      },
      "Ilk demo kurulumu ile birlikte otomatik olusturulan oryantasyon egitimi kaydi.",
    ),
  };
}

export function buildLocalizedStarterNotification(
  locale: Locale,
  companyName: string,
  firstPrompt: DemoStarterPrompt | null,
) {
  return {
    title: pickLocalized(
      locale,
      {
        tr: "Demo kurulumu hazir",
        en: "Demo setup is ready",
        ar: "إعداد العرض التجريبي جاهز",
        ru: "Демо-настройка готова",
        de: "Demo-Setup ist bereit",
        fr: "Le setup demo est pret",
        es: "La configuracion demo esta lista",
        zh: "演示环境已准备就绪",
        ja: "デモ設定の準備ができました",
        ko: "데모 설정이 준비되었습니다",
        hi: "डेमो सेटअप तैयार है",
        az: "Demo qurulusu hazirdir",
        id: "Setup demo sudah siap",
      },
      "Demo kurulumu hazir",
    ),
    message: pickLocalized(
      locale,
      {
        tr: `${companyName} icin ilk dokuman, egitim ve Nova hizli baslangic kayitlari hazir. ${firstPrompt?.title || "Nova ile basla"} adimindan devam edebilirsin.`,
        en: `The first document, training, and Nova quick-start records for ${companyName} are ready. Continue with ${firstPrompt?.title || "Nova starter prompts"}.`,
        ar: `تم تجهيز أول المستندات والتدريب ونقاط البداية السريعة لـ Nova الخاصة بـ ${companyName}. يمكنك المتابعة من ${firstPrompt?.title || "بداية Nova"}.`,
        ru: `Для ${companyName} готовы первые документы, обучение и быстрые подсказки Nova. Продолжайте с шага ${firstPrompt?.title || "старт Nova"}.`,
        de: `Die ersten Dokumente, Schulungen und Nova-Schnellstarts fuer ${companyName} sind bereit. Weiter mit ${firstPrompt?.title || "Nova-Start"}.`,
        fr: `Les premiers documents, formations et invites Nova pour ${companyName} sont prets. Continuez avec ${firstPrompt?.title || "demarrage Nova"}.`,
        es: `Los primeros documentos, capacitaciones y accesos rapidos de Nova para ${companyName} estan listos. Continua con ${firstPrompt?.title || "inicio de Nova"}.`,
        zh: `${companyName} 的首批文档、培训和 Nova 快速开始内容已准备好。可从 ${firstPrompt?.title || "Nova 起步"} 继续。`,
        ja: `${companyName} 向けの最初の文書、トレーニング、Nova クイックスタートが準備できました。${firstPrompt?.title || "Nova 開始"} から進められます。`,
        ko: `${companyName}용 첫 문서, 교육, Nova 빠른 시작 항목이 준비되었습니다. ${firstPrompt?.title || "Nova 시작"}부터 진행하세요.`,
        hi: `${companyName} के लिए पहला दस्तावेज़, प्रशिक्षण और Nova क्विक-स्टार्ट सामग्री तैयार है। ${firstPrompt?.title || "Nova शुरुआत"} से आगे बढ़ें।`,
        az: `${companyName} ucun ilk sened, telim ve Nova suretli baslangic qeydleri hazirdir. ${firstPrompt?.title || "Nova baslangici"} ile davam ede bilersiniz.`,
        id: `Dokumen pertama, pelatihan, dan prompt awal Nova untuk ${companyName} sudah siap. Lanjutkan dari ${firstPrompt?.title || "awal Nova"}.`,
      },
      `${companyName} icin ilk dokuman, egitim ve Nova hizli baslangic kayitlari hazir. ${firstPrompt?.title || "Nova ile basla"} adimindan devam edebilirsin.`,
    ),
  };
}
