// ============================================================
// Group 6: Kaza/Olay — 7 sablon
// Group 7: Iletisim/Yazisma — 3 sablon
// Group 8: Talimatlar — 4 sablon
// Group 9: ISG Prosedurler — 19 sablon
// Group 10: Isletme Kontrol/Denetim — 4 sablon
// ============================================================

import { h, p, table, bullet } from './document-templates-p1';
import type { P1Template } from './document-templates-p1';

// ============================================================
// GROUP 6 — KAZA / OLAY
// ============================================================

export const GROUP6_TEMPLATES: P1Template[] = [
  {
    id: 'kaza-bildirim-formu',
    groupKey: 'kaza-olay',
    title: 'İş Kazası Bildirim Formu',
    description: '6331 sayılı Kanun kapsamında iş kazası bildirim belgesi',
    variables: ['firma_adi', 'uzman_adi', 'bugun', 'firma_adresi', 'firma_sehir'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İŞ KAZASI BİLDİRİM FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. İŞYERİ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['İşyeri Unvanı', '{{firma_adi}}'],
          ['Adres', '{{firma_adresi}}, {{firma_sehir}}'],
          ['Bildirim Tarihi', '{{bugun}}'],
        ]),
        h(2, '2. KAZAZEDE BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['T.C. Kimlik No', ''],
          ['Doğum Tarihi', ''],
          ['Görevi', ''],
          ['Departmanı', ''],
          ['SGK Sicil No', ''],
          ['İşe Giriş Tarihi', ''],
        ]),
        h(2, '3. KAZA BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Kaza Tarihi', ''],
          ['Kaza Saati', ''],
          ['Kaza Yeri', ''],
          ['Kaza sırasında yapılan iş', ''],
          ['Kazanın oluş şekli', ''],
          ['Yaralanma türü', ''],
          ['Yaralanan vücut bölgesi', ''],
          ['Tanık(lar)', ''],
        ]),
        h(2, '4. KAZA SONRASI'),
        table(['Bilgi', 'Değer'], [
          ['İlkyardım uygulandı mı', '☐ Evet  ☐ Hayır'],
          ['Hastaneye sevk edildi mi', '☐ Evet  ☐ Hayır'],
          ['İş günü kaybı var mı', '☐ Evet  ☐ Hayır — Kaç gün: ___'],
          ['SGK bildirimi yapıldı mı', '☐ Evet  ☐ Hayır — Tarih: ___'],
        ]),
        h(2, '5. İMZA'),
        p('6331 sayılı Kanun Madde 14: İşveren iş kazasını 3 iş günü içinde SGK\'ya bildirmekle yükümlüdür.'),
        table(['Bildirimi Yapan', 'İSG Uzmanı', 'İşveren'], [
          ['Ad Soyad:', '', '{{uzman_adi}}', ''],
          ['Tarih: {{bugun}}', 'Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:', 'İmza:'],
        ]),
      ],
    },
  },

  {
    id: 'kaza-arastirma-raporu',
    groupKey: 'kaza-olay',
    title: 'Kaza Araştırma Raporu',
    description: 'İş kazası detaylı araştırma ve analiz raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KAZA ARAŞTIRMA RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. KAZA ÖZETİ'),
        table(['Bilgi', 'Değer'], [
          ['Kaza Tarihi / Saati', ''],
          ['Kaza Yeri', ''],
          ['Kazazede', ''],
          ['Yaralanma Durumu', ''],
          ['Rapor No', ''],
        ]),
        h(2, '2. OLAY TANIMI'),
        p('Kazanın detaylı anlatımı:'),
        p(''),
        h(2, '3. OLAY YERİ İNCELEME'),
        bullet([
          'Fiziksel ortam koşulları: ',
          'Makine/ekipman durumu: ',
          'KKD kullanım durumu: ',
          'Gözetim durumu: ',
        ]),
        h(2, '4. TANIK İFADELERİ'),
        table(['Tanık', 'İfade Özeti'], [
          ['', ''],
          ['', ''],
        ]),
        h(2, '5. KÖK NEDEN ANALİZİ'),
        table(['Neden Türü', 'Açıklama'], [
          ['Doğrudan neden', ''],
          ['Güvensiz davranış', ''],
          ['Güvensiz durum', ''],
          ['Temel neden (yönetim)', ''],
        ]),
        h(2, '6. DÜZELTİCİ FAALİYETLER'),
        table(['No', 'Önlem', 'Sorumlu', 'Termin', 'Durum'], [
          ['1', '', '', '', '☐ Açık'],
          ['2', '', '', '', '☐ Açık'],
          ['3', '', '', '', '☐ Açık'],
        ]),
        h(2, '7. ONAY'),
        table(['Araştırmacı', 'İSG Uzmanı', 'İşveren'], [
          ['', '{{uzman_adi}}', ''],
          ['Tarih:', 'Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:', 'İmza:'],
        ]),
      ],
    },
  },

  {
    id: 'ramak-kala-formu',
    groupKey: 'kaza-olay',
    title: 'Ramak Kala Olay Bildirim Formu',
    description: 'Ramak kala (near miss) olay kayıt formu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'RAMAK KALA OLAY BİLDİRİM FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'BİLDİREN KİŞİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Departman', ''],
          ['Bildirim Tarihi', '{{bugun}}'],
        ]),
        h(2, 'OLAY BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Olay Tarihi', ''],
          ['Olay Saati', ''],
          ['Olay Yeri', ''],
          ['Potansiyel Sonuç', '☐ Ölüm  ☐ Ağır yaralanma  ☐ Hafif yaralanma  ☐ Maddi hasar'],
        ]),
        h(2, 'OLAY TANIMI'),
        p('Olayın detaylı anlatımı:'),
        p(''),
        h(2, 'OLASI NEDENLERİ'),
        bullet([
          '☐ Güvensiz davranış',
          '☐ Güvensiz durum / ortam',
          '☐ Ekipman arızası',
          '☐ Prosedür eksikliği',
          '☐ Eğitim eksikliği',
          '☐ KKD kullanılmaması',
          '☐ Diğer: ___________',
        ]),
        h(2, 'ÖNERİLEN ÖNLEMLER'),
        p(''),
        h(2, 'DEĞERLENDİRME'),
        table(['Değerlendiren', 'Sonuç'], [
          ['{{uzman_adi}} — İSG Uzmanı', ''],
          ['Tarih: {{bugun}}', 'Alınan önlem:'],
          ['İmza:', ''],
        ]),
        p('6331 sayılı Kanun Madde 14: Ramak kala olaylar kayıt altına alınmalıdır.'),
      ],
    },
  },

  {
    id: 'dof-formu',
    groupKey: 'kaza-olay',
    title: 'Düzeltici ve Önleyici Faaliyet (DÖF) Formu',
    description: 'Uygunsuzluk için düzeltici ve önleyici faaliyet belgesi',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'DÜZELTİCİ VE ÖNLEYİCİ FAALİYET (DÖF) FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'UYGUNSUZLUK BİLGİSİ'),
        table(['Bilgi', 'Değer'], [
          ['DÖF No', ''],
          ['Tespit Tarihi', '{{bugun}}'],
          ['Tespit Eden', '{{uzman_adi}}'],
          ['Kaynak', '☐ İç denetim  ☐ Kaza/Olay  ☐ Şikayet  ☐ Gözlem  ☐ Diğer'],
          ['Uygunsuzluk Tanımı', ''],
        ]),
        h(2, 'ACİL DÜZELTME (Varsa)'),
        p(''),
        h(2, 'KÖK NEDEN ANALİZİ'),
        p(''),
        h(2, 'DÜZELTİCİ FAALİYET'),
        table(['No', 'Faaliyet', 'Sorumlu', 'Termin'], [
          ['1', '', '', ''],
          ['2', '', '', ''],
        ]),
        h(2, 'ÖNLEYİCİ FAALİYET'),
        table(['No', 'Faaliyet', 'Sorumlu', 'Termin'], [
          ['1', '', '', ''],
          ['2', '', '', ''],
        ]),
        h(2, 'ETKİNLİK DEĞERLENDİRME'),
        table(['Bilgi', 'Değer'], [
          ['Değerlendirme Tarihi', ''],
          ['Faaliyet etkili mi', '☐ Evet  ☐ Hayır'],
          ['Açıklama', ''],
          ['Kapanış Onayı', ''],
        ]),
        table(['Açan', 'Kapatan'], [
          ['{{uzman_adi}}', ''],
          ['Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:'],
        ]),
      ],
    },
  },

  {
    id: 'kaza-istatistik',
    groupKey: 'kaza-olay',
    title: 'Kaza İstatistik Raporu',
    description: 'Dönemsel iş kazası istatistikleri ve analizi',
    variables: ['firma_adi', 'uzman_adi', 'bugun', 'yil', 'personel_sayisi'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İŞ KAZASI İSTATİSTİK RAPORU — {{yil}}'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. GENEL BİLGİLER'),
        table(['Bilgi', 'Değer'], [
          ['Rapor Dönemi', '{{yil}}'],
          ['Çalışan Sayısı', '{{personel_sayisi}}'],
          ['Hazırlayan', '{{uzman_adi}}'],
        ]),
        h(2, '2. KAZA İSTATİSTİKLERİ'),
        table(['Gösterge', 'Değer'], [
          ['Toplam iş kazası sayısı', ''],
          ['İş günü kayıplı kaza sayısı', ''],
          ['Toplam kayıp iş günü', ''],
          ['Ramak kala olay sayısı', ''],
          ['Kaza sıklık hızı (Frekans)', ''],
          ['Kaza ağırlık hızı (Şiddet)', ''],
        ]),
        h(2, '3. KAZA DAĞILIMI'),
        table(['Kriter', 'Kategori', 'Sayı', 'Oran'], [
          ['Türüne göre', 'Düşme', '', ''],
          ['', 'Sıkışma', '', ''],
          ['', 'Kesilme', '', ''],
          ['', 'Çarpma', '', ''],
          ['', 'Diğer', '', ''],
          ['Bölgeye göre', 'Üretim', '', ''],
          ['', 'Depo', '', ''],
          ['', 'Ofis', '', ''],
          ['', 'Diğer', '', ''],
        ]),
        h(2, '4. DEĞERLENDİRME VE ÖNERİLER'),
        p(''),
        table(['Hazırlayan', 'Onaylayan'], [
          ['{{uzman_adi}} — İSG Uzmanı', 'İşveren / İşveren Vekili'],
          ['Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:'],
        ]),
      ],
    },
  },

  {
    id: 'kok-neden-analizi',
    groupKey: 'kaza-olay',
    title: 'Kök Neden Analizi Raporu',
    description: 'İş kazası veya uygunsuzluk kök neden analiz raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KÖK NEDEN ANALİZİ RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. OLAY BİLGİSİ'),
        table(['Bilgi', 'Değer'], [
          ['Olay / Kaza Tarihi', ''],
          ['Olay Yeri', ''],
          ['Olay Tanımı', ''],
          ['Analiz Tarihi', '{{bugun}}'],
          ['Analiz Ekibi', '{{uzman_adi}}'],
        ]),
        h(2, '2. NEDEN-SONUÇ ZİNCİRİ (5 NEDEN YÖNTEMİ)'),
        table(['Sıra', 'Neden Sorusu', 'Yanıt'], [
          ['1. Neden?', 'Olay neden meydana geldi?', ''],
          ['2. Neden?', 'Birinci neden neden oluştu?', ''],
          ['3. Neden?', 'İkinci neden neden oluştu?', ''],
          ['4. Neden?', 'Üçüncü neden neden oluştu?', ''],
          ['5. Neden?', 'Dördüncü neden neden oluştu?', ''],
        ]),
        h(2, '3. KÖK NEDENLER'),
        table(['Kategori', 'Kök Neden', 'Açıklama'], [
          ['İnsan faktörü', '', ''],
          ['Ekipman / malzeme', '', ''],
          ['Çevre / ortam', '', ''],
          ['Yönetim sistemi', '', ''],
          ['Prosedür / talimat', '', ''],
        ]),
        h(2, '4. DÜZELTİCİ AKSİYONLAR'),
        table(['No', 'Aksiyon', 'Sorumlu', 'Termin'], [
          ['1', '', '', ''],
          ['2', '', '', ''],
          ['3', '', '', ''],
        ]),
        p(''),
        p('Hazırlayan: {{uzman_adi}} — Tarih: {{bugun}}'),
      ],
    },
  },

  {
    id: 'olay-degerlendirme',
    groupKey: 'kaza-olay',
    title: 'Olay Değerlendirme Raporu',
    description: 'Genel olay (kaza, ramak kala, çevre) değerlendirme raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'OLAY DEĞERLENDİRME RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. OLAY BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Olay Türü', '☐ İş Kazası  ☐ Ramak Kala  ☐ Meslek Hastalığı  ☐ Çevre Olayı  ☐ Diğer'],
          ['Olay Tarihi / Saati', ''],
          ['Olay Yeri', ''],
          ['Etkilenen Kişi(ler)', ''],
        ]),
        h(2, '2. OLAY AÇIKLAMASI'),
        p(''),
        h(2, '3. ANALİZ'),
        table(['Kriter', 'Değerlendirme'], [
          ['Mevcut kontroller yeterli miydi?', ''],
          ['Prosedüre uyulmuş muydu?', ''],
          ['KKD kullanılmış mıydı?', ''],
          ['Eğitim yeterli miydi?', ''],
          ['Benzer olay daha önce yaşandı mı?', ''],
        ]),
        h(2, '4. SONUÇ VE AKSİYONLAR'),
        table(['No', 'Aksiyon', 'Sorumlu', 'Termin'], [
          ['1', '', '', ''],
          ['2', '', '', ''],
        ]),
        p(''),
        table(['Değerlendiren', 'Onaylayan'], [
          ['{{uzman_adi}} — İSG Uzmanı', 'İşveren / İşveren Vekili'],
          ['Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:'],
        ]),
      ],
    },
  },
];

// ============================================================
// GROUP 7 — İLETİŞİM / YAZIŞMA
// ============================================================

export const GROUP7_TEMPLATES: P1Template[] = [
  {
    id: 'resmi-yazi',
    groupKey: 'iletisim-yazisma',
    title: 'Resmi Yazı',
    description: 'İSG konulu resmi kurum yazışma şablonu',
    variables: ['firma_adi', 'firma_adresi', 'firma_sehir', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'RESMİ YAZI'),
        p('{{firma_adi}}'),
        p('{{firma_adresi}}, {{firma_sehir}}'),
        { type: 'horizontalRule' },
        p('Sayı  : ______/______'),
        p('Konu  : '),
        p('Tarih : {{bugun}}'),
        p(''),
        p('_______________________ MÜDÜRLÜĞÜNE / BAŞKANLIĞINA'),
        p(''),
        p('İlgi  : '),
        p(''),
        p('6331 sayılı İş Sağlığı ve Güvenliği Kanunu kapsamında aşağıdaki hususu bilgilerinize arz ederiz.'),
        p(''),
        p('[Yazı içeriği bu alana yazılacaktır.]'),
        p(''),
        p('Gereğini bilgilerinize arz ederiz.'),
        p('Saygılarımızla,'),
        p(''),
        table(['Hazırlayan', 'Onaylayan'], [
          ['{{uzman_adi}} — İSG Uzmanı', 'İşveren / İşveren Vekili'],
          ['İmza:', 'İmza:'],
          ['Tarih: {{bugun}}', 'Tarih:'],
        ]),
        p(''),
        p('Ek   : '),
        p('Dağıtım: '),
      ],
    },
  },

  {
    id: 'uyari-yazisi',
    groupKey: 'iletisim-yazisma',
    title: 'İSG Uyarı Yazısı',
    description: 'Çalışana veya birime İSG ihlali uyarı bildirimi',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG UYARI YAZISI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'UYARI BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Uyarı No', ''],
          ['Tarih', '{{bugun}}'],
          ['Uyarılan Kişi / Birim', ''],
          ['Departman', ''],
          ['Uyarı Konusu', ''],
          ['Uyarı Sayısı', '☐ 1. Uyarı  ☐ 2. Uyarı  ☐ 3. Uyarı (Son)'],
        ]),
        h(2, 'UYARI DETAYI'),
        p('6331 sayılı İSG Kanunu ve ilgili yönetmelikler kapsamında aşağıdaki İSG ihlali/uygunsuzluğu tespit edilmiştir:'),
        p(''),
        p('Tespit edilen ihlal:'),
        p(''),
        p('İhlal edilen kural/prosedür:'),
        p(''),
        h(2, 'YAPILMASI GEREKEN'),
        p('Yukarıda belirtilen uygunsuzluğun derhal düzeltilmesi ve tekrarının önlenmesi gerekmektedir.'),
        p(''),
        h(2, 'BİLGİLENDİRME'),
        p('Bu uyarının tekrarı halinde 6331 sayılı Kanun Madde 26 kapsamında idari yaptırımlar uygulanabilir.'),
        p(''),
        table(['Uyaran', 'Uyarılan', 'Birim Amiri'], [
          ['{{uzman_adi}}', '', ''],
          ['İSG Uzmanı', 'Ad Soyad', 'Ad Soyad'],
          ['Tarih: {{bugun}}', 'Tarih:', 'Tarih:'],
          ['İmza:', 'İmza:', 'İmza:'],
        ]),
      ],
    },
  },

  {
    id: 'bilgilendirme-yazisi',
    groupKey: 'iletisim-yazisma',
    title: 'İSG Bilgilendirme Yazısı',
    description: 'Çalışanlara yönelik genel İSG bilgilendirme duyurusu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG BİLGİLENDİRME YAZISI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        p('Tarih: {{bugun}}'),
        p('Konu: '),
        p(''),
        p('Sayın Çalışanlarımız,'),
        p(''),
        p('6331 sayılı İş Sağlığı ve Güvenliği Kanunu kapsamında aşağıdaki konuda bilgilendirilmeniz gerekmektedir:'),
        p(''),
        p('[Bilgilendirme içeriği bu alana yazılacaktır.]'),
        p(''),
        h(2, 'ÖNEMLİ HATIRLATMALAR'),
        bullet([
          'İSG kurallarına eksiksiz uyulması zorunludur.',
          'Kişisel koruyucu donanımların eksiksiz kullanılması gerekmektedir.',
          'Herhangi bir tehlike veya uygunsuzluk gördüğünüzde İSG birimine bildiriniz.',
          'Sorularınız için İSG uzmanınıza başvurabilirsiniz.',
        ]),
        p(''),
        p('Bilgilerinize sunarız.'),
        p('Saygılarımızla,'),
        p(''),
        p('{{uzman_adi}}'),
        p('İSG Uzmanı'),
        p('Tarih: {{bugun}}'),
      ],
    },
  },
];

// ============================================================
// GROUP 8 — TALİMATLAR
// ============================================================

export const GROUP8_TEMPLATES: P1Template[] = [
  {
    id: 'genel-isg-talimati',
    groupKey: 'talimatlar',
    title: 'Genel İSG Talimatı',
    description: 'İşyeri genelinde geçerli temel İSG kuralları talimatı',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'GENEL İŞ SAĞLIĞI VE GÜVENLİĞİ TALİMATI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. AMAÇ'),
        p('İşyerinde çalışan tüm personelin uyması gereken temel İSG kurallarını belirlemek.'),
        h(2, '2. KAPSAM'),
        p('{{firma_adi}} bünyesinde çalışan tüm personeli, taşeron çalışanlarını ve ziyaretçileri kapsar.'),
        h(2, '3. GENEL KURALLAR'),
        bullet([
          'İşe başlamadan önce çalışma alanınızı ve ekipmanlarınızı kontrol edin.',
          'Belirlenen KKD\'leri eksiksiz kullanın.',
          'Eğitimini almadığınız makine ve ekipmanları kullanmayın.',
          'Alkol veya uyuşturucu etkisi altında işe gelmeyin.',
          'Acil çıkış yollarını ve toplanma noktasını bilin.',
          'İş kazası, ramak kala veya tehlikeli durumları derhal bildirin.',
          'Çalışma ortamını temiz ve düzenli tutun.',
          'Elektrikli aletlerin kablolarını kontrol edin.',
          'Yüksekte çalışma, sıcak çalışma gibi özel işlerde iş izni alın.',
          'Yemek, sigara gibi aktiviteleri yalnızca belirlenen alanlarda yapın.',
        ]),
        h(2, '4. YASAKLAR'),
        bullet([
          'Koruma tertibatlarını çıkarmak veya devre dışı bırakmak yasaktır.',
          'Yetkisiz alanlara girmek yasaktır.',
          'Hız sınırlarını aşmak yasaktır.',
          'Şaka amaçlı tehlikeli davranışlar yasaktır.',
        ]),
        h(2, '5. YAPTIRIMLAR'),
        p('Bu talimata uyulmaması halinde 6331 sayılı Kanun Madde 26 kapsamında disiplin işlemi uygulanabilir.'),
        p(''),
        p('Hazırlayan: {{uzman_adi}} — Tarih: {{bugun}}'),
        p('Onaylayan: İşveren / İşveren Vekili'),
      ],
    },
  },

  {
    id: 'makine-talimati',
    groupKey: 'talimatlar',
    title: 'Makine Kullanım Talimatı',
    description: 'Makine ve ekipman güvenli kullanım talimatı şablonu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'MAKİNE KULLANIM TALİMATI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. MAKİNE BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Makine Adı', ''],
          ['Marka / Model', ''],
          ['Bulunduğu Alan', ''],
          ['Talimat No', ''],
          ['Revizyon Tarihi', '{{bugun}}'],
        ]),
        h(2, '2. ÇALIŞTIRMA ÖNCESİ KONTROLLER'),
        bullet([
          'Koruma tertibatlarının yerinde ve çalışır durumda olduğunu kontrol edin.',
          'Acil durdurma butonunun çalıştığından emin olun.',
          'Gerekli KKD\'leri giyin (koruyucu gözlük, eldiven, kulak tıkacı vb.).',
          'Çalışma alanının temiz ve düzenli olduğundan emin olun.',
          'Yağlama ve bakım durumunu kontrol edin.',
          'Gevşek giysi, takı, uzun saç gibi sıkışma riski oluşturacak unsurları giderin.',
        ]),
        h(2, '3. ÇALIŞTIRMA KURALLARI'),
        bullet([
          'Yalnızca eğitimli ve yetkilendirilmiş personel makineyi kullanabilir.',
          'Makineyi üretici talimatlarına uygun şekilde çalıştırın.',
          'Çalışma sırasında koruma kapakları kapalı olmalıdır.',
          'Makine çalışırken ayar ve bakım yapmayın.',
          'Anormal ses, titreşim veya koku durumunda makineyi durdurun.',
        ]),
        h(2, '4. ÇALIŞTIRMA SONRASI'),
        bullet([
          'Makineyi uygun prosedürle kapatın.',
          'Çalışma alanını temizleyin.',
          'Tespit ettiğiniz arızaları kaydedin ve bildirin.',
          'Enerji kaynaklarını kesin (gerekiyorsa).',
        ]),
        h(2, '5. ACİL DURUMLAR'),
        p('Kaza veya arıza durumunda acil durdurma butonuna basın. İlkyardım gerekiyorsa İSG birimine haber verin.'),
        p(''),
        p('6331 sayılı Kanun Madde 17 ve İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği gereğince düzenlenmiştir.'),
        p('Hazırlayan: {{uzman_adi}} — Tarih: {{bugun}}'),
      ],
    },
  },

  {
    id: 'kimyasal-talimati',
    groupKey: 'talimatlar',
    title: 'Kimyasal Madde Kullanım Talimatı',
    description: 'Kimyasal maddelerin güvenli kullanımı, depolanması ve bertarafı talimatı',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KİMYASAL MADDE KULLANIM TALİMATI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. AMAÇ'),
        p('İşyerinde kullanılan kimyasal maddelerin güvenli kullanımı, taşınması, depolanması ve bertarafına ilişkin kuralları belirlemek.'),
        h(2, '2. KİŞİSEL KORUYUCU DONANIMLAR'),
        bullet([
          'Kimyasal madde ile çalışırken uygun KKD kullanılmalıdır.',
          'Koruyucu eldiven (kimyasala uygun tipte)',
          'Koruyucu gözlük / yüz siperi',
          'Solunum koruyucu (uygun filtre tipi)',
          'Kimyasala dayanıklı önlük / tulum',
        ]),
        h(2, '3. KULLANIM KURALLARI'),
        bullet([
          'Kullanmadan önce Güvenlik Bilgi Formu\'nu (MSDS/SDS) okuyun.',
          'Kimyasalları yalnızca orijinal veya etiketli kaplarda bulundurun.',
          'Uyumsuz kimyasalları bir arada depolamayın.',
          'Yeme, içme, sigara içme alanlarında kimyasal bulundurmayın.',
          'Dökülme durumunda dökülme setini kullanın.',
          'Kullanım sonrası kapları sıkıca kapatın.',
        ]),
        h(2, '4. DEPOLAMA KURALLARI'),
        bullet([
          'Havalandırmalı, kilitli alanlarda depolayın.',
          'Direkt güneş ışığından ve ısı kaynaklarından uzak tutun.',
          'Uyumsuzluk tablosuna göre ayrı depolayın.',
          'Döşeme üzerine direkt koymayın, raf/palet kullanın.',
        ]),
        h(2, '5. ACİL DURUM'),
        p('Kimyasal sızıntı veya temas durumunda: bölgeyi terk edin, KKD giyin, MSDS formundaki ilkyardım talimatlarını uygulayın. 112\'yi arayın.'),
        p(''),
        p('Kimyasal Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik gereğince düzenlenmiştir.'),
        p('Hazırlayan: {{uzman_adi}} — Tarih: {{bugun}}'),
      ],
    },
  },

  {
    id: 'kkd-kullanim-talimati',
    groupKey: 'talimatlar',
    title: 'KKD Kullanım Talimatı',
    description: 'Kişisel koruyucu donanım seçimi ve kullanım kuralları talimatı',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KİŞİSEL KORUYUCU DONANIM (KKD) KULLANIM TALİMATI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. AMAÇ'),
        p('Kişisel koruyucu donanımların doğru seçimi, kullanımı, bakımı ve saklanmasına ilişkin kuralları belirlemek.'),
        h(2, '2. KKD TÜRLERİ VE KULLANIM ALANLARI'),
        table(
          ['KKD Türü', 'Koruma Alanı', 'Kullanım Yeri', 'Standart'],
          [
            ['Baret', 'Kafa', 'Üretim, inşaat, depo alanları', 'EN 397'],
            ['Koruyucu gözlük', 'Göz', 'Talaşlı imalat, kimyasal, kaynak', 'EN 166'],
            ['Kulaklık / kulak tıkacı', 'İşitme', '85 dB üzeri gürültülü alanlar', 'EN 352'],
            ['Koruyucu eldiven', 'El', 'Kimyasal, mekanik, termal riskler', 'EN 388/374'],
            ['Güvenlik ayakkabısı', 'Ayak', 'Tüm üretim alanları', 'EN ISO 20345'],
            ['Toz maskesi / gaz maskesi', 'Solunum', 'Tozlu, gazlı ortamlar', 'EN 149/140'],
            ['Emniyet kemeri', 'Vücut', 'Yüksekte çalışma (1.5 m üzeri)', 'EN 361'],
            ['Reflektif yelek', 'Vücut', 'Araç trafiği olan alanlar', 'EN ISO 20471'],
          ]
        ),
        h(2, '3. GENEL KURALLAR'),
        bullet([
          'Belirlenen KKD\'ler ilgili alanlarda mutlaka kullanılmalıdır.',
          'KKD kullanmadan çalışmaya başlamak yasaktır.',
          'Hasarlı KKD\'leri derhal değiştirin ve İSG birimine bildirin.',
          'KKD\'leri temiz ve bakımlı tutun.',
          'KKD\'leri başkalarıyla paylaşmayın (hijyen).',
          'Son kullanma tarihini kontrol edin.',
        ]),
        h(2, '4. BAKIM VE SAKLAMA'),
        bullet([
          'Kullanım sonrası temizleyin ve uygun yerde saklayın.',
          'Üretici talimatlarına göre bakım yapın.',
          'Direkt güneş ışığı ve nemden koruyun.',
          'Periyodik kontrol ve değişim tarihlerine uyun.',
        ]),
        p(''),
        p('KKD Yönetmeliği ve 6331 sayılı Kanun Madde 5 gereğince düzenlenmiştir.'),
        p('Hazırlayan: {{uzman_adi}} — Tarih: {{bugun}}'),
      ],
    },
  },
];

// ============================================================
// GROUP 9 — İSG PROSEDÜRLERİ (19 adet — kısa ve profesyonel)
// ============================================================

function prosedur(
  id: string,
  title: string,
  description: string,
  amac: string,
  kapsam: string,
  adimlar: string[],
  sorumlular: string[],
  yasal: string,
): P1Template {
  return {
    id,
    groupKey: 'isg-prosedurler',
    title,
    description,
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, title.toUpperCase()),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. AMAÇ'),
        p(amac),
        h(2, '2. KAPSAM'),
        p(kapsam),
        h(2, '3. PROSEDÜR ADIMLARI'),
        bullet(adimlar),
        h(2, '4. SORUMLULUKLAR'),
        bullet(sorumlular),
        h(2, '5. YASAL DAYANAK'),
        p(yasal),
        h(2, '6. REVİZYON VE ONAY'),
        table(['Hazırlayan', 'Onaylayan'], [
          ['{{uzman_adi}} — İSG Uzmanı', 'İşveren / İşveren Vekili'],
          ['Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:'],
        ]),
      ],
    },
  };
}

export const GROUP9_TEMPLATES: P1Template[] = [
  prosedur(
    'isg-politikasi',
    'İSG Politikası',
    'İşyeri iş sağlığı ve güvenliği politika belgesi',
    'İşyerinin İSG taahhüdünü, hedeflerini ve ilkelerini belirlemek.',
    '{{firma_adi}} bünyesindeki tüm faaliyetleri, çalışanları, taşeron personelini ve ziyaretçileri kapsar.',
    [
      'İSG mevzuatına ve uluslararası standartlara tam uyum sağlanır.',
      'Tüm çalışanların sağlık ve güvenliği en öncelikli hedeftir.',
      'Risk değerlendirme sonuçlarına göre sürekli iyileştirme yapılır.',
      'Çalışanların İSG konusunda eğitimi ve bilinçlendirilmesi sağlanır.',
      'İş kazası ve meslek hastalıklarının önlenmesi için gerekli tüm tedbirler alınır.',
      'Acil durumlara hazırlıklı olunması sağlanır.',
      'İSG hedefleri düzenli olarak gözden geçirilir ve güncellenir.',
    ],
    [
      'İşveren: Politikanın uygulanması için kaynak sağlar.',
      'İSG uzmanı: Politikanın hayata geçirilmesini koordine eder.',
      'Tüm çalışanlar: Politika ilkelerine uyar.',
    ],
    '6331 sayılı İSG Kanunu Madde 4, 5 — İşverenin genel yükümlülüğü',
  ),

  prosedur(
    'risk-degerlendirme-prosedur',
    'Risk Değerlendirme Prosedürü',
    'Risk değerlendirme sürecinin yönetim prosedürü',
    'İşyerinde sistematik risk değerlendirme faaliyetlerinin nasıl yürütüleceğini belirlemek.',
    'İşyerindeki tüm bölümler, faaliyetler ve çalışma koşullarını kapsar.',
    [
      'Risk değerlendirme ekibi oluşturulur (İSG uzmanı, hekim, işveren temsilcisi, çalışan temsilcisi).',
      'Tehlike tanımlama: Tüm bölümlerde ve faaliyetlerde tehlikeler belirlenir.',
      'Risk analizi: Her tehlike için olasılık ve şiddet değerlendirmesi yapılır (5×5 matris veya Fine-Kinney).',
      'Risk değerlendirme: Hesaplanan skor kabul edilebilirlik kriterlerine göre sınıflandırılır.',
      'Kontrol tedbirleri belirlenir: Eliminasyon, substitüsyon, mühendislik, idari kontrol, KKD hiyerarşisi uygulanır.',
      'Aksiyon planı hazırlanır: Sorumlu, termin, bütçe atanır.',
      'Uygulama ve izleme: Aksiyonların gerçekleştirilmesi takip edilir.',
      'Yenileme: Yılda en az 1 kez veya değişiklik/kaza durumunda güncellenir.',
    ],
    [
      'İSG Uzmanı: Ekip koordinasyonu, tehlike tanımlama, rapor hazırlama',
      'İşyeri Hekimi: Sağlık risklerinin değerlendirmesi',
      'Çalışan Temsilcisi: Saha bilgisi ve katılım',
      'İşveren: Onay ve kaynak sağlama',
    ],
    '6331 sayılı Kanun Madde 10 ve İSG Risk Değerlendirmesi Yönetmeliği',
  ),

  prosedur(
    'egitim-proseduru',
    'Eğitim Prosedürü',
    'İSG eğitimlerinin planlanması ve yürütülmesi prosedürü',
    'İSG eğitimlerinin planlanması, verilmesi, kaydedilmesi ve etkinliğinin değerlendirilmesine ilişkin usulleri belirlemek.',
    'İşyerindeki tüm çalışanların İSG eğitimlerini kapsar.',
    [
      'Eğitim ihtiyaç analizi yapılır (risk değerlendirme, kaza istatistik, mevzuat).',
      'Yıllık eğitim planı hazırlanır ve onaylanır.',
      'Eğitim içerikleri ve materyalleri hazırlanır.',
      'Eğitimler planına uygun şekilde verilir.',
      'Katılım formları imzalatılır ve dosyalanır.',
      'Eğitim sonrası değerlendirme (test/anket) yapılır.',
      'Eğitim etkinliği ölçülür ve raporlanır.',
      'Yeni işe başlayanlara oryantasyon eğitimi verilir.',
    ],
    [
      'İSG Uzmanı: Eğitim planlaması, içerik hazırlığı, eğitim verilmesi',
      'İnsan Kaynakları: Katılım koordinasyonu, kayıt yönetimi',
      'Birim amirleri: Personelin eğitime katılımının sağlanması',
    ],
    '6331 sayılı Kanun Madde 17 ve Çalışanların İSG Eğitimlerinin Usul ve Esasları Hakkında Yönetmelik',
  ),

  prosedur(
    'acil-durum-prosedur',
    'Acil Durum Prosedürü',
    'Acil durumlarda uygulanacak genel prosedür',
    'Yangın, deprem, patlama, kimyasal sızıntı gibi acil durumlarda uygulanacak müdahale ve tahliye prosedürlerini belirlemek.',
    'İşyerindeki tüm acil durum senaryolarını ve tüm personeli kapsar.',
    [
      'Acil durum planı hazırlanır ve güncel tutulur.',
      'Acil durum ekipleri (söndürme, kurtarma, koruma, ilkyardım) belirlenir.',
      'Ekiplere görevlendirme eğitimi verilir.',
      'Acil durum tespit edildiğinde alarm sistemi devreye alınır.',
      'Tahliye prosedürü başlatılır ve personel toplanma noktasına yönlendirilir.',
      'Yoklama alınır ve eksik personel bildirimi yapılır.',
      'Yılda en az 1 kez tahliye tatbikatı yapılır.',
      'Tatbikat sonuçları değerlendirilir ve plan güncellenir.',
    ],
    [
      'Acil Durum Koordinatörü: Genel koordinasyon ve karar alma',
      'Ekip başları: Görev alanlarındaki müdahale ve tahliye',
      'İSG Uzmanı: Plan hazırlama, eğitim ve tatbikat koordinasyonu',
      'Tüm çalışanlar: Talimatlara uyma ve tatbikatlara katılım',
    ],
    '6331 sayılı Kanun Madde 11-12 ve İşyerlerinde Acil Durumlar Hakkında Yönetmelik',
  ),

  prosedur(
    'kaza-bildirimi-prosedur',
    'Kaza Bildirimi Prosedürü',
    'İş kazası bildirim ve raporlama prosedürü',
    'İş kazası ve ramak kala olaylarının bildirilmesi, araştırılması ve raporlanmasına ilişkin süreçleri belirlemek.',
    'İşyerinde meydana gelen tüm iş kazaları ve ramak kala olaylarını kapsar.',
    [
      'Kaza meydana geldiğinde önce kazazedeye ilkyardım uygulanır.',
      'Olay yeri güvene alınır ve deliller korunur.',
      'Birim amiri ve İSG uzmanı derhal bilgilendirilir.',
      'Kaza bildirim formu doldurulur.',
      'SGK\'ya 3 iş günü içinde bildirim yapılır.',
      'Kaza araştırma raporu hazırlanır.',
      'Kök neden analizi yapılır.',
      'Düzeltici/önleyici faaliyetler planlanır ve takip edilir.',
      'Risk değerlendirmesi güncellenir.',
    ],
    [
      'Tespit eden kişi: İlk müdahale ve bilgilendirme',
      'Birim amiri: İlk bildirim ve olay yeri güvenliği',
      'İSG Uzmanı: Kaza araştırma, rapor, SGK bildirimi',
      'İnsan Kaynakları: SGK iş ve işlemleri',
    ],
    '6331 sayılı Kanun Madde 14 ve 5510 sayılı Kanun Madde 13',
  ),

  prosedur(
    'kkd-proseduru',
    'KKD Yönetim Prosedürü',
    'Kişisel koruyucu donanım seçimi, temini ve kullanım prosedürü',
    'Kişisel koruyucu donanımların ihtiyaç belirleme, temin, dağıtım, kullanım ve değişim süreçlerini belirlemek.',
    'İşyerinde KKD kullanması gereken tüm çalışanları ve tüm KKD türlerini kapsar.',
    [
      'Risk değerlendirmesine göre KKD ihtiyacı belirlenir.',
      'CE işaretli, uygun standartlarda KKD seçimi yapılır.',
      'KKD zimmet formu ile çalışana teslim edilir.',
      'Çalışanlara KKD kullanım eğitimi verilir.',
      'KKD kullanımı saha denetimleriyle takip edilir.',
      'Hasarlı veya süresi dolan KKD\'ler değiştirilir.',
      'KKD envanter ve zimmet kayıtları tutulur.',
    ],
    [
      'İSG Uzmanı: İhtiyaç belirleme, uygunluk kontrolü, eğitim',
      'Satın alma: Temin ve stok yönetimi',
      'Birim amirleri: Kullanım takibi',
      'Çalışanlar: Doğru kullanım ve bakım',
    ],
    '6331 sayılı Kanun Madde 5 ve Kişisel Koruyucu Donanımların İşyerlerinde Kullanılması Hakkında Yönetmelik',
  ),

  prosedur(
    'saglik-gozetimi-prosedur',
    'Sağlık Gözetimi Prosedürü',
    'Çalışan sağlık gözetimi ve muayene prosedürü',
    'Çalışanların işe giriş, periyodik ve işe dönüş sağlık muayenelerinin yönetilmesine ilişkin süreçleri belirlemek.',
    'İşyerindeki tüm çalışanları ve tüm sağlık muayene türlerini kapsar.',
    [
      'İşe giriş muayenesi: İşe başlamadan önce sağlık raporu alınır.',
      'Periyodik muayene: Tehlike sınıfına göre (az tehlikeli: 5 yıl, tehlikeli: 3 yıl, çok tehlikeli: 1 yıl) yapılır.',
      'İş değişikliği muayenesi: Görev değişikliğinde yapılır.',
      'İşe dönüş muayenesi: Uzun süreli hastalık sonrası yapılır.',
      'Muayene sonuçları kişisel sağlık dosyasında saklanır.',
      'Meslek hastalığı şüphesinde ilgili mercilere bildirim yapılır.',
    ],
    [
      'İşyeri Hekimi: Muayene, değerlendirme, rapor',
      'İSG Uzmanı: Takip ve koordinasyon',
      'İnsan Kaynakları: Randevu planlaması, kayıt yönetimi',
    ],
    '6331 sayılı Kanun Madde 15 ve İşyeri Hekimi ve Diğer Sağlık Personelinin Görev Yetki Sorumluluk ve Eğitimleri Hakkında Yönetmelik',
  ),

  prosedur(
    'is-izni-proseduru',
    'İş İzni Prosedürü',
    'Tehlikeli işler için iş izni yönetim prosedürü',
    'Yüksekte çalışma, sıcak çalışma, kapalı alan, elektrik işleri gibi tehlikeli faaliyetler için iş izni sistemini belirlemek.',
    'İş izni gerektiren tüm tehlikeli faaliyetleri kapsar.',
    [
      'İş izni formu, çalışma başlamadan önce ilgili birim tarafından doldurulur.',
      'İSG uzmanı çalışma koşullarını ve güvenlik tedbirlerini değerlendirir.',
      'Gerekli KKD, ölçüm cihazları ve güvenlik ekipmanları hazırlanır.',
      'İş izni yetkili tarafından onaylanır.',
      'Çalışma süresi boyunca güvenlik tedbirleri izlenir.',
      'Çalışma tamamlandığında iş izni kapatılır.',
      'Acil durumda iş izni derhal iptal edilir.',
    ],
    [
      'Çalışmayı talep eden birim: İş izni başvurusu',
      'İSG Uzmanı: Değerlendirme ve güvenlik koşullarının belirlenmesi',
      'Yetkili amir: Onay',
      'Çalışanlar: Belirtilen güvenlik koşullarına uyum',
    ],
    '6331 sayılı Kanun Madde 10 ve ilgili özel yönetmelikler',
  ),

  prosedur(
    'yuksekte-calisma',
    'Yüksekte Çalışma Prosedürü',
    'Yüksekte çalışma güvenliği prosedürü',
    '1.5 metre ve üzerindeki yüksekliklerde yapılan çalışmalarda güvenlik kurallarını belirlemek.',
    'İşyerinde yüksekte yapılan tüm çalışmaları (merdiven, iskele, platform, çatı vb.) kapsar.',
    [
      'Yüksekte çalışma için iş izni alınır.',
      'Çalışanların sağlık durumu (yükseklik korkusu, baş dönmesi vb.) kontrol edilir.',
      'Uygun KKD sağlanır: tam vücut emniyet kemeri, yaşam hattı, baret.',
      'Çalışma platformları, iskeleler güvenlik kontrolünden geçirilir.',
      'Çalışma alanı bariyerlerle çevrilir, uyarı levhaları konulur.',
      'Olumsuz hava koşullarında (rüzgar, yağmur, buzlanma) çalışma yapılmaz.',
      'İki kişiden az personelle yüksekte çalışılmaz.',
      'Düşme önleme ve durdurma sistemleri kontrol edilir.',
    ],
    [
      'İSG Uzmanı: İş izni değerlendirme, güvenlik denetimi',
      'Birim amiri: Ekipman kontrolü, personel gözetimi',
      'Çalışanlar: KKD kullanımı, güvenlik kurallarına uyum',
    ],
    'Yapı İşlerinde İSG Yönetmeliği ve 6331 sayılı Kanun',
  ),

  prosedur(
    'kapali-alan',
    'Kapalı Alan Çalışma Prosedürü',
    'Kapalı/sınırlı alanlarda çalışma güvenliği prosedürü',
    'Tank, kuyu, silo, boru, kanal gibi kapalı alanlarda güvenli çalışma koşullarını belirlemek.',
    'İşyerindeki tüm kapalı/sınırlı alan çalışmalarını kapsar.',
    [
      'Kapalı alan çalışması için özel iş izni alınır.',
      'Giriş öncesi gaz ölçümü yapılır (O₂, H₂S, CO, LEL).',
      'Uygun havalandırma sağlanır.',
      'Kapalı alan girişinde gözetmen (buddy) bulundurulur.',
      'Uygun KKD kullanılır: gaz dedektörü, solunum cihazı, emniyet kemeri.',
      'Kurtarma ekipmanları hazır bulundurulur.',
      'Sürekli iletişim (telsiz/ip sinyali) sağlanır.',
      'Acil durumda derhal tahliye yapılır.',
    ],
    [
      'İSG Uzmanı: Gaz ölçümü, iş izni, güvenlik kontrolü',
      'Gözetmen: Giriş kontrolü, sürekli izleme',
      'Kurtarma ekibi: Acil müdahale hazırlığı',
      'Çalışanlar: Prosedüre uyum, iletişim',
    ],
    '6331 sayılı Kanun ve İş Sağlığı ve Güvenliğine İlişkin İşyeri Tehlike Sınıfları Tebliği',
  ),

  prosedur(
    'elektrik-guvenlik',
    'Elektrik Güvenliği Prosedürü',
    'Elektrik tesisatı ve ekipmanlarında güvenli çalışma prosedürü',
    'Elektrikle çalışmalarda iş güvenliği kurallarını ve yetkilendirme sürecini belirlemek.',
    'İşyerindeki tüm elektrik tesisat, pano, makine ve ekipman çalışmalarını kapsar.',
    [
      'Elektrik işlerini yalnızca yetkilendirilmiş (ehliyet belgeli) personel yapar.',
      'Enerjisiz çalışma prensibi (LOTO — Kilitle/Etiketle) uygulanır.',
      'Çalışma öncesi gerilim yokluğu teyit edilir.',
      'Uygun yalıtımlı aletler ve KKD kullanılır.',
      'Topraklama kontrolleri düzenli yapılır.',
      'Kaçak akım rölesi (KAR) tüm devrelerde aktif tutulur.',
      'Pano ve dağıtım kutuları kilitli ve işaretli tutulur.',
    ],
    [
      'Elektrik teknisyeni: Yetkilendirilmiş çalışma',
      'İSG Uzmanı: LOTO kontrolü, güvenlik denetimi',
      'Bakım birimi: Periyodik kontrol ve bakım',
    ],
    'Elektrik Tesislerinde Topraklamalar Yönetmeliği ve 6331 sayılı Kanun',
  ),

  prosedur(
    'ergonomi-prosedur',
    'Ergonomi Prosedürü',
    'İşyeri ergonomi değerlendirme ve iyileştirme prosedürü',
    'Çalışma ortamı ve koşullarının ergonomik açıdan değerlendirilmesi ve kas-iskelet sistemi hastalıklarının önlenmesi.',
    'İşyerindeki tüm çalışma alanları ve faaliyetleri kapsar (ofis, üretim, depo).',
    [
      'Ergonomik risk değerlendirmesi yapılır (REBA, RULA, NIOSH vb.).',
      'Ofis çalışanları için ekran kullanımı düzenlemesi yapılır.',
      'Ağır yük kaldırma/taşıma limitlerini belirleyin (erkek: 25 kg, kadın: 15 kg).',
      'Çalışma istasyonları ergonomik prensiplere göre düzenlenir.',
      'Uzun süreli tek pozisyonda çalışma önlenir (mola/rotasyon).',
      'Çalışanlara ergonomi eğitimi verilir.',
      'Şikayetler ve kas-iskelet yakınmaları takip edilir.',
    ],
    [
      'İSG Uzmanı: Ergonomik risk değerlendirme, düzenleme önerileri',
      'İşyeri Hekimi: Sağlık şikayetleri değerlendirme',
      'Birim amirleri: Düzenlemelerin uygulanması',
    ],
    '6331 sayılı Kanun ve Ekranlı Araçlarla Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik',
  ),

  prosedur(
    'taseron-yonetimi',
    'Taşeron Yönetimi Prosedürü',
    'Taşeron/alt işveren İSG yönetim prosedürü',
    'İşyerinde faaliyet gösteren taşeron firmaların İSG yükümlülüklerinin takibini sağlamak.',
    'İşyerinde çalışan tüm taşeron/alt işveren firmalarını ve personelini kapsar.',
    [
      'Taşeron firma İSG evrakları (tescil, sigorta, risk değerlendirme) kontrol edilir.',
      'Taşeron personeline oryantasyon eğitimi verilir.',
      'Taşeron İSG taahhütnamesi imzalatılır.',
      'Taşeron personelinin KKD kullanımı denetlenir.',
      'Ortak alan risk değerlendirmesi yapılır.',
      'Taşeron kaynaklı kaza/olay durumunda raporlama yapılır.',
      'Periyodik taşeron İSG denetimleri gerçekleştirilir.',
    ],
    [
      'İSG Uzmanı: Evrak kontrolü, oryantasyon, denetim',
      'Satın alma / Proje yönetimi: Sözleşme ve İSG şartları',
      'Taşeron firma: İSG yükümlülüklerini yerine getirme',
    ],
    '6331 sayılı Kanun Madde 22-23 ve Alt İşverenlik Yönetmeliği',
  ),

  prosedur(
    'depolama-prosedur',
    'Depolama Prosedürü',
    'Malzeme depolama ve istifleme güvenliği prosedürü',
    'İşyerinde malzemelerin güvenli depolanması, istiflenmesi ve taşınmasına ilişkin kuralları belirlemek.',
    'İşyerindeki tüm depolama alanları ve istifleme faaliyetlerini kapsar.',
    [
      'Malzemeler uygun raf ve paletlerde depolanır.',
      'İstifleme yüksekliği güvenli sınırları aşmamalıdır.',
      'Ağır malzemeler alt raflara, hafif malzemeler üst raflara yerleştirilir.',
      'Geçiş yolları ve acil çıkışlar açık tutulur (en az 80 cm).',
      'Kimyasal maddeler uyumsuzluk tablosuna göre ayrı depolanır.',
      'Forklift/istif makinesi yalnızca ehliyetli operatör kullanır.',
      'Depo alanı düzenli olarak denetlenir.',
    ],
    [
      'Depo sorumlusu: Günlük düzen ve istifleme kontrolü',
      'İSG Uzmanı: Periyodik denetim ve risk değerlendirme',
      'Forklift operatörü: Güvenli kullanım kurallarına uyum',
    ],
    '6331 sayılı Kanun ve İş Sağlığı ve Güvenliği Yönetmeliği',
  ),

  prosedur(
    'isaret-etiketleme',
    'İşaret ve Etiketleme Prosedürü',
    'İşyeri güvenlik işaret ve etiketleme prosedürü',
    'İşyerinde güvenlik ve sağlık işaretlerinin, uyarı etiketlerinin ve boru renk kodlarının uygulanmasını sağlamak.',
    'İşyerindeki tüm bölgelerde kullanılan güvenlik işaretlerini, uyarı levhalarını ve etiketleri kapsar.',
    [
      'İşyeri güvenlik işaretleri ihtiyaç analizine göre belirlenir.',
      'Yasaklama (kırmızı), uyarı (sarı), zorunluluk (mavi), bilgi (yeşil) işaretleri uygun yerlere asılır.',
      'Kimyasal kaplarda GHS etiketleri bulundurulur.',
      'Boru hatları renk kodlarına göre işaretlenir.',
      'LOTO (Kilitle/Etiketle) etiketleri enerji kaynaklarında kullanılır.',
      'İşaretlerin görünürlüğü ve okunabilirliği periyodik kontrol edilir.',
      'Hasarlı veya solmuş işaretler yenilenir.',
    ],
    [
      'İSG Uzmanı: İhtiyaç belirleme, yerleşim planlaması',
      'Bakım birimi: Montaj ve yenileme',
      'Tüm çalışanlar: İşaretlere uyum',
    ],
    'Güvenlik ve Sağlık İşaretleri Yönetmeliği ve 6331 sayılı Kanun',
  ),

  prosedur(
    'gece-calisma',
    'Gece Çalışma Prosedürü',
    'Gece vardiyası çalışma güvenliği prosedürü',
    'Gece vardiyasında çalışma koşulları ve ek güvenlik tedbirlerini belirlemek.',
    'İşyerinde gece vardiyasında (20:00 – 06:00 arası) çalışan tüm personeli kapsar.',
    [
      'Gece çalışanlarına işe başlamadan önce sağlık kontrolü yapılır.',
      'Çalışma alanlarının yeterli aydınlatması sağlanır.',
      'Gece nöbetçi amiri / sorumlusu belirlenir.',
      'Acil durum iletişim bilgileri güncel tutulur.',
      'Gece çalışanlarının günlük çalışma süresi 7.5 saati aşamaz.',
      'Yalnız çalışma minimuma indirilir; buddy sistemi uygulanır.',
      'Güvenlik personeli ile koordinasyon sağlanır.',
    ],
    [
      'Vardiya amiri: Personel gözetimi ve güvenlik',
      'İSG Uzmanı: Aydınlatma kontrolü, risk değerlendirme',
      'İşyeri Hekimi: Gece çalışanlarının sağlık takibi',
    ],
    '4857 sayılı İş Kanunu Madde 69-76 ve 6331 sayılı Kanun',
  ),

  prosedur(
    'sicak-calisma',
    'Sıcak Çalışma Prosedürü',
    'Kaynak, kesme, lehim gibi sıcak çalışma güvenliği prosedürü',
    'Kaynak, oksijen kesme, lehimleme gibi kıvılcım ve alev oluşturan çalışmalarda yangın ve güvenlik tedbirlerini belirlemek.',
    'İşyerinde açık alev, kıvılcım veya yüksek ısı üreten tüm çalışmaları kapsar.',
    [
      'Sıcak çalışma iş izni alınır.',
      'Çalışma alanındaki yanıcı malzemeler uzaklaştırılır veya örtülür.',
      'Yangın söndürücü hazır bulundurulur.',
      'Çevre alanlar aleve dayanıklı örtülerle korunur.',
      'Uygun KKD kullanılır: kaynak maskesi, deri eldiven, aleve dayanıklı kıyafet.',
      'Çalışma sonrası alan 1 saat izlenir (yangın gözetimi).',
      'Gaz tüpleri dik pozisyonda, bağlı ve güneşten korunaklı tutulur.',
    ],
    [
      'Kaynak operatörü: Güvenli çalışma, KKD kullanımı',
      'İSG Uzmanı: İş izni, risk değerlendirme',
      'Yangın gözetmeni: Çalışma sırasında ve sonrasında izleme',
    ],
    '6331 sayılı Kanun ve Yapı İşlerinde İSG Yönetmeliği',
  ),

  prosedur(
    'gurultu-prosedur',
    'Gürültü Kontrolü Prosedürü',
    'İşyeri gürültü maruziyeti ve kontrol prosedürü',
    'Çalışanların gürültü maruziyetinin ölçülmesi, değerlendirilmesi ve kontrol tedbirlerinin uygulanmasını sağlamak.',
    'Gürültü düzeyi 80 dB(A) üzerinde olan tüm çalışma alanlarını kapsar.',
    [
      'Gürültü ölçümü yapılır ve gürültü haritası çıkarılır.',
      'Maruziyet sınır değerleri: Maruziyet eylem değeri 80 dB(A), üst eylem değeri 85 dB(A), sınır değer 87 dB(A).',
      '85 dB(A) üzerinde işitme koruyucu kullanımı zorunludur.',
      'Mühendislik kontrolleri uygulanır (ses yalıtımı, titreşim sönümleme).',
      'Gürültülü alanlar uyarı işaretleriyle belirtilir.',
      'Maruz kalan çalışanlara yıllık odyometri testi yapılır.',
      'Gürültü ölçümleri periyodik olarak tekrarlanır.',
    ],
    [
      'İSG Uzmanı: Gürültü ölçümü, risk değerlendirme',
      'İşyeri Hekimi: Odyometri testleri, sağlık takibi',
      'Bakım birimi: Mühendislik kontrolleri uygulama',
    ],
    'Çalışanların Gürültü ile İlgili Risklerden Korunmalarına Dair Yönetmelik ve 6331 sayılı Kanun',
  ),

  prosedur(
    'toz-prosedur',
    'Toz Kontrolü Prosedürü',
    'İşyeri toz maruziyeti ve kontrol prosedürü',
    'Çalışanların toza maruziyetinin ölçülmesi, değerlendirilmesi ve kontrol tedbirlerinin uygulanmasını sağlamak.',
    'Toz oluşumu bulunan tüm çalışma alanlarını kapsar (üretim, taşlama, kaynak, depolama vb.).',
    [
      'Toz ölçümü yapılır ve mesleki maruziyet sınır değerleriyle karşılaştırılır.',
      'Toz kaynağında kontrol tedbirleri uygulanır (lokal aspirasyon, kapalı sistem).',
      'Genel havalandırma sistemi yeterli kapasitede çalıştırılır.',
      'Tozlu alanlarda uygun solunum koruyucu (FFP2/FFP3) kullanılır.',
      'Çalışma alanları düzenli temizlenir (basınçlı hava ile temizlik yapılmaz).',
      'Maruz kalan çalışanlara periyodik akciğer fonksiyon testi yapılır.',
      'Toz ölçümleri yılda en az 1 kez tekrarlanır.',
    ],
    [
      'İSG Uzmanı: Toz ölçümü, risk değerlendirme',
      'İşyeri Hekimi: Solunum fonksiyon testleri, sağlık takibi',
      'Bakım birimi: Havalandırma ve aspirasyon sistemi bakımı',
    ],
    'Tozla Mücadele Yönetmeliği ve 6331 sayılı Kanun',
  ),
];

// ============================================================
// GROUP 10 — İŞLETME KONTROL / DENETİM
// ============================================================

export const GROUP10_TEMPLATES: P1Template[] = [
  {
    id: 'is-yeri-denetim',
    groupKey: 'isletme-kontrol',
    title: 'İşyeri İSG Denetim Raporu',
    description: 'Periyodik işyeri İSG denetim raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun', 'ay_yil'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İŞYERİ İSG DENETİM RAPORU'),
        p('{{firma_adi}} — {{ay_yil}}'),
        { type: 'horizontalRule' },
        h(2, '1. DENETİM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Denetim Tarihi', '{{bugun}}'],
          ['Denetçi', '{{uzman_adi}}'],
          ['Denetim Türü', '☐ Planlı  ☐ Habersiz  ☐ Takip'],
          ['Denetlenen Alan(lar)', ''],
        ]),
        h(2, '2. DENETİM BULGULARI'),
        table(
          ['No', 'Alan', 'Bulgu', 'Risk Seviyesi', 'Fotoğraf Ref.'],
          [
            ['1', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
            ['2', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
            ['3', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
            ['4', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
            ['5', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
            ['6', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
          ]
        ),
        h(2, '3. DÜZELTİCİ FAALİYET TALEPLERİ'),
        table(['No', 'Bulgu Ref.', 'İstenen Düzeltme', 'Sorumlu', 'Termin'], [
          ['1', '', '', '', ''],
          ['2', '', '', '', ''],
          ['3', '', '', '', ''],
        ]),
        h(2, '4. GENEL DEĞERLENDİRME'),
        p('Denetim sonucunda toplam ____ bulgu tespit edilmiştir. Bunlardan ____ adedi yüksek, ____ adedi orta, ____ adedi düşük risklidir.'),
        p(''),
        table(['Denetçi', 'Denetlenen Birim Amiri'], [
          ['{{uzman_adi}} — İSG Uzmanı', ''],
          ['Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:'],
        ]),
        p('6331 sayılı Kanun Madde 8 — İSG uzmanının görevleri kapsamında düzenlenmiştir.'),
      ],
    },
  },

  {
    id: 'ic-denetim-raporu',
    groupKey: 'isletme-kontrol',
    title: 'İç Denetim Raporu',
    description: 'İSG yönetim sistemi iç denetim raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG İÇ DENETİM RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. DENETİM KAPSAMI'),
        table(['Bilgi', 'Değer'], [
          ['Denetim Tarihi', '{{bugun}}'],
          ['Denetim Ekibi', '{{uzman_adi}}'],
          ['Denetlenen Süreçler', ''],
          ['Referans Standart / Mevzuat', '6331 sayılı Kanun, ISO 45001'],
        ]),
        h(2, '2. DENETİM SONUÇLARI'),
        table(
          ['No', 'Denetim Konusu', 'Uygun', 'Uygunsuz', 'Gözlem', 'Açıklama'],
          [
            ['1', 'Risk değerlendirme güncelliği', '☐', '☐', '☐', ''],
            ['2', 'Eğitim kayıtları', '☐', '☐', '☐', ''],
            ['3', 'Acil durum planı ve tatbikat', '☐', '☐', '☐', ''],
            ['4', 'KKD kullanımı ve zimmet', '☐', '☐', '☐', ''],
            ['5', 'Kaza/olay kayıtları', '☐', '☐', '☐', ''],
            ['6', 'Sağlık gözetimi kayıtları', '☐', '☐', '☐', ''],
            ['7', 'İş izni uygulaması', '☐', '☐', '☐', ''],
            ['8', 'Yasal bildirimler (SGK, İSGKATİP)', '☐', '☐', '☐', ''],
            ['9', 'Periyodik kontrol ve ölçümler', '☐', '☐', '☐', ''],
            ['10', 'DÖF takibi', '☐', '☐', '☐', ''],
          ]
        ),
        h(2, '3. UYGUNSUZLUKLAR VE DÖF TALEPLERİ'),
        table(['No', 'Uygunsuzluk', 'DÖF No', 'Sorumlu', 'Termin'], [
          ['1', '', '', '', ''],
          ['2', '', '', '', ''],
        ]),
        h(2, '4. SONUÇ'),
        p('İç denetim sonucunda toplam ____ uygunluk, ____ uygunsuzluk ve ____ gözlem tespit edilmiştir.'),
        p(''),
        table(['Baş Denetçi', 'Denetlenen Yönetici'], [
          ['{{uzman_adi}}', ''],
          ['Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:'],
        ]),
      ],
    },
  },

  {
    id: 'kontrol-listesi',
    groupKey: 'isletme-kontrol',
    title: 'İSG Kontrol Listesi',
    description: 'Genel işyeri İSG kontrol/checklist formu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KONTROL LİSTESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        p('Kontrol Tarihi: {{bugun}} — Kontrol Eden: {{uzman_adi}}'),
        p(''),
        h(2, 'A. GENEL ÇALIŞMA ORTAMI'),
        table(['No', 'Kontrol Maddesi', 'Uygun', 'Uygun Değil', 'N/A', 'Not'], [
          ['1', 'Çalışma alanları temiz ve düzenli', '☐', '☐', '☐', ''],
          ['2', 'Geçiş yolları açık ve engelsiz', '☐', '☐', '☐', ''],
          ['3', 'Aydınlatma yeterli', '☐', '☐', '☐', ''],
          ['4', 'Havalandırma uygun', '☐', '☐', '☐', ''],
          ['5', 'Zemin kaygan değil, düzgün', '☐', '☐', '☐', ''],
        ]),
        h(2, 'B. YANGIN GÜVENLİĞİ'),
        table(['No', 'Kontrol Maddesi', 'Uygun', 'Uygun Değil', 'N/A', 'Not'], [
          ['6', 'Yangın söndürücüler yerinde ve kontrollü', '☐', '☐', '☐', ''],
          ['7', 'Acil çıkışlar işaretli ve açık', '☐', '☐', '☐', ''],
          ['8', 'Yangın alarm sistemi çalışıyor', '☐', '☐', '☐', ''],
          ['9', 'Acil aydınlatma çalışıyor', '☐', '☐', '☐', ''],
        ]),
        h(2, 'C. ELEKTRİK GÜVENLİĞİ'),
        table(['No', 'Kontrol Maddesi', 'Uygun', 'Uygun Değil', 'N/A', 'Not'], [
          ['10', 'Elektrik panoları kapalı ve işaretli', '☐', '☐', '☐', ''],
          ['11', 'Kablo ve prizler hasarsız', '☐', '☐', '☐', ''],
          ['12', 'Topraklama mevcut', '☐', '☐', '☐', ''],
        ]),
        h(2, 'D. KKD KULLANIMI'),
        table(['No', 'Kontrol Maddesi', 'Uygun', 'Uygun Değil', 'N/A', 'Not'], [
          ['13', 'Çalışanlar uygun KKD kullanıyor', '☐', '☐', '☐', ''],
          ['14', 'KKD\'ler hasarsız ve temiz', '☐', '☐', '☐', ''],
        ]),
        h(2, 'E. İŞARET VE LEVHALAR'),
        table(['No', 'Kontrol Maddesi', 'Uygun', 'Uygun Değil', 'N/A', 'Not'], [
          ['15', 'Güvenlik işaretleri görünür ve okunabilir', '☐', '☐', '☐', ''],
          ['16', 'Toplanma noktası işareti mevcut', '☐', '☐', '☐', ''],
        ]),
        p(''),
        p('Toplam: ____ Uygun, ____ Uygun Değil, ____ N/A'),
        table(['Kontrol Eden', 'Birim Amiri'], [
          ['{{uzman_adi}} — İSG Uzmanı', ''],
          ['Tarih: {{bugun}}', 'Tarih:'],
          ['İmza:', 'İmza:'],
        ]),
      ],
    },
  },

  {
    id: 'uygunsuzluk-raporu',
    groupKey: 'isletme-kontrol',
    title: 'Uygunsuzluk Raporu',
    description: 'İSG denetimi sonucu uygunsuzluk tespit raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'UYGUNSUZLUK RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, '1. UYGUNSUZLUK BİLGİSİ'),
        table(['Bilgi', 'Değer'], [
          ['Rapor No', ''],
          ['Tespit Tarihi', '{{bugun}}'],
          ['Tespit Eden', '{{uzman_adi}}'],
          ['Tespit Yöntemi', '☐ Denetim  ☐ Gözlem  ☐ Kaza/Olay  ☐ Şikayet'],
          ['Uygunsuzluk Alanı', ''],
          ['Uygunsuzluk Seviyesi', '☐ Majör  ☐ Minör  ☐ Gözlem'],
        ]),
        h(2, '2. UYGUNSUZLUK TANIMI'),
        p('Tespit edilen uygunsuzluk:'),
        p(''),
        p('İlgili mevzuat / standart maddesi:'),
        p(''),
        h(2, '3. KANIT VE FOTOĞRAFLAR'),
        p('[Fotoğraf ve kanıt referansları bu alana eklenecektir.]'),
        h(2, '4. DÜZELTİCİ FAALİYET'),
        table(['Bilgi', 'Değer'], [
          ['İstenen düzeltme', ''],
          ['Sorumlu kişi/birim', ''],
          ['Termin tarihi', ''],
          ['DÖF No (açıldıysa)', ''],
        ]),
        h(2, '5. KAPANIŞ'),
        table(['Bilgi', 'Değer'], [
          ['Düzeltme yapıldı mı', '☐ Evet  ☐ Hayır'],
          ['Doğrulama tarihi', ''],
          ['Doğrulayan', ''],
          ['Kapatma onayı', ''],
        ]),
        p(''),
        table(['Tespit Eden', 'Sorumlu Birim', 'Doğrulayan'], [
          ['{{uzman_adi}}', '', ''],
          ['Tarih: {{bugun}}', 'Tarih:', 'Tarih:'],
          ['İmza:', 'İmza:', 'İmza:'],
        ]),
        p('6331 sayılı Kanun Madde 8 gereğince İSG uzmanı tespit ve önerilerini yazılı olarak bildirmekle yükümlüdür.'),
      ],
    },
  },
];
