// ============================================================
// Group 11: Personel Özlük — 17 şablon
// Group 12: Yıllık Değerlendirme — 2 şablon
// Group 13: Çalışan Temsilcisi — 6 şablon
// Group 14: İyi Uygulama — 3 şablon
// Group 15: Dış Görevlendirme — 1 şablon
// ============================================================

import { h, p, table, bullet } from './document-templates-p1';
import type { P1Template } from './document-templates-p1';

// ============================================================
// GROUP 11 — Personel Özlük
// ============================================================

export const GROUP11_TEMPLATES: P1Template[] = [
  {
    id: 'is-sozlesmesi',
    groupKey: 'personel-ozluk',
    title: 'İş Sözleşmesi',
    description: 'Belirsiz süreli iş sözleşmesi şablonu',
    variables: ['firma_adi', 'firma_adresi', 'firma_sehir', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'BELİRSİZ SÜRELİ İŞ SÖZLEŞMESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'TARAFLAR'),
        table(['Bilgi', 'İşveren', 'İşçi'], [
          ['Unvan / Ad Soyad', '{{firma_adi}}', ''],
          ['Adres', '{{firma_adresi}}, {{firma_sehir}}', ''],
          ['T.C. Kimlik No', '', ''],
          ['Telefon', '', ''],
        ]),
        h(2, 'SÖZLEŞME KONUSU VE ŞARTLARI'),
        bullet([
          'Sözleşme Başlangıç Tarihi: {{bugun}}',
          'Sözleşme Türü: Belirsiz süreli',
          'Görev Tanımı: ........................................',
          'Çalışma Yeri: {{firma_adresi}}, {{firma_sehir}}',
          'Haftalık Çalışma Süresi: 45 saat',
          'Ücret: ........................ TL (brüt/aylık)',
          'Ücret Ödeme Günü: Her ayın son iş günü',
        ]),
        h(2, 'İŞ SAĞLIĞI VE GÜVENLİĞİ'),
        p('İşçi, 6331 sayılı İş Sağlığı ve Güvenliği Kanunu kapsamında verilen İSG eğitimlerine katılmakla, kişisel koruyucu donanımları kullanmakla ve iş güvenliği kurallarına uymakla yükümlüdür.'),
        h(2, 'DENEMESÜRESİ'),
        p('Bu sözleşmede deneme süresi 2 (iki) aydır. Deneme süresi içinde taraflar, bildirim süresine gerek olmaksızın sözleşmeyi feshedebilir.'),
        h(2, 'FESİH KOŞULLARI'),
        p('Sözleşmenin feshi, 4857 sayılı İş Kanunu hükümlerine tabidir. İhbar süreleri kanunda belirtilen sürelere uygun olarak uygulanır.'),
        h(2, 'İMZALAR'),
        table(['', 'İşveren', 'İşçi'], [
          ['Ad Soyad', '{{firma_adi}}', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('4857 sayılı İş Kanunu ve 6331 sayılı İSG Kanunu hükümlerine uygun olarak düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'ek-sozlesme',
    groupKey: 'personel-ozluk',
    title: 'Ek Sözleşme',
    description: 'İş sözleşmesine ek protokol/değişiklik belgesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'EK SÖZLEŞME / DEĞİŞİKLİK PROTOKOLÜ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'TARAFLAR'),
        table(['Bilgi', 'Değer'], [
          ['İşveren', '{{firma_adi}}'],
          ['İşçi Adı Soyadı', ''],
          ['Asıl Sözleşme Tarihi', ''],
          ['Sicil No', ''],
        ]),
        h(2, 'DEĞİŞİKLİK KONUSU'),
        p('Aşağıda belirtilen hususlarda tarafların karşılıklı mutabakatı ile iş sözleşmesinde değişiklik yapılmıştır:'),
        table(['Madde', 'Eski Durum', 'Yeni Durum'], [
          ['1', '', ''],
          ['2', '', ''],
          ['3', '', ''],
        ]),
        h(2, 'YÜRÜRLÜK'),
        p('İşbu ek sözleşme {{bugun}} tarihinde yürürlüğe girer. Burada belirtilmeyen hususlarda asıl iş sözleşmesi hükümleri geçerlidir.'),
        h(2, 'İMZALAR'),
        table(['', 'İşveren', 'İşçi'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('4857 sayılı İş Kanunu Madde 22 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'gizlilik-sozlesme',
    groupKey: 'personel-ozluk',
    title: 'Gizlilik Sözleşmesi',
    description: 'Çalışan gizlilik ve bilgi güvenliği taahhütnamesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'GİZLİLİK SÖZLEŞMESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'TARAFLAR'),
        table(['Bilgi', 'Değer'], [
          ['İşveren', '{{firma_adi}}'],
          ['Çalışan Adı Soyadı', ''],
          ['Departman', ''],
          ['Görevi', ''],
        ]),
        h(2, 'GİZLİLİK KAPSAMI'),
        p('Çalışan, görev süresi boyunca ve iş ilişkisinin sona ermesinden itibaren 2 (iki) yıl süreyle aşağıdaki bilgileri gizli tutmayı taahhüt eder:'),
        bullet([
          'Şirketin ticari sırları, müşteri bilgileri ve fiyatlandırma politikaları',
          'Üretim süreçleri, teknik bilgiler ve know-how',
          'İş sağlığı ve güvenliği risk değerlendirme raporları ve iç denetim sonuçları',
          'Personel bilgileri, maaş ve özlük verileri',
          'Stratejik planlar, yatırım kararları ve mali tablolar',
        ]),
        h(2, 'YÜKÜMLÜLÜKLER'),
        bullet([
          'Gizli bilgileri üçüncü şahıslarla paylaşmamak',
          'Gizli bilgileri yalnızca iş amacıyla kullanmak',
          'İşten ayrılma durumunda tüm belge ve kopyaları iade etmek',
          'İhlal durumunda hukuki ve cezai sorumluluk kabul etmek',
        ]),
        h(2, 'İMZALAR'),
        table(['', 'İşveren', 'Çalışan'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'gorev-tanim-belgesi',
    groupKey: 'personel-ozluk',
    title: 'Görev Tanım Belgesi',
    description: 'Personel görev, yetki ve sorumluluk tanımı',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'GÖREV TANIM BELGESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Departman', ''],
          ['Pozisyon', ''],
          ['Bağlı Olduğu Yönetici', ''],
          ['İşe Başlama Tarihi', ''],
        ]),
        h(2, 'TEMEL GÖREVLER'),
        table(['Sıra', 'Görev Tanımı', 'Sıklık'], [
          ['1', '', ''],
          ['2', '', ''],
          ['3', '', ''],
          ['4', '', ''],
          ['5', '', ''],
        ]),
        h(2, 'İSG SORUMLULUKLARI'),
        bullet([
          'İSG kurallarına ve talimatlarına uymak',
          'Kişisel koruyucu donanımları (KKD) düzgün kullanmak',
          'Tehlikeli durumları derhal bildirmek',
          'İSG eğitimlerine katılmak',
          '6331 sayılı Kanun Madde 19 kapsamındaki çalışan yükümlülüklerini yerine getirmek',
        ]),
        h(2, 'YETKİLERİ'),
        bullet([
          'Görev alanı ile ilgili karar alma yetkisi',
          'Tehlikeli durumda işi durdurma yetkisi (6331 Madde 13)',
        ]),
        h(2, 'ONAY'),
        table(['', 'Çalışan', 'Yönetici', 'İK Birimi'], [
          ['Ad Soyad', '', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'ise-giris-evrak',
    groupKey: 'personel-ozluk',
    title: 'İşe Giriş Evrak Kontrol Listesi',
    description: 'Yeni personel işe giriş evrak tamamlama listesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İŞE GİRİŞ EVRAK KONTROL LİSTESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Departman', ''],
          ['İşe Başlama Tarihi', ''],
        ]),
        h(2, 'EVRAK LİSTESİ'),
        table(['Sıra', 'Evrak', 'Teslim', 'Tarih'], [
          ['1', 'Nüfus cüzdanı fotokopisi', '☐', ''],
          ['2', 'İkametgah belgesi', '☐', ''],
          ['3', 'Adli sicil kaydı', '☐', ''],
          ['4', 'Diploma fotokopisi', '☐', ''],
          ['5', 'Sağlık raporu (işe giriş)', '☐', ''],
          ['6', '4 adet vesikalık fotoğraf', '☐', ''],
          ['7', 'SGK işe giriş bildirgesi', '☐', ''],
          ['8', 'İş sözleşmesi (imzalı)', '☐', ''],
          ['9', 'İSG oryantasyon eğitim belgesi', '☐', ''],
          ['10', 'KKD teslim formu', '☐', ''],
          ['11', 'Gizlilik sözleşmesi', '☐', ''],
          ['12', 'KVKK aydınlatma metni onayı', '☐', ''],
        ]),
        h(2, 'ONAY'),
        table(['', 'İK Sorumlusu'], [
          ['Ad Soyad', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
        p('6331 sayılı İSG Kanunu ve 5510 sayılı SGK Kanunu gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'isten-ayrilma',
    groupKey: 'personel-ozluk',
    title: 'İşten Ayrılma Formu',
    description: 'Personel işten ayrılma / çıkış işlemleri formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İŞTEN AYRILMA FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Departman', ''],
          ['İşe Giriş Tarihi', ''],
          ['Ayrılma Tarihi', ''],
          ['Ayrılma Nedeni', ''],
        ]),
        h(2, 'ÇIKIŞ İŞLEMLERİ KONTROL'),
        table(['İşlem', 'Tamamlandı', 'Sorumlu'], [
          ['İhbar süresi tamamlandı / tazminat hesaplandı', '☐', ''],
          ['Zimmetli malzemeler teslim alındı', '☐', ''],
          ['Şirket kartı / anahtarı iade edildi', '☐', ''],
          ['SGK işten çıkış bildirgesi yapıldı', '☐', ''],
          ['Kıdem/ihbar tazminatı hesaplandı', '☐', ''],
          ['Yıllık izin ücreti hesaplandı', '☐', ''],
          ['İSG dosyası arşive kaldırıldı', '☐', ''],
        ]),
        h(2, 'İMZALAR'),
        table(['', 'Çalışan', 'İK Sorumlusu', 'Birim Yöneticisi'], [
          ['Ad Soyad', '', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', '', ''],
        ]),
        p('4857 sayılı İş Kanunu hükümlerine uygun olarak düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'izin-formu',
    groupKey: 'personel-ozluk',
    title: 'İzin Talep Formu',
    description: 'Yıllık izin, mazeret izni ve diğer izin talepleri',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İZİN TALEP FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Departman', ''],
          ['Talep Tarihi', '{{bugun}}'],
        ]),
        h(2, 'İZİN BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['İzin Türü', '☐ Yıllık  ☐ Mazeret  ☐ Ücretsiz  ☐ Doğum  ☐ Ölüm  ☐ Evlilik'],
          ['Başlangıç Tarihi', ''],
          ['Bitiş Tarihi', ''],
          ['Toplam Gün', ''],
          ['İzin Nedeni', ''],
        ]),
        h(2, 'İZİN DURUMU'),
        table(['Bilgi', 'Değer'], [
          ['Toplam Yıllık İzin Hakkı', ''],
          ['Kullanılan İzin', ''],
          ['Kalan İzin', ''],
        ]),
        h(2, 'ONAY'),
        table(['', 'Çalışan', 'Birim Yöneticisi', 'İK Onay'], [
          ['Ad Soyad', '', '', ''],
          ['Tarih', '{{bugun}}', '', ''],
          ['İmza', '', '', ''],
        ]),
        p('4857 sayılı İş Kanunu Madde 53-60 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'mesai-formu',
    groupKey: 'personel-ozluk',
    title: 'Fazla Mesai Formu',
    description: 'Fazla çalışma onay ve kayıt formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'FAZLA MESAİ ONAY FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÇALIŞAN BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Departman', ''],
        ]),
        h(2, 'MESAİ BİLGİLERİ'),
        table(['Tarih', 'Başlangıç Saati', 'Bitiş Saati', 'Toplam Saat', 'Gerekçe'], [
          ['', '', '', '', ''],
          ['', '', '', '', ''],
          ['', '', '', '', ''],
          ['', '', '', '', ''],
          ['', '', '', '', ''],
        ]),
        h(2, 'FAZLA ÇALIŞMA MUVAFAKATNAMESİ'),
        p('Yukarıda belirtilen tarihlerde fazla çalışma yapmayı kabul ediyorum. Fazla çalışma ücretinin yasal oranlarda ödeneceği tarafıma bildirilmiştir.'),
        h(2, 'ONAY'),
        table(['', 'Çalışan', 'Birim Yöneticisi', 'İK Onay'], [
          ['Ad Soyad', '', '', ''],
          ['Tarih', '{{bugun}}', '', ''],
          ['İmza', '', '', ''],
        ]),
        p('4857 sayılı İş Kanunu Madde 41 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'disiplin-tutanagi',
    groupKey: 'personel-ozluk',
    title: 'Disiplin Tutanağı',
    description: 'Çalışan disiplin ihlali tespit ve uyarı tutanağı',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'DİSİPLİN TUTANAĞI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Departman', ''],
          ['Görevi', ''],
        ]),
        h(2, 'İHLAL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['İhlal Tarihi', ''],
          ['İhlal Yeri', ''],
          ['İhlal Türü', '☐ İSG kuralı ihlali  ☐ Devamsızlık  ☐ Görev ihmali  ☐ Diğer'],
          ['İhlal Açıklaması', ''],
          ['Tanıklar', ''],
        ]),
        h(2, 'UYGULANAN YAPTIRIM'),
        p('☐ Sözlü uyarı  ☐ Yazılı uyarı  ☐ Kınama  ☐ Ücret kesintisi  ☐ İş sözleşmesi feshi'),
        h(2, 'ÇALIŞAN SAVUNMASI'),
        p('4857 sayılı İş Kanunu Madde 19 gereğince çalışanın savunması alınmıştır:'),
        p('...........................................................................................................................'),
        h(2, 'İMZALAR'),
        table(['', 'Çalışan', 'Birim Yöneticisi', 'İK Sorumlusu'], [
          ['Ad Soyad', '', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'performans-degerlendirme',
    groupKey: 'personel-ozluk',
    title: 'Performans Değerlendirme Formu',
    description: 'Dönemsel personel performans değerlendirmesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'PERFORMANS DEĞERLENDİRME FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Departman', ''],
          ['Görevi', ''],
          ['Değerlendirme Dönemi', ''],
        ]),
        h(2, 'DEĞERLENDİRME KRİTERLERİ'),
        table(['Kriter', '1', '2', '3', '4', '5'], [
          ['İş kalitesi', '☐', '☐', '☐', '☐', '☐'],
          ['İş hızı ve verimlilik', '☐', '☐', '☐', '☐', '☐'],
          ['İSG kurallarına uyum', '☐', '☐', '☐', '☐', '☐'],
          ['KKD kullanımı', '☐', '☐', '☐', '☐', '☐'],
          ['Takım çalışması', '☐', '☐', '☐', '☐', '☐'],
          ['İnisiyatif ve sorumluluk', '☐', '☐', '☐', '☐', '☐'],
          ['Devam ve dakiklik', '☐', '☐', '☐', '☐', '☐'],
        ]),
        p('Puanlama: 1=Çok Yetersiz, 2=Yetersiz, 3=Yeterli, 4=İyi, 5=Çok İyi'),
        h(2, 'GENEL DEĞERLENDİRME'),
        p(''),
        h(2, 'İMZALAR'),
        table(['', 'Çalışan', 'Değerlendiren Yönetici'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'terfi-formu',
    groupKey: 'personel-ozluk',
    title: 'Terfi / Nakil Formu',
    description: 'Personel terfi, görev değişikliği veya nakil formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'TERFİ / NAKİL FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Mevcut', 'Yeni'], [
          ['Departman', '', ''],
          ['Pozisyon / Unvan', '', ''],
          ['Ücret', '', ''],
          ['Çalışma Yeri', '', ''],
        ]),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Geçerlilik Tarihi', ''],
          ['İşlem Türü', '☐ Terfi  ☐ Nakil  ☐ Görev Değişikliği'],
        ]),
        h(2, 'İSG GEREKLİLİKLERİ'),
        bullet([
          'Yeni görev için İSG eğitimi verildi: ☐ Evet  ☐ Hayır',
          'Yeni görev risk değerlendirmesi güncellendi: ☐ Evet  ☐ Hayır',
          'Yeni KKD ihtiyacı belirlendi: ☐ Evet  ☐ Hayır',
        ]),
        h(2, 'ONAY'),
        table(['', 'Çalışan', 'Mevcut Yönetici', 'Yeni Yönetici', 'İK'], [
          ['Ad Soyad', '', '', '', ''],
          ['Tarih', '{{bugun}}', '', '', ''],
          ['İmza', '', '', '', ''],
        ]),
        p('4857 sayılı İş Kanunu Madde 22 ve 6331 sayılı İSG Kanunu Madde 17 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'personel-bilgi-formu',
    groupKey: 'personel-ozluk',
    title: 'Personel Bilgi Formu',
    description: 'Çalışan kişisel ve iletişim bilgileri formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'PERSONEL BİLGİ FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'KİŞİSEL BİLGİLER'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['T.C. Kimlik No', ''],
          ['Doğum Tarihi / Yeri', ''],
          ['Medeni Durum', ''],
          ['Kan Grubu', ''],
          ['Askerlik Durumu', ''],
          ['Ehliyet', ''],
        ]),
        h(2, 'İLETİŞİM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adres', ''],
          ['Cep Telefonu', ''],
          ['E-posta', ''],
          ['Acil Durumda Aranacak Kişi', ''],
          ['Acil Durum Telefonu', ''],
        ]),
        h(2, 'EĞİTİM BİLGİLERİ'),
        table(['Okul', 'Bölüm', 'Mezuniyet Yılı'], [
          ['', '', ''],
          ['', '', ''],
        ]),
        h(2, 'BEYAN'),
        p('Yukarıdaki bilgilerin doğruluğunu beyan ederim. Bilgilerimde değişiklik olması halinde İK birimine bildireceğimi taahhüt ederim.'),
        table(['', 'Çalışan'], [
          ['Ad Soyad', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
      ],
    },
  },
  {
    id: 'cv-formu',
    groupKey: 'personel-ozluk',
    title: 'CV / Özgeçmiş Formu',
    description: 'Standart şirket CV formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ÖZGEÇMİŞ FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'KİŞİSEL BİLGİLER'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Doğum Tarihi', ''],
          ['Telefon', ''],
          ['E-posta', ''],
          ['Adres', ''],
        ]),
        h(2, 'EĞİTİM'),
        table(['Yıl', 'Okul', 'Bölüm', 'Derece'], [
          ['', '', '', ''],
          ['', '', '', ''],
        ]),
        h(2, 'İŞ DENEYİMİ'),
        table(['Dönem', 'Firma', 'Pozisyon', 'Ayrılma Nedeni'], [
          ['', '', '', ''],
          ['', '', '', ''],
          ['', '', '', ''],
        ]),
        h(2, 'SERTİFİKALAR VE KURSLAR'),
        table(['Yıl', 'Sertifika / Kurs Adı', 'Kuruluş'], [
          ['', '', ''],
          ['', '', ''],
        ]),
        h(2, 'YABANCI DİL'),
        table(['Dil', 'Seviye'], [
          ['', ''],
        ]),
        p('Tarih: {{bugun}}'),
        p('İmza: ................................'),
      ],
    },
  },
  {
    id: 'referans-formu',
    groupKey: 'personel-ozluk',
    title: 'Referans Kontrol Formu',
    description: 'Aday referans doğrulama formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'REFERANS KONTROL FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ADAY BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Aday Adı Soyadı', ''],
          ['Başvurduğu Pozisyon', ''],
        ]),
        h(2, 'REFERANS BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Referans Adı Soyadı', ''],
          ['Firma / Kurum', ''],
          ['Görevi', ''],
          ['Telefon', ''],
          ['Adayla İlişkisi', ''],
        ]),
        h(2, 'REFERANS DEĞERLENDİRME'),
        table(['Soru', 'Cevap'], [
          ['Adayın çalışma süresi?', ''],
          ['Pozisyonu ve sorumlulukları?', ''],
          ['İSG kurallarına uyumu?', ''],
          ['Güçlü yönleri?', ''],
          ['Gelişim alanları?', ''],
          ['Tekrar çalışır mısınız?', ''],
        ]),
        h(2, 'GÖRÜŞME BİLGİLERİ'),
        table(['', 'Değer'], [
          ['Görüşen İK Yetkilisi', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
      ],
    },
  },
  {
    id: 'bordro-mutabakat',
    groupKey: 'personel-ozluk',
    title: 'Bordro Mutabakat Formu',
    description: 'Aylık bordro mutabakat ve onay belgesi',
    variables: ['firma_adi', 'ay_yil'],
    content: {
      type: 'doc',
      content: [
        h(1, 'BORDRO MUTABAKAT FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'DÖNEM BİLGİSİ'),
        p('Bordro Dönemi: {{ay_yil}}'),
        h(2, 'BORDRO ÖZETİ'),
        table(['Kalem', 'Tutar (TL)'], [
          ['Brüt Ücret', ''],
          ['SGK İşçi Payı', ''],
          ['İşsizlik Sigortası İşçi Payı', ''],
          ['Gelir Vergisi', ''],
          ['Damga Vergisi', ''],
          ['Net Ücret', ''],
          ['Fazla Mesai Ücreti', ''],
          ['AGİ', ''],
          ['Toplam Ödeme', ''],
        ]),
        h(2, 'MUTABAKAT'),
        p('Yukarıda belirtilen bordro bilgilerinin doğruluğunu kontrol ettim ve onaylıyorum.'),
        h(2, 'İMZALAR'),
        table(['', 'Çalışan', 'Muhasebe', 'İK Onay'], [
          ['Ad Soyad', '', '', ''],
          ['Tarih', '', '', ''],
          ['İmza', '', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'zimmet-teslim',
    groupKey: 'personel-ozluk',
    title: 'Zimmet Teslim Formu',
    description: 'Personele teslim edilen malzeme ve ekipman zimmet formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ZİMMET TESLİM FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Departman', ''],
        ]),
        h(2, 'ZİMMET LİSTESİ'),
        table(['Sıra', 'Malzeme / Ekipman', 'Marka / Model', 'Seri No', 'Adet', 'Durumu'], [
          ['1', '', '', '', '', ''],
          ['2', '', '', '', '', ''],
          ['3', '', '', '', '', ''],
          ['4', '', '', '', '', ''],
          ['5', '', '', '', '', ''],
        ]),
        h(2, 'TAAHHÜTNAME'),
        p('Yukarıda belirtilen malzemeleri eksiksiz ve sağlam olarak teslim aldığımı, işten ayrılmam veya talep edilmesi halinde aynı durumda iade edeceğimi, kayıp veya hasar durumunda bedelini ödemeyi taahhüt ederim.'),
        h(2, 'İMZALAR'),
        table(['', 'Teslim Alan (Çalışan)', 'Teslim Eden'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'yetkinlik-matrisi',
    groupKey: 'personel-ozluk',
    title: 'Yetkinlik Matrisi',
    description: 'Personel yetkinlik ve beceri değerlendirme matrisi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'YETKİNLİK MATRİSİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'DEĞERLENDİRME BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Departman / Birim', ''],
          ['Değerlendirme Tarihi', '{{bugun}}'],
          ['Değerlendiren', ''],
        ]),
        h(2, 'YETKİNLİK DEĞERLENDİRME TABLOSU'),
        p('Puanlama: 0=Yok, 1=Başlangıç, 2=Temel, 3=Orta, 4=İleri, 5=Uzman'),
        table(['Çalışan Adı', 'İSG Bilgisi', 'KKD Kullanımı', 'Acil Durum', 'Teknik Beceri', 'İlkyardım', 'Yangın Söndürme'], [
          ['', '', '', '', '', '', ''],
          ['', '', '', '', '', '', ''],
          ['', '', '', '', '', '', ''],
          ['', '', '', '', '', '', ''],
          ['', '', '', '', '', '', ''],
        ]),
        h(2, 'EĞİTİM İHTİYACI'),
        table(['Çalışan', 'Eksik Yetkinlik', 'Planlanan Eğitim', 'Hedef Tarih'], [
          ['', '', '', ''],
          ['', '', '', ''],
          ['', '', '', ''],
        ]),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan', 'Birim Yöneticisi'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('6331 sayılı İSG Kanunu Madde 17 gereğince eğitim planlaması amacıyla düzenlenmiştir.'),
      ],
    },
  },
];

// ============================================================
// GROUP 12 — Yıllık Değerlendirme
// ============================================================

export const GROUP12_TEMPLATES: P1Template[] = [
  {
    id: 'yillik-faaliyet-raporu',
    groupKey: 'yillik-degerlendirme',
    title: 'Yıllık İSG Faaliyet Raporu',
    description: 'Yıllık iş sağlığı ve güvenliği faaliyet değerlendirme raporu',
    variables: ['firma_adi', 'firma_adresi', 'firma_sehir', 'tehlike_sinifi', 'personel_sayisi', 'uzman_adi', 'uzman_sinifi', 'isyeri_hekimi', 'yil'],
    content: {
      type: 'doc',
      content: [
        h(1, 'YILLIK İSG FAALİYET RAPORU'),
        p('{{firma_adi}} — {{yil}} Yılı'),
        { type: 'horizontalRule' },
        h(2, '1. İŞYERİ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['İşyeri Unvanı', '{{firma_adi}}'],
          ['Adres', '{{firma_adresi}}, {{firma_sehir}}'],
          ['Tehlike Sınıfı', '{{tehlike_sinifi}}'],
          ['Çalışan Sayısı', '{{personel_sayisi}}'],
          ['İSG Uzmanı', '{{uzman_adi}} ({{uzman_sinifi}})'],
          ['İşyeri Hekimi', '{{isyeri_hekimi}}'],
        ]),
        h(2, '2. YILLIK İSG FAALİYET ÖZETİ'),
        table(['Faaliyet', 'Planlanan', 'Gerçekleşen', 'Oran'], [
          ['İSG Kurul Toplantısı', '', '', ''],
          ['Risk Değerlendirme Revizyonu', '', '', ''],
          ['İSG Eğitimleri', '', '', ''],
          ['Sağlık Gözetimi (Periyodik Muayene)', '', '', ''],
          ['İç Denetim / Teftiş', '', '', ''],
          ['Acil Durum Tatbikatı', '', '', ''],
          ['Ortam Ölçümleri', '', '', ''],
        ]),
        h(2, '3. İŞ KAZASI VE MESLEK HASTALIĞI İSTATİSTİKLERİ'),
        table(['Gösterge', 'Değer'], [
          ['Toplam İş Kazası Sayısı', ''],
          ['Kayıp Günlü Kaza Sayısı', ''],
          ['Kaza Sıklık Oranı', ''],
          ['Kaza Ağırlık Oranı', ''],
          ['Ramak Kala Olay Sayısı', ''],
          ['Meslek Hastalığı Sayısı', ''],
        ]),
        h(2, '4. SONUÇ VE ÖNERİLER'),
        p(''),
        h(2, 'ONAY'),
        table(['', 'İSG Uzmanı', 'İşyeri Hekimi', 'İşveren Vekili'], [
          ['Ad Soyad', '{{uzman_adi}}', '{{isyeri_hekimi}}', ''],
          ['Tarih', '', '', ''],
          ['İmza', '', '', ''],
        ]),
        p('6331 sayılı İSG Kanunu ve İSG Hizmetleri Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'yillik-calisma-plani',
    groupKey: 'yillik-degerlendirme',
    title: 'Yıllık İSG Çalışma Planı',
    description: 'Yıllık iş sağlığı ve güvenliği çalışma planı',
    variables: ['firma_adi', 'uzman_adi', 'uzman_sinifi', 'isyeri_hekimi', 'yil'],
    content: {
      type: 'doc',
      content: [
        h(1, 'YILLIK İSG ÇALIŞMA PLANI'),
        p('{{firma_adi}} — {{yil}} Yılı'),
        { type: 'horizontalRule' },
        h(2, 'PLAN BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Hazırlayan', '{{uzman_adi}} ({{uzman_sinifi}})'],
          ['İşyeri Hekimi', '{{isyeri_hekimi}}'],
          ['Plan Dönemi', '{{yil}}'],
        ]),
        h(2, 'AYLIK FAALİYET PLANI'),
        table(['Ay', 'İSG Faaliyeti', 'Sorumlu', 'Durum'], [
          ['Ocak', 'Yıllık çalışma planı hazırlama, risk değerlendirme revizyonu', '{{uzman_adi}}', '☐'],
          ['Şubat', 'Acil durum planı güncelleme, acil durum ekibi eğitimi', '{{uzman_adi}}', '☐'],
          ['Mart', 'Periyodik sağlık muayeneleri başlangıcı', '{{isyeri_hekimi}}', '☐'],
          ['Nisan', 'Yangın tatbikatı, yangın söndürme eğitimi', '{{uzman_adi}}', '☐'],
          ['Mayıs', 'İSG haftası etkinlikleri, genel İSG eğitimi', '{{uzman_adi}}', '☐'],
          ['Haziran', 'Ortam ölçümleri (gürültü, toz, aydınlatma)', '{{uzman_adi}}', '☐'],
          ['Temmuz', 'KKD envanter kontrolü ve yenileme', '{{uzman_adi}}', '☐'],
          ['Ağustos', 'Makine/ekipman periyodik kontrolleri', '{{uzman_adi}}', '☐'],
          ['Eylül', 'İlkyardım eğitimi yenileme', '{{isyeri_hekimi}}', '☐'],
          ['Ekim', 'Deprem tatbikatı, tahliye eğitimi', '{{uzman_adi}}', '☐'],
          ['Kasım', 'İç denetim ve uygunsuzluk takibi', '{{uzman_adi}}', '☐'],
          ['Aralık', 'Yıllık değerlendirme raporu hazırlama', '{{uzman_adi}}', '☐'],
        ]),
        h(2, 'ONAY'),
        table(['', 'İSG Uzmanı', 'İşyeri Hekimi', 'İşveren Vekili'], [
          ['Ad Soyad', '{{uzman_adi}}', '{{isyeri_hekimi}}', ''],
          ['Tarih', '', '', ''],
          ['İmza', '', '', ''],
        ]),
        p('6331 sayılı İSG Kanunu Madde 4 ve İSG Hizmetleri Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
];

// ============================================================
// GROUP 13 — Çalışan Temsilcisi
// ============================================================

export const GROUP13_TEMPLATES: P1Template[] = [
  {
    id: 'temsilci-secim-tutanagi',
    groupKey: 'calisan-temsilcisi',
    title: 'Çalışan Temsilcisi Seçim Tutanağı',
    description: 'Çalışan temsilcisi seçimi sonuç tutanağı',
    variables: ['firma_adi', 'personel_sayisi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ÇALIŞAN TEMSİLCİSİ SEÇİM TUTANAĞI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'İŞYERİ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['İşyeri', '{{firma_adi}}'],
          ['Toplam Çalışan Sayısı', '{{personel_sayisi}}'],
          ['Seçim Tarihi', '{{bugun}}'],
        ]),
        h(2, 'SEÇİM SONUÇLARI'),
        table(['Sıra', 'Aday Adı Soyadı', 'Departman', 'Aldığı Oy'], [
          ['1', '', '', ''],
          ['2', '', '', ''],
          ['3', '', '', ''],
        ]),
        h(2, 'SEÇİM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Toplam Oy Kullanan', ''],
          ['Geçerli Oy', ''],
          ['Geçersiz Oy', ''],
          ['Seçilen Temsilci', ''],
          ['Yedek Temsilci', ''],
        ]),
        h(2, 'SEÇİM KURULU'),
        table(['Ad Soyad', 'Görev', 'İmza'], [
          ['', 'Başkan', ''],
          ['', 'Üye', ''],
          ['', 'Üye', ''],
        ]),
        p('6331 sayılı İSG Kanunu Madde 20 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'temsilci-gorev-tanimi',
    groupKey: 'calisan-temsilcisi',
    title: 'Çalışan Temsilcisi Görev Tanımı',
    description: 'Çalışan temsilcisinin hak, görev ve sorumlulukları',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ÇALIŞAN TEMSİLCİSİ GÖREV TANIMI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'TEMSİLCİ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Departman', ''],
          ['Seçilme Tarihi', ''],
          ['Görev Süresi', '2 yıl'],
        ]),
        h(2, 'GÖREV VE SORUMLULUKLARI'),
        bullet([
          'İSG ile ilgili konularda çalışanları temsil etmek',
          'İSG kurul toplantılarına katılmak',
          'Tehlikeli durumları işverene bildirmek',
          'Çalışanların İSG taleplerini ve şikayetlerini yönetime iletmek',
          'İSG denetimlerine eşlik etmek',
          'İSG eğitimlerinin planlanmasına katkıda bulunmak',
        ]),
        h(2, 'HAKLARI'),
        bullet([
          'Temsilcilik görevi nedeniyle dezavantajlı duruma düşürülemez',
          'Görev için gerekli zaman ve imkanlar sağlanır',
          'İSG konularında bilgilendirilme hakkı vardır',
          'İSG kurul toplantılarına tam üye olarak katılır',
        ]),
        h(2, 'ONAY'),
        table(['', 'Temsilci', 'İşveren Vekili'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('6331 sayılı İSG Kanunu Madde 20 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'temsilci-raporu',
    groupKey: 'calisan-temsilcisi',
    title: 'Çalışan Temsilcisi Faaliyet Raporu',
    description: 'Çalışan temsilcisi dönemsel faaliyet raporu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ÇALIŞAN TEMSİLCİSİ FAALİYET RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'RAPOR BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Temsilci Adı Soyadı', ''],
          ['Rapor Dönemi', ''],
          ['Rapor Tarihi', '{{bugun}}'],
        ]),
        h(2, 'DÖNEM FAALİYETLERİ'),
        table(['Tarih', 'Faaliyet', 'Sonuç'], [
          ['', 'İSG kurul toplantısı katılımı', ''],
          ['', 'Çalışan talep/şikayet iletimi', ''],
          ['', 'Saha denetimi', ''],
          ['', '', ''],
        ]),
        h(2, 'TESPİT VE ÖNERİLER'),
        table(['Sıra', 'Tespit', 'Öneri', 'Durum'], [
          ['1', '', '', ''],
          ['2', '', '', ''],
          ['3', '', '', ''],
        ]),
        h(2, 'İMZA'),
        table(['', 'Çalışan Temsilcisi'], [
          ['Ad Soyad', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
      ],
    },
  },
  {
    id: 'temsilci-oneri-formu',
    groupKey: 'calisan-temsilcisi',
    title: 'Çalışan Temsilcisi Öneri Formu',
    description: 'İSG iyileştirme önerisi bildirim formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ÇALIŞAN TEMSİLCİSİ ÖNERİ FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÖNERİ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Temsilci Adı Soyadı', ''],
          ['Öneri Tarihi', '{{bugun}}'],
          ['İlgili Bölüm/Alan', ''],
          ['Öncelik', '☐ Yüksek  ☐ Orta  ☐ Düşük'],
        ]),
        h(2, 'MEVCUT DURUM'),
        p(''),
        h(2, 'ÖNERİ DETAYI'),
        p(''),
        h(2, 'BEKLENEN FAYDA'),
        bullet([
          'İSG açısından: ',
          'Maliyet açısından: ',
          'Verimlilik açısından: ',
        ]),
        h(2, 'İŞVEREN DEĞERLENDİRMESİ'),
        table(['Bilgi', 'Değer'], [
          ['Değerlendirme', '☐ Kabul  ☐ Red  ☐ Değerlendirmede'],
          ['Açıklama', ''],
          ['Termin Tarihi', ''],
        ]),
        table(['', 'Temsilci', 'İşveren Vekili'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'temsilci-egitim-kaydi',
    groupKey: 'calisan-temsilcisi',
    title: 'Çalışan Temsilcisi Eğitim Kaydı',
    description: 'Çalışan temsilcisine verilen İSG eğitim kaydı',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ÇALIŞAN TEMSİLCİSİ EĞİTİM KAYDI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'TEMSİLCİ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Eğitim Tarihi', '{{bugun}}'],
          ['Eğitimci', '{{uzman_adi}}'],
        ]),
        h(2, 'EĞİTİM KONULARI'),
        table(['Sıra', 'Konu', 'Süre', 'Tamamlandı'], [
          ['1', '6331 sayılı İSG Kanunu ve çalışan temsilcisi hakları', '1 saat', '☐'],
          ['2', 'Risk değerlendirme yöntemleri', '1 saat', '☐'],
          ['3', 'İSG kurul işleyişi ve karar mekanizması', '1 saat', '☐'],
          ['4', 'Tehlike ve risk kavramları', '1 saat', '☐'],
          ['5', 'İş kazası ve meslek hastalıkları bildirimi', '1 saat', '☐'],
        ]),
        h(2, 'İMZALAR'),
        table(['', 'Temsilci', 'Eğitimci'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('6331 sayılı İSG Kanunu Madde 20 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'temsilci-atama-yazisi',
    groupKey: 'calisan-temsilcisi',
    title: 'Çalışan Temsilcisi Atama Yazısı',
    description: 'Çalışan temsilcisi resmi atama belgesi',
    variables: ['firma_adi', 'personel_sayisi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ÇALIŞAN TEMSİLCİSİ ATAMA YAZISI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ATAMA BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Atanan Kişi', ''],
          ['T.C. Kimlik No', ''],
          ['Departman', ''],
          ['Görevi', ''],
        ]),
        h(2, 'ATAMA GEREKÇESİ'),
        p('6331 sayılı İş Sağlığı ve Güvenliği Kanunu\'nun 20. maddesi gereğince, işyerimizde çalışan sayısının ({{personel_sayisi}}) ilgili yönetmelik kapsamında olması nedeniyle çalışan temsilcisi atanması/seçilmesi gerekmektedir.'),
        p('Yapılan seçim/atama sonucunda yukarıda bilgileri belirtilen çalışanımız, çalışan temsilcisi olarak görevlendirilmiştir.'),
        h(2, 'GÖREV SÜRESİ'),
        p('Başlangıç: {{bugun}}'),
        p('Bitiş: 2 yıl sonra (veya yeni seçim yapılana kadar)'),
        h(2, 'İMZALAR'),
        table(['', 'İşveren Vekili', 'Çalışan Temsilcisi'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('6331 sayılı İSG Kanunu Madde 20 gereğince düzenlenmiştir.'),
      ],
    },
  },
];

// ============================================================
// GROUP 14 — İyi Uygulama
// ============================================================

export const GROUP14_TEMPLATES: P1Template[] = [
  {
    id: 'iyi-uygulama-raporu',
    groupKey: 'iyi-uygulama',
    title: 'İyi Uygulama Raporu',
    description: 'İSG alanında iyi uygulama ve başarı öyküsü raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İYİ UYGULAMA RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'UYGULAMA BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Uygulama Adı', ''],
          ['Uygulama Alanı', ''],
          ['Başlangıç Tarihi', ''],
          ['Rapor Tarihi', '{{bugun}}'],
          ['Hazırlayan', '{{uzman_adi}}'],
        ]),
        h(2, 'ÖNCEKİ DURUM'),
        p(''),
        h(2, 'YAPILAN İYİLEŞTİRME'),
        p(''),
        h(2, 'ELDE EDİLEN SONUÇLAR'),
        table(['Gösterge', 'Önce', 'Sonra', 'İyileşme'], [
          ['İş kazası sayısı', '', '', ''],
          ['Ramak kala olay sayısı', '', '', ''],
          ['Kayıp iş günü', '', '', ''],
          ['Maliyet (TL)', '', '', ''],
        ]),
        h(2, 'ÖĞRENILEN DERSLER'),
        bullet([
          '',
          '',
          '',
        ]),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan', 'İşveren Vekili'], [
          ['Ad Soyad', '{{uzman_adi}}', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'oneri-odul-sistemi',
    groupKey: 'iyi-uygulama',
    title: 'Öneri ve Ödül Sistemi Formu',
    description: 'Çalışan İSG öneri ve ödüllendirme sistemi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG ÖNERİ VE ÖDÜL SİSTEMİ FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÖNERİ SAHİBİ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Departman', ''],
          ['Öneri Tarihi', '{{bugun}}'],
        ]),
        h(2, 'ÖNERİ DETAYI'),
        table(['Bilgi', 'Değer'], [
          ['Öneri Konusu', ''],
          ['İlgili Alan/Bölüm', ''],
          ['Mevcut Problem', ''],
          ['Önerilen Çözüm', ''],
          ['Beklenen Fayda', ''],
        ]),
        h(2, 'DEĞERLENDİRME KOMİTESİ KARARI'),
        table(['Kriter', 'Puan (1-10)'], [
          ['İSG etkisi', ''],
          ['Uygulanabilirlik', ''],
          ['Maliyet etkinliği', ''],
          ['Yaratıcılık', ''],
          ['TOPLAM', ''],
        ]),
        p('Karar: ☐ Ödül verilsin  ☐ Takdir belgesi  ☐ Değerlendirilmedi'),
        h(2, 'ONAY'),
        table(['', 'Öneri Sahibi', 'Komite Başkanı'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'benchmark-raporu',
    groupKey: 'iyi-uygulama',
    title: 'İSG Kıyaslama (Benchmark) Raporu',
    description: 'Sektörel İSG performans karşılaştırma raporu',
    variables: ['firma_adi', 'sektor', 'uzman_adi', 'bugun', 'yil'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KIYASLAMA (BENCHMARK) RAPORU'),
        p('{{firma_adi}} — {{yil}} Yılı'),
        { type: 'horizontalRule' },
        h(2, 'KIYASLAMA BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Sektör', '{{sektor}}'],
          ['Rapor Dönemi', '{{yil}}'],
          ['Hazırlayan', '{{uzman_adi}}'],
          ['Rapor Tarihi', '{{bugun}}'],
        ]),
        h(2, 'PERFORMANS KARŞILAŞTIRMA'),
        table(['Gösterge', 'Firmamız', 'Sektör Ortalaması', 'En İyi Uygulama'], [
          ['Kaza Sıklık Oranı', '', '', ''],
          ['Kaza Ağırlık Oranı', '', '', ''],
          ['Eğitim Saati/Çalışan', '', '', ''],
          ['Ramak Kala Bildirim Oranı', '', '', ''],
          ['KKD Uyum Oranı', '', '', ''],
          ['İSG Yatırım (TL/Çalışan)', '', '', ''],
        ]),
        h(2, 'GÜÇLÜ YÖNLER'),
        bullet(['', '', '']),
        h(2, 'GELİŞİM ALANLARI'),
        bullet(['', '', '']),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan', 'İşveren Vekili'], [
          ['Ad Soyad', '{{uzman_adi}}', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
];

// ============================================================
// GROUP 15 — Dış Görevlendirme
// ============================================================

export const GROUP15_TEMPLATES: P1Template[] = [
  {
    id: 'dis-gorev-yazisi',
    groupKey: 'dis-gorevlendirme',
    title: 'Dış Görev Yazısı',
    description: 'Personel dış görevlendirme / harcırah belgesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'DIŞ GÖREV YAZISI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'GÖREVLENDİRİLEN PERSONEL'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Departman', ''],
          ['Görevi', ''],
        ]),
        h(2, 'GÖREV BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Görev Yeri', ''],
          ['Görev Konusu', ''],
          ['Başlangıç Tarihi', ''],
          ['Bitiş Tarihi', ''],
          ['Ulaşım Aracı', '☐ Şirket aracı  ☐ Toplu taşıma  ☐ Kişisel araç'],
        ]),
        h(2, 'HARCIRAH BİLGİLERİ'),
        table(['Kalem', 'Tutar (TL)'], [
          ['Yol gideri', ''],
          ['Konaklama', ''],
          ['Yemek / İaşe', ''],
          ['Diğer', ''],
          ['TOPLAM', ''],
        ]),
        h(2, 'İSG UYARILARI'),
        bullet([
          'Görev süresince İSG kurallarına uyulacaktır',
          'Araç kullanımında trafik kurallarına dikkat edilecektir',
          'İş kazası durumunda derhal bildirim yapılacaktır',
          'Kişisel koruyucu donanımlar gerekli durumlarda kullanılacaktır',
        ]),
        h(2, 'ONAY'),
        table(['', 'Görevli Personel', 'Birim Yöneticisi', 'Üst Yönetim'], [
          ['Ad Soyad', '', '', ''],
          ['Tarih', '{{bugun}}', '', ''],
          ['İmza', '', '', ''],
        ]),
      ],
    },
  },
];
