// ============================================================
// Group 1: İş Giriş İSG ve Oryantasyon — 8 şablon
// Group 2: İSG Kurul Kayıtları — 7 şablon (kurul-tutanagi P1'de)
// ============================================================

import type { JSONContent } from '@tiptap/react';
import { h, p, table, bullet } from './document-templates-p1';
import type { P1Template } from './document-templates-p1';

export const GROUP1_TEMPLATES: P1Template[] = [
  {
    id: 'oryantasyon-formu',
    groupKey: 'is-giris-oryantasyon',
    title: 'İSG Oryantasyon Eğitim Formu',
    description: 'Yeni işe başlayan personel için İSG oryantasyon eğitim kaydı',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG ORYANTASYON EĞİTİM FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÇALIŞAN BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['T.C. Kimlik No', ''],
          ['Görevi / Departmanı', ''],
          ['İşe Başlama Tarihi', ''],
          ['Eğitim Tarihi', '{{bugun}}'],
        ]),
        h(2, 'ORYANTASYON EĞİTİM KONULARI'),
        table(['Sıra', 'Konu', 'Süre', 'Eğitimci', 'Tamamlandı'], [
          ['1', 'İSG mevzuatı ve çalışan hakları', '30 dk', '{{uzman_adi}}', '☐'],
          ['2', 'İşyeri tehlike ve riskleri', '30 dk', '{{uzman_adi}}', '☐'],
          ['3', 'Kişisel koruyucu donanım (KKD) kullanımı', '20 dk', '{{uzman_adi}}', '☐'],
          ['4', 'Acil durum prosedürleri ve tahliye planı', '20 dk', '{{uzman_adi}}', '☐'],
          ['5', 'İlkyardım bilgileri ve ilkyardımcılar', '15 dk', '{{uzman_adi}}', '☐'],
          ['6', 'Yangın güvenliği ve söndürme ekipmanları', '15 dk', '{{uzman_adi}}', '☐'],
          ['7', 'İş kazası ve ramak kala bildirim süreci', '15 dk', '{{uzman_adi}}', '☐'],
          ['8', 'Çalışma ortamı kuralları ve yasaklar', '15 dk', '{{uzman_adi}}', '☐'],
        ]),
        h(2, 'ÇALIŞAN BEYANI'),
        p('Yukarıda belirtilen İSG oryantasyon eğitimini aldığımı, eğitim konularını anladığımı ve kurallara uyacağımı beyan ederim.'),
        p(''),
        table(['', 'Çalışan', 'Eğitimci'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p(''),
        p('6331 sayılı İSG Kanunu Madde 17 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'ise-giris-eslestirme',
    groupKey: 'is-giris-oryantasyon',
    title: 'İşe Giriş Eşleştirme Formu',
    description: 'Yeni personelin deneyimli çalışanla eşleştirilmesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İŞE GİRİŞ EŞLEŞTİRME FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'YENİ PERSONEL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Departman / Birim', ''],
          ['Görevi', ''],
          ['İşe Başlama Tarihi', ''],
        ]),
        h(2, 'EŞLEŞTİRİLEN USTA / REHBERLİK YAPACAK KİŞİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Departman / Birim', ''],
          ['Deneyim Süresi', ''],
          ['Eşleştirme Süresi', '30 gün'],
        ]),
        h(2, 'EŞLEŞTİRME SÜRECİ TAKİP'),
        table(['Hafta', 'Tarih', 'Değerlendirme', 'Notlar'], [
          ['1. Hafta', '', '', ''],
          ['2. Hafta', '', '', ''],
          ['3. Hafta', '', '', ''],
          ['4. Hafta', '', '', ''],
        ]),
        p(''),
        table(['', 'Yeni Personel', 'Rehber', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '', ''],
          ['İmza', '', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'ise-giris-saglik',
    groupKey: 'is-giris-oryantasyon',
    title: 'İşe Giriş Sağlık Raporu Takip',
    description: 'Personel sağlık raporu ve muayene takip formu',
    variables: ['firma_adi', 'isyeri_hekimi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İŞE GİRİŞ SAĞLIK RAPORU TAKİP FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        table(['Sıra', 'Ad Soyad', 'Departman', 'İşe Giriş Tarihi', 'Sağlık Raporu Tarihi', 'Rapor Sonucu', 'Periyodik Muayene Tarihi'], [
          ['1', '', '', '', '', '☐ Uygun ☐ Uygun Değil', ''],
          ['2', '', '', '', '', '☐ Uygun ☐ Uygun Değil', ''],
          ['3', '', '', '', '', '☐ Uygun ☐ Uygun Değil', ''],
          ['4', '', '', '', '', '☐ Uygun ☐ Uygun Değil', ''],
          ['5', '', '', '', '', '☐ Uygun ☐ Uygun Değil', ''],
        ]),
        p(''),
        p('İşyeri Hekimi: {{isyeri_hekimi}}'),
        p('Tarih: {{bugun}}'),
        p('İmza: ________________'),
      ],
    },
  },
  {
    id: 'ise-giris-taahhut',
    groupKey: 'is-giris-oryantasyon',
    title: 'İSG Taahhütnamesi',
    description: 'Çalışanın İSG kurallarına uyacağını taahhüt ettiği belge',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İŞ SAĞLIĞI VE GÜVENLİĞİ TAAHHÜTNAMESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        p('6331 sayılı İş Sağlığı ve Güvenliği Kanunu ve ilgili yönetmelikler çerçevesinde aşağıdaki hususları kabul ve taahhüt ederim:'),
        p(''),
        bullet([
          'İşyerinde uygulanan İSG kurallarına ve talimatlarına uyacağım.',
          'Verilen kişisel koruyucu donanımları (KKD) düzgün kullanacağım.',
          'İş kazası, ramak kala olayı veya tehlikeli durumları derhal bildireceğim.',
          'Acil durum prosedürlerine ve tahliye planlarına uyacağım.',
          'İSG eğitimlerine düzenli katılacağım.',
          'Alkol, uyuşturucu veya keyif verici madde kullanmadan işe geleceğim.',
          'İş ekipmanlarını amacına uygun ve güvenli kullanacağım.',
          'Çalışma arkadaşlarımın güvenliğini tehlikeye atacak davranışlardan kaçınacağım.',
          'Sağlık muayenelerine zamanında katılacağım.',
          'Bu kurallara uymamamın disiplin işlemine tabi olacağını kabul ediyorum.',
        ]),
        p(''),
        h(2, 'ÇALIŞAN BİLGİLERİ VE ONAY'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['T.C. Kimlik No', ''],
          ['Departman', ''],
          ['Görevi', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
      ],
    },
  },
  {
    id: 'kkd-zimmet',
    groupKey: 'is-giris-oryantasyon',
    title: 'KKD Zimmet Formu',
    description: 'Kişisel koruyucu donanım teslim ve zimmet kaydı',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KİŞİSEL KORUYUCU DONANIM ZİMMET FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÇALIŞAN BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Departman', ''],
          ['Görevi', ''],
        ]),
        h(2, 'TESLİM EDİLEN KKD LİSTESİ'),
        table(['Sıra', 'KKD Türü', 'Marka/Model', 'Adet', 'Teslim Tarihi', 'Teslim Alan İmza'], [
          ['1', 'Baret', '', '1', '{{bugun}}', ''],
          ['2', 'Koruyucu Gözlük', '', '1', '{{bugun}}', ''],
          ['3', 'İş Eldiveni', '', '1', '{{bugun}}', ''],
          ['4', 'İş Ayakkabısı', '', '1', '{{bugun}}', ''],
          ['5', 'Reflektif Yelek', '', '1', '{{bugun}}', ''],
          ['6', 'Kulak Tıkacı/Kulaklık', '', '1', '{{bugun}}', ''],
          ['7', 'Toz Maskesi', '', '5', '{{bugun}}', ''],
        ]),
        p(''),
        p('Yukarıda belirtilen KKD\'leri teslim aldığımı, amacına uygun kullanacağımı, hasar veya kayıp durumunda bildireceğimi taahhüt ederim.'),
        p(''),
        table(['', 'Teslim Alan', 'Teslim Eden'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'isg-bilgilendirme',
    groupKey: 'is-giris-oryantasyon',
    title: 'İSG Bilgilendirme Tutanağı',
    description: '6331 Madde 16 kapsamında çalışan bilgilendirme kaydı',
    variables: ['firma_adi', 'uzman_adi', 'tehlike_sinifi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG BİLGİLENDİRME TUTANAĞI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        p('6331 sayılı İSG Kanunu Madde 16 gereğince, çalışanlar aşağıdaki konularda bilgilendirilmiştir:'),
        h(2, 'BİLGİLENDİRME KONULARI'),
        bullet([
          'İşyerinin tehlike sınıfı: {{tehlike_sinifi}}',
          'İşyerindeki mevcut riskler ve alınan önlemler',
          'Yasal hak ve sorumluluklar (6331 sayılı Kanun)',
          'İlkyardım, yangın ve acil durum prosedürleri',
          'Çalışan temsilcileri ve görevleri',
          'İSG kurulu yapısı ve işleyişi',
          'İş kazası ve meslek hastalığı bildirim süreçleri',
          'KKD kullanımı ve bakımı',
        ]),
        h(2, 'BİLGİLENDİRİLEN ÇALIŞANLAR'),
        table(['Sıra', 'Ad Soyad', 'Departman', 'İmza'], [
          ['1', '', '', ''],
          ['2', '', '', ''],
          ['3', '', '', ''],
          ['4', '', '', ''],
          ['5', '', '', ''],
        ]),
        p(''),
        p('Bilgilendiren: {{uzman_adi}} — İSG Uzmanı'),
        p('Tarih: {{bugun}}'),
        p('İmza: ________________'),
      ],
    },
  },
  {
    id: 'gorev-tanimlari',
    groupKey: 'is-giris-oryantasyon',
    title: 'Görev Tanımları',
    description: 'Çalışan pozisyon bazlı görev tanımı belgesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'GÖREV TANIM BELGESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        table(['Bilgi', 'Değer'], [
          ['Pozisyon Adı', ''],
          ['Departman', ''],
          ['Bağlı Olduğu Yönetici', ''],
          ['Hazırlanma Tarihi', '{{bugun}}'],
          ['Revizyon No', '01'],
        ]),
        h(2, 'GÖREV AMACI'),
        p(''),
        h(2, 'TEMEL GÖREV VE SORUMLULUKLAR'),
        bullet([
          '',
          '',
          '',
        ]),
        h(2, 'İSG SORUMLULUKLARI'),
        bullet([
          'İSG kurallarına ve talimatlarına uymak',
          'KKD\'leri düzgün kullanmak',
          'Tehlikeli durumları bildirmek',
          'İSG eğitimlerine katılmak',
        ]),
        h(2, 'YETKİNLİK GEREKSİNİMLERİ'),
        table(['Yetkinlik', 'Açıklama'], [
          ['Eğitim', ''],
          ['Deneyim', ''],
          ['Sertifika', ''],
          ['Teknik Bilgi', ''],
        ]),
        p(''),
        table(['', 'Çalışan', 'Yönetici'], [
          ['Ad Soyad', '', ''],
          ['İmza', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
        ]),
      ],
    },
  },
  {
    id: 'oryantasyon-kontrol',
    groupKey: 'is-giris-oryantasyon',
    title: 'Oryantasyon Kontrol Listesi',
    description: 'Yeni personel oryantasyon sürecinin takip listesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ORYANTASYON KONTROL LİSTESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        table(['Bilgi', 'Değer'], [
          ['Personel Adı', ''],
          ['Departman', ''],
          ['İşe Başlama Tarihi', ''],
        ]),
        h(2, 'KONTROL MADDELERI'),
        table(['Sıra', 'Konu', 'Tamamlandı', 'Tarih', 'Sorumlu'], [
          ['1', 'İşe giriş sağlık raporu alındı', '☐', '', ''],
          ['2', 'İSG oryantasyon eğitimi verildi', '☐', '', ''],
          ['3', 'KKD teslim edildi ve zimmet tutanağı imzalandı', '☐', '', ''],
          ['4', 'İSG taahhütnamesi imzalandı', '☐', '', ''],
          ['5', 'Görev tanımı tebliğ edildi', '☐', '', ''],
          ['6', 'Acil durum prosedürleri anlatıldı', '☐', '', ''],
          ['7', 'Çalışma alanı tanıtıldı', '☐', '', ''],
          ['8', 'İlkyardım noktaları gösterildi', '☐', '', ''],
          ['9', 'Yangın söndürücülerin yerleri gösterildi', '☐', '', ''],
          ['10', 'Toplanma alanı gösterildi', '☐', '', ''],
          ['11', 'Usta/rehber eşleştirmesi yapıldı', '☐', '', ''],
          ['12', 'SGK girişi yapıldı', '☐', '', ''],
        ]),
        p(''),
        p('Oryantasyon Sorumlusu İmza: ________________'),
        p('Tarih: {{bugun}}'),
      ],
    },
  },
];

// Group 2: İSG Kurul Kayıtları (kurul-tutanagi zaten P1'de)
export const GROUP2_TEMPLATES: P1Template[] = [
  {
    id: 'kurul-uye-listesi',
    groupKey: 'isg-kurul-kayitlari',
    title: 'Kurul Üye Listesi',
    description: 'İSG Kurulu üye bilgileri ve görev dağılımı',
    variables: ['firma_adi', 'uzman_adi', 'isyeri_hekimi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KURULU ÜYE LİSTESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        p('6331 sayılı İSG Kanunu Madde 22 ve İSG Kurulları Hakkında Yönetmelik gereğince oluşturulan kurul üyeleri:'),
        table(['Sıra', 'Ad Soyad', 'Görevi', 'Kurul Rolü', 'İmza'], [
          ['1', '', 'İşveren/İşveren Vekili', 'Kurul Başkanı', ''],
          ['2', '{{uzman_adi}}', 'İSG Uzmanı', 'Kurul Sekreteri', ''],
          ['3', '{{isyeri_hekimi}}', 'İşyeri Hekimi', 'Üye', ''],
          ['4', '', 'İnsan Kaynakları', 'Üye', ''],
          ['5', '', 'Çalışan Temsilcisi', 'Üye', ''],
          ['6', '', 'Formen/Ustabaşı', 'Üye', ''],
        ]),
        p(''),
        p('Yürürlük Tarihi: {{bugun}}'),
      ],
    },
  },
  {
    id: 'kurul-karar-takip',
    groupKey: 'isg-kurul-kayitlari',
    title: 'Kurul Karar Takip Formu',
    description: 'İSG kurulu kararlarının takip ve izleme formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KURULU KARAR TAKİP FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        table(['Karar No', 'Toplantı Tarihi', 'Karar Konusu', 'Sorumlu', 'Termin', 'Durum'], [
          ['', '', '', '', '', '☐ Açık ☐ Kapandı'],
          ['', '', '', '', '', '☐ Açık ☐ Kapandı'],
          ['', '', '', '', '', '☐ Açık ☐ Kapandı'],
          ['', '', '', '', '', '☐ Açık ☐ Kapandı'],
          ['', '', '', '', '', '☐ Açık ☐ Kapandı'],
        ]),
        p(''),
        p('Takip Eden: İSG Uzmanı'),
        p('Son Güncelleme: {{bugun}}'),
      ],
    },
  },
  {
    id: 'kurul-gundem',
    groupKey: 'isg-kurul-kayitlari',
    title: 'Kurul Gündem Belgesi',
    description: 'İSG kurulu toplantı gündemi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KURULU TOPLANTI GÜNDEMİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        table(['Bilgi', 'Değer'], [
          ['Toplantı Tarihi', ''],
          ['Toplantı Saati', ''],
          ['Toplantı Yeri', ''],
        ]),
        h(2, 'GÜNDEM MADDELERİ'),
        bullet([
          'Açılış ve yoklama',
          'Bir önceki toplantı kararlarının değerlendirilmesi',
          'İş kazası/ramak kala olaylarının değerlendirilmesi',
          'Risk değerlendirmesi güncellemeleri',
          'Eğitim faaliyetlerinin değerlendirilmesi',
          'Çalışan öneri ve şikayetleri',
          'Periyodik kontrol sonuçları',
          'Dilek ve temenniler',
          'Kapanış',
        ]),
        p(''),
        p('Hazırlayan: İSG Uzmanı'),
        p('Tarih: {{bugun}}'),
      ],
    },
  },
  {
    id: 'kurul-yillik-plan',
    groupKey: 'isg-kurul-kayitlari',
    title: 'Kurul Yıllık Toplantı Planı',
    description: 'İSG kurulu yıllık toplantı takvimi',
    variables: ['firma_adi', 'yil'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KURULU YILLIK TOPLANTI PLANI'),
        p('{{firma_adi}} — {{yil}}'),
        { type: 'horizontalRule' },
        p('İSG Kurulları Hakkında Yönetmelik gereğince en az ayda bir kez toplanılması planlanmıştır.'),
        table(['Ay', 'Planlanan Tarih', 'Özel Gündem', 'Gerçekleşen Tarih', 'Durum'], [
          ['Ocak', '', 'Yıllık çalışma planı', '', ''],
          ['Şubat', '', '', '', ''],
          ['Mart', '', '', '', ''],
          ['Nisan', '', '28 Nisan İSG Haftası', '', ''],
          ['Mayıs', '', '', '', ''],
          ['Haziran', '', 'Yarıyıl değerlendirme', '', ''],
          ['Temmuz', '', '', '', ''],
          ['Ağustos', '', '', '', ''],
          ['Eylül', '', 'Yeni dönem planlaması', '', ''],
          ['Ekim', '', '', '', ''],
          ['Kasım', '', '', '', ''],
          ['Aralık', '', 'Yıl sonu değerlendirme', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'kurul-katilim',
    groupKey: 'isg-kurul-kayitlari',
    title: 'Kurul Katılım Çizelgesi',
    description: 'İSG kurulu toplantı katılım takip çizelgesi',
    variables: ['firma_adi', 'yil'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KURULU KATILIM ÇİZELGESİ'),
        p('{{firma_adi}} — {{yil}}'),
        { type: 'horizontalRule' },
        table(['Üye Adı', 'Rolü', 'Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'], [
          ['', 'Başkan', '', '', '', '', '', '', '', '', '', '', '', ''],
          ['', 'Sekreter', '', '', '', '', '', '', '', '', '', '', '', ''],
          ['', 'Üye', '', '', '', '', '', '', '', '', '', '', '', ''],
          ['', 'Üye', '', '', '', '', '', '', '', '', '', '', '', ''],
          ['', 'Üye', '', '', '', '', '', '', '', '', '', '', '', ''],
        ]),
        p('✓ = Katıldı, X = Katılmadı, M = Mazeretli'),
      ],
    },
  },
  {
    id: 'kurul-ozel-toplanti',
    groupKey: 'isg-kurul-kayitlari',
    title: 'Özel Toplantı Tutanağı',
    description: 'Olağanüstü durumlarda yapılan özel İSG kurulu toplantısı',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KURULU ÖZEL TOPLANTI TUTANAĞI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        table(['Bilgi', 'Değer'], [
          ['Toplantı Tarihi', '{{bugun}}'],
          ['Toplantı Nedeni', '☐ İş Kazası ☐ Meslek Hastalığı ☐ Tehlikeli Durum ☐ Diğer'],
          ['Toplantıyı Talep Eden', ''],
        ]),
        h(2, 'OLAY ÖZETİ'),
        p(''),
        h(2, 'DEĞERLENDİRME VE ALINACAK ÖNLEMLER'),
        table(['Sıra', 'Önlem', 'Sorumlu', 'Termin'], [
          ['1', '', '', ''],
          ['2', '', '', ''],
          ['3', '', '', ''],
        ]),
        h(2, 'KATILIMCILAR'),
        table(['Ad Soyad', 'Görevi', 'İmza'], [
          ['', '', ''],
          ['', '', ''],
          ['', '', ''],
          ['{{uzman_adi}}', 'İSG Uzmanı', ''],
        ]),
      ],
    },
  },
  {
    id: 'kurul-secim-tutanagi',
    groupKey: 'isg-kurul-kayitlari',
    title: 'Kurul Seçim Tutanağı',
    description: 'İSG kurulu çalışan temsilcisi seçim tutanağı',
    variables: ['firma_adi', 'personel_sayisi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İSG KURULU ÇALIŞAN TEMSİLCİSİ SEÇİM TUTANAĞI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        table(['Bilgi', 'Değer'], [
          ['Seçim Tarihi', '{{bugun}}'],
          ['Toplam Çalışan Sayısı', '{{personel_sayisi}}'],
          ['Oy Kullanan Sayısı', ''],
          ['Seçim Yöntemi', '☐ Gizli Oy ☐ Açık Oylama'],
        ]),
        h(2, 'ADAYLAR VE SONUÇLAR'),
        table(['Sıra', 'Aday Adı', 'Departman', 'Aldığı Oy', 'Sonuç'], [
          ['1', '', '', '', '☐ Seçildi ☐ Yedek'],
          ['2', '', '', '', '☐ Seçildi ☐ Yedek'],
          ['3', '', '', '', '☐ Seçildi ☐ Yedek'],
        ]),
        h(2, 'SEÇİM KURULU'),
        table(['Ad Soyad', 'Görevi', 'İmza'], [
          ['', 'Kurul Başkanı', ''],
          ['', 'Katip Üye', ''],
          ['', 'Katip Üye', ''],
        ]),
        p(''),
        p('İSG Kurulları Hakkında Yönetmelik Madde 5 gereğince düzenlenmiştir.'),
      ],
    },
  },
];
