// ============================================================
// Group 16: Araç/Makine — 5 şablon
// Group 17: Periyodik Kontrol — 14 şablon
// Group 18: Diğer Kayıtlar — 12 şablon
// Group 19: Yangın/Kimyasal — 7 şablon
// Group 20: İlkyardım — 3 şablon
// ============================================================

import { h, p, table, bullet } from './document-templates-p1';
import type { P1Template } from './document-templates-p1';

// ============================================================
// GROUP 16 — Araç / Makine
// ============================================================

export const GROUP16_TEMPLATES: P1Template[] = [
  {
    id: 'arac-kontrol-listesi',
    groupKey: 'arac-makine',
    title: 'Araç Günlük Kontrol Listesi',
    description: 'Şirket araçları günlük kullanım öncesi kontrol formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ARAÇ GÜNLÜK KONTROL LİSTESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ARAÇ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Plaka', ''],
          ['Marka / Model', ''],
          ['Sürücü Adı Soyadı', ''],
          ['Kontrol Tarihi', '{{bugun}}'],
          ['Kilometre', ''],
        ]),
        h(2, 'KONTROL NOKTALARI'),
        table(['Sıra', 'Kontrol Kalemi', 'Uygun', 'Uygun Değil', 'Açıklama'], [
          ['1', 'Motor yağı seviyesi', '☐', '☐', ''],
          ['2', 'Antifriz seviyesi', '☐', '☐', ''],
          ['3', 'Fren hidroliği', '☐', '☐', ''],
          ['4', 'Lastik durumu ve basınçları', '☐', '☐', ''],
          ['5', 'Farlar ve sinyal lambaları', '☐', '☐', ''],
          ['6', 'Silecekler ve cam suyu', '☐', '☐', ''],
          ['7', 'Aynalar', '☐', '☐', ''],
          ['8', 'Emniyet kemerleri', '☐', '☐', ''],
          ['9', 'Yangın tüpü', '☐', '☐', ''],
          ['10', 'İlkyardım çantası', '☐', '☐', ''],
          ['11', 'Reflektör / yansıtıcı yelek', '☐', '☐', ''],
          ['12', 'Genel temizlik ve düzen', '☐', '☐', ''],
        ]),
        h(2, 'SONUÇ'),
        p('☐ Araç kullanıma uygundur  ☐ Araç kullanıma uygun değildir'),
        table(['', 'Sürücü'], [
          ['Ad Soyad', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
      ],
    },
  },
  {
    id: 'makine-bakim-formu',
    groupKey: 'arac-makine',
    title: 'Makine Bakım Formu',
    description: 'Makine ve ekipman periyodik bakım kayıt formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'MAKİNE BAKIM FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'MAKİNE BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Makine Adı', ''],
          ['Marka / Model', ''],
          ['Seri No / Envanter No', ''],
          ['Bulunduğu Bölüm', ''],
          ['Bakım Tarihi', '{{bugun}}'],
          ['Bakım Türü', '☐ Periyodik  ☐ Arıza  ☐ Koruyucu'],
        ]),
        h(2, 'BAKIM KONTROL LİSTESİ'),
        table(['Sıra', 'Kontrol / Bakım İşlemi', 'Yapıldı', 'Açıklama'], [
          ['1', 'Genel temizlik', '☐', ''],
          ['2', 'Yağlama ve gresaj', '☐', ''],
          ['3', 'Kayış ve bağlantı kontrolü', '☐', ''],
          ['4', 'Elektrik bağlantıları', '☐', ''],
          ['5', 'Güvenlik tertibatları kontrolü', '☐', ''],
          ['6', 'Titreşim ve ses kontrolü', '☐', ''],
          ['7', 'Sızıntı kontrolü', '☐', ''],
          ['8', 'Çalışma testi', '☐', ''],
        ]),
        h(2, 'KULLANILAN MALZEME'),
        table(['Malzeme', 'Miktar', 'Birim'], [
          ['', '', ''],
          ['', '', ''],
        ]),
        h(2, 'SONUÇ'),
        p('☐ Makine çalışmaya uygundur  ☐ Onarım gereklidir  ☐ Kullanım dışı bırakılmalıdır'),
        p('Sonraki Bakım Tarihi: .......................'),
        table(['', 'Bakım Teknisyeni', 'Bölüm Sorumlusu'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'forklift-kontrol',
    groupKey: 'arac-makine',
    title: 'Forklift Günlük Kontrol Formu',
    description: 'Forklift kullanım öncesi günlük kontrol listesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'FORKLİFT GÜNLÜK KONTROL FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'FORKLİFT BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Forklift No / Plaka', ''],
          ['Marka / Model', ''],
          ['Kapasite (kg)', ''],
          ['Operatör Adı Soyadı', ''],
          ['Operatör Belgesi No', ''],
          ['Kontrol Tarihi', '{{bugun}}'],
        ]),
        h(2, 'KONTROL NOKTALARI'),
        table(['Sıra', 'Kontrol Kalemi', 'Uygun', 'Uygun Değil'], [
          ['1', 'Çatal (fork) durumu ve bağlantıları', '☐', '☐'],
          ['2', 'Hidrolik sistem ve sızıntı kontrolü', '☐', '☐'],
          ['3', 'Fren sistemi', '☐', '☐'],
          ['4', 'Direksiyon sistemi', '☐', '☐'],
          ['5', 'Lastikler', '☐', '☐'],
          ['6', 'Korna ve ikaz lambası', '☐', '☐'],
          ['7', 'Aydınlatma sistemi', '☐', '☐'],
          ['8', 'Emniyet kemeri', '☐', '☐'],
          ['9', 'Koruma kafesi (ROPS/FOPS)', '☐', '☐'],
          ['10', 'Yük zinciri ve bağlantıları', '☐', '☐'],
          ['11', 'Akü / yakıt durumu', '☐', '☐'],
          ['12', 'Yangın tüpü', '☐', '☐'],
        ]),
        h(2, 'SONUÇ'),
        p('☐ Forklift kullanıma uygundur  ☐ Kullanıma uygun değildir'),
        table(['', 'Operatör', 'Bölüm Sorumlusu'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'arac-zimmet',
    groupKey: 'arac-makine',
    title: 'Araç Zimmet Tutanağı',
    description: 'Şirket aracı teslim ve zimmet tutanağı',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ARAÇ ZİMMET TUTANAĞI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ARAÇ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Plaka', ''],
          ['Marka / Model / Yıl', ''],
          ['Renk', ''],
          ['Kilometre', ''],
          ['Yakıt Durumu', ''],
        ]),
        h(2, 'TESLİM ALAN BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Adı Soyadı', ''],
          ['Sicil No', ''],
          ['Ehliyet Sınıfı / No', ''],
          ['Departman', ''],
        ]),
        h(2, 'ARAÇ İLE TESLİM EDİLEN MALZEMELER'),
        table(['Malzeme', 'Var', 'Yok', 'Açıklama'], [
          ['Yedek lastik', '☐', '☐', ''],
          ['Kriko', '☐', '☐', ''],
          ['Yangın tüpü', '☐', '☐', ''],
          ['İlkyardım çantası', '☐', '☐', ''],
          ['Reflektör', '☐', '☐', ''],
          ['Araç ruhsatı', '☐', '☐', ''],
          ['Sigorta poliçesi', '☐', '☐', ''],
        ]),
        h(2, 'TAAHHÜTNAME'),
        p('Yukarıda bilgileri verilen aracı eksiksiz teslim aldığımı, trafik kurallarına ve şirket araç kullanım prosedürüne uyacağımı, hasarda derhal bildirim yapacağımı taahhüt ederim.'),
        table(['', 'Teslim Alan', 'Teslim Eden'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'makine-envanter',
    groupKey: 'arac-makine',
    title: 'Makine ve Ekipman Envanteri',
    description: 'İşyeri makine ve ekipman envanter listesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'MAKİNE VE EKİPMAN ENVANTERİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ENVANTER BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Düzenleme Tarihi', '{{bugun}}'],
          ['Düzenleyen', ''],
        ]),
        h(2, 'MAKİNE / EKİPMAN LİSTESİ'),
        table(['No', 'Makine Adı', 'Marka/Model', 'Seri No', 'Üretim Yılı', 'Bölüm', 'Periyodik Kontrol Tarihi', 'Durum'], [
          ['1', '', '', '', '', '', '', ''],
          ['2', '', '', '', '', '', '', ''],
          ['3', '', '', '', '', '', '', ''],
          ['4', '', '', '', '', '', '', ''],
          ['5', '', '', '', '', '', '', ''],
          ['6', '', '', '', '', '', '', ''],
          ['7', '', '', '', '', '', '', ''],
          ['8', '', '', '', '', '', '', ''],
          ['9', '', '', '', '', '', '', ''],
          ['10', '', '', '', '', '', '', ''],
        ]),
        p('Durum: A=Aktif, P=Pasif, H=Hurda, T=Tamirde'),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan', 'Teknik Sorumlu'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
];

// ============================================================
// GROUP 17 — Periyodik Kontrol
// Helper: concise template pattern for periodic inspections
// ============================================================

function periyodikKontrolSablonu(
  id: string,
  title: string,
  description: string,
  ekipmanAdi: string,
  kontrolKalemleri: string[],
  yasal: string
): P1Template {
  return {
    id,
    groupKey: 'periyodik-kontrol',
    title,
    description,
    variables: ['firma_adi', 'bugun', 'bir_yil_sonra'],
    content: {
      type: 'doc',
      content: [
        h(1, title.toUpperCase()),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'EKİPMAN BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          [ekipmanAdi + ' Adı / Tanımı', ''],
          ['Marka / Model', ''],
          ['Seri No / Kapasite', ''],
          ['Bulunduğu Yer', ''],
          ['Kontrol Tarihi', '{{bugun}}'],
          ['Kontrol Eden Firma / Kişi', ''],
        ]),
        h(2, 'KONTROL SONUÇLARI'),
        table(
          ['Sıra', 'Kontrol Kalemi', 'Uygun', 'Uygun Değil', 'Açıklama'],
          kontrolKalemleri.map((kalem, i) => [String(i + 1), kalem, '☐', '☐', ''])
        ),
        h(2, 'GENEL DEĞERLENDİRME'),
        p('☐ Kullanıma uygundur  ☐ Koşullu uygun (düzeltme gerekli)  ☐ Kullanıma uygun değildir'),
        p('Sonraki Kontrol Tarihi: {{bir_yil_sonra}}'),
        h(2, 'İMZALAR'),
        table(['', 'Kontrol Eden', 'İşveren / Sorumlu'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza / Kaşe', '', ''],
        ]),
        p(yasal),
      ],
    },
  };
}

export const GROUP17_TEMPLATES: P1Template[] = [
  periyodikKontrolSablonu(
    'asansor-kontrol',
    'Asansör Periyodik Kontrol Formu',
    'Asansör yıllık periyodik kontrol ve muayene kaydı',
    'Asansör',
    [
      'Makine dairesi ve ekipmanları',
      'Kuyu ve güvenlik mesafeleri',
      'Kabin ve kabin kapıları',
      'Kat kapıları ve kilitleri',
      'Halatlar / zincirler',
      'Tamponlar ve sınır kesiciler',
      'Acil kurtarma sistemi',
      'Elektrik tesisatı ve topraklama',
    ],
    'Asansör Bakım ve İşletme Yönetmeliği gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'basincli-kap',
    'Basınçlı Kap Periyodik Kontrol Formu',
    'Basınçlı kaplar periyodik test ve muayene kaydı',
    'Basınçlı Kap',
    [
      'Dış yüzey muayenesi (korozyon, deformasyon)',
      'İç muayene (temizlik, aşınma)',
      'Emniyet vanaları ve basınç düşürücüler',
      'Manometre kontrolü ve kalibrasyonu',
      'Boru bağlantıları ve contalar',
      'Hidrostatik test',
      'Etiket ve işaretleme kontrolü',
    ],
    'İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği Ek-III gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'elektrik-tesisati',
    'Elektrik Tesisatı Periyodik Kontrol Formu',
    'Elektrik iç tesisatı periyodik kontrol ve ölçüm kaydı',
    'Elektrik Tesisatı',
    [
      'Pano genel durumu ve kilitleri',
      'Sigorta ve şalterler',
      'Kaçak akım rölesi (KAR) testi',
      'İzolasyon direnci ölçümü',
      'Topraklama direnci ölçümü',
      'Kablo bağlantıları ve ek yerleri',
      'Priz ve aydınlatma armatürleri',
      'Uyarı işaretleri ve etiketler',
    ],
    'Elektrik İç Tesisleri Yönetmeliği ve İş Ekipmanları Yönetmeliği gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'topraklama-kontrol',
    'Topraklama Tesisatı Kontrol Formu',
    'Topraklama tesisatı periyodik ölçüm ve kontrol kaydı',
    'Topraklama Tesisatı',
    [
      'Topraklama iletkenleri bağlantı durumu',
      'Topraklama direnci ölçümü',
      'Eşpotansiyel bara bağlantıları',
      'Topraklama elektrot durumu',
      'Koruma iletkeni sürekliliği',
      'İşaretleme ve etiketler',
    ],
    'Elektrik Tesislerinde Topraklamalar Yönetmeliği gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'paratoner-kontrol',
    'Paratoner Periyodik Kontrol Formu',
    'Yıldırımdan korunma (paratoner) sistemi periyodik kontrolü',
    'Paratoner',
    [
      'Yakalama ucu ve montaj durumu',
      'İniş iletkeni bağlantıları',
      'Topraklama sistemi direnci',
      'Sayaç (darbe sayacı) kontrolü',
      'Korozyon ve fiziksel hasar',
      'Koruma bölgesi yeterliliği',
    ],
    'Yapı Denetimi Hakkında Kanun ve Elektrik Kuvvetli Akım Tesisleri Yönetmeliği gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'yangin-tup-kontrol',
    'Yangın Tüpü Kontrol Formu',
    'Yangın söndürme tüpleri periyodik kontrol ve bakım kaydı',
    'Yangın Tüpü',
    [
      'Tüp gövde durumu (ezik, korozyon)',
      'Manometre basınç göstergesi',
      'Pim ve mühür durumu',
      'Hortum ve lans kontrolü',
      'Etiket ve son kullanma tarihi',
      'Montaj yeri ve erişilebilirlik',
      'Dolum tarihi kontrolü',
    ],
    'Binaların Yangından Korunması Hakkında Yönetmelik gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'yangin-dolap-kontrol',
    'Yangın Dolabı Kontrol Formu',
    'Yangın dolabı ve hortum sistemi periyodik kontrol kaydı',
    'Yangın Dolabı',
    [
      'Dolap kapağı ve kilidi',
      'Hortum durumu ve bağlantıları',
      'Vana çalışması',
      'Lans (nozul) durumu',
      'Su basıncı testi',
      'İşaretleme ve yönlendirme',
    ],
    'Binaların Yangından Korunması Hakkında Yönetmelik gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'kompressor-kontrol',
    'Kompresör Periyodik Kontrol Formu',
    'Hava kompresörü periyodik kontrol ve muayene kaydı',
    'Kompresör',
    [
      'Genel dış görünüm ve temizlik',
      'Emniyet valfi testi',
      'Manometre kontrolü',
      'Kayış ve bağlantı elemanları',
      'Yağ seviyesi ve kalitesi',
      'Hava filtresi durumu',
      'Elektrik bağlantıları',
      'Titreşim ve ses seviyesi',
    ],
    'İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'vinc-kontrol',
    'Vinç Periyodik Kontrol Formu',
    'Kaldırma ve iletme ekipmanı (vinç) periyodik kontrol kaydı',
    'Vinç',
    [
      'Çelik halatlar ve zincirler',
      'Kanca ve emniyet mandalı',
      'Fren sistemi',
      'Sınır kesiciler (limitörler)',
      'Elektrik sistemi ve kumanda',
      'Yapısal bütünlük (gövde, bom)',
      'Yük göstergesi / sınırlayıcı',
      'Topraklama',
    ],
    'İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği Ek-II gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'kazan-kontrol',
    'Kazan Periyodik Kontrol Formu',
    'Buhar ve sıcak su kazanları periyodik kontrol kaydı',
    'Kazan',
    [
      'Kazan gövdesi dış muayenesi',
      'İç muayene (tortu, korozyon)',
      'Emniyet vanaları testi',
      'Manometre ve termometre kontrolü',
      'Alev ve duman boruları',
      'Baca sistemi',
      'Su seviye göstergesi',
      'Otomatik kontrol sistemi',
    ],
    'İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği Ek-III gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'havalandirma-kontrol',
    'Havalandırma Sistemi Kontrol Formu',
    'Havalandırma ve klima sistemi periyodik kontrol kaydı',
    'Havalandırma Sistemi',
    [
      'Fan ve motor durumu',
      'Filtre temizlik/değişim durumu',
      'Kanal temizliği ve sızdırmazlık',
      'Hava debisi ölçümü',
      'Kayış ve bağlantılar',
      'Titreşim ve ses seviyesi',
      'Damper ve vana çalışması',
    ],
    'İşyeri Bina ve Eklentilerinde Alınacak Sağlık ve Güvenlik Önlemlerine İlişkin Yönetmelik gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'jenerator-kontrol',
    'Jeneratör Periyodik Kontrol Formu',
    'Dizel/benzinli jeneratör periyodik kontrol ve bakım kaydı',
    'Jeneratör',
    [
      'Motor yağı ve filtre durumu',
      'Yakıt sistemi ve sızıntı',
      'Akü durumu ve şarj',
      'Soğutma sistemi',
      'Egzoz sistemi',
      'Otomatik devreye girme testi',
      'Elektrik bağlantıları',
      'Yük altında çalışma testi',
    ],
    'İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'lpg-kontrol',
    'LPG Tesisatı Kontrol Formu',
    'LPG depolama ve dağıtım tesisatı periyodik kontrol kaydı',
    'LPG Tesisatı',
    [
      'Tank dış muayenesi',
      'Boru ve bağlantı sızdırmazlık testi',
      'Emniyet vanaları',
      'Basınç regülatörleri',
      'Gaz algılama sistemi',
      'Havalandırma yeterliliği',
      'İşaretleme ve uyarı levhaları',
    ],
    'Sıvılaştırılmış Petrol Gazları (LPG) ile Çalışan Motorlu Taşıtlar İçin İkmal İstasyonlarının Kuruluş ve İşletme Yönetmeliği gereğince düzenlenmiştir.'
  ),
  periyodikKontrolSablonu(
    'merdiven-iskele',
    'Merdiven ve İskele Kontrol Formu',
    'Taşınabilir merdiven ve iskele periyodik kontrol kaydı',
    'Merdiven / İskele',
    [
      'Genel yapısal bütünlük',
      'Basamak / platform durumu',
      'Bağlantı elemanları ve kilit mekanizması',
      'Korkuluk ve ayak koruma',
      'Kaymaz taban / ayak',
      'Yük kapasitesi etiketi',
      'Çapraz bağlantılar (iskele)',
      'Sabitleme ve ankraj (iskele)',
    ],
    'Yapı İşlerinde İş Sağlığı ve Güvenliği Yönetmeliği gereğince düzenlenmiştir.'
  ),
];

// ============================================================
// GROUP 18 — Diğer Kayıtlar
// ============================================================

export const GROUP18_TEMPLATES: P1Template[] = [
  {
    id: 'msds-kayit',
    groupKey: 'diger-kayitlar',
    title: 'MSDS / GBF Kayıt Formu',
    description: 'Malzeme güvenlik bilgi formu (MSDS/GBF) kayıt ve takip formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'MSDS / GÜVENLİK BİLGİ FORMU KAYIT'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'KİMYASAL MADDE LİSTESİ'),
        table(['Sıra', 'Ürün Adı', 'Üretici', 'CAS No', 'Tehlike Sınıfı', 'GBF Tarihi', 'GBF Mevcut'], [
          ['1', '', '', '', '', '', '☐'],
          ['2', '', '', '', '', '', '☐'],
          ['3', '', '', '', '', '', '☐'],
          ['4', '', '', '', '', '', '☐'],
          ['5', '', '', '', '', '', '☐'],
          ['6', '', '', '', '', '', '☐'],
          ['7', '', '', '', '', '', '☐'],
          ['8', '', '', '', '', '', '☐'],
        ]),
        h(2, 'NOTLAR'),
        bullet([
          'Tüm GBF\'ler Türkçe olarak temin edilmelidir',
          'GBF\'ler kimyasalın kullanıldığı bölümde erişilebilir olmalıdır',
          'Yeni kimyasal alımlarında GBF temin edilmeden kullanım yapılmamalıdır',
        ]),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan'], [
          ['Ad Soyad', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
        p('Kimyasal Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'is-izni-formu',
    groupKey: 'diger-kayitlar',
    title: 'Genel İş İzni Formu',
    description: 'Tehlikeli işler için genel çalışma izni belgesi',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ÇALIŞMA İZNİ FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'İŞ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['İş Tanımı', ''],
          ['Çalışma Alanı', ''],
          ['Başlangıç Tarih/Saat', ''],
          ['Bitiş Tarih/Saat', ''],
          ['Sorumlu Kişi', ''],
          ['Çalışacak Personel', ''],
        ]),
        h(2, 'GÜVENLİK ÖNLEMLERİ'),
        table(['Önlem', 'Alındı'], [
          ['Alan güvenliği sağlandı', '☐'],
          ['İlgili personel bilgilendirildi', '☐'],
          ['Gerekli KKD temin edildi', '☐'],
          ['Enerji kesme/kilitleme (LOTO) uygulandı', '☐'],
          ['Yangın söndürme ekipmanı hazırlandı', '☐'],
          ['İlkyardım malzemesi mevcut', '☐'],
        ]),
        h(2, 'ONAY'),
        table(['', 'İş Sorumlusu', 'İSG Uzmanı', 'İşveren Vekili'], [
          ['Ad Soyad', '', '{{uzman_adi}}', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', '', ''],
        ]),
        p('İş tamamlandıktan sonra alan kontrol edilecek ve bu form kapatılacaktır.'),
      ],
    },
  },
  {
    id: 'sicak-is-izni',
    groupKey: 'diger-kayitlar',
    title: 'Sıcak İş İzni Formu',
    description: 'Kaynak, kesme, lehim gibi sıcak çalışma izni',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'SICAK ÇALIŞMA İZNİ FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'İŞ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Yapılacak İş', '☐ Kaynak  ☐ Kesme  ☐ Taşlama  ☐ Lehim  ☐ Diğer'],
          ['Çalışma Alanı', ''],
          ['Tarih / Saat', '{{bugun}}'],
          ['Çalışacak Personel', ''],
        ]),
        h(2, 'GÜVENLİK ÖNLEMLERİ'),
        table(['Önlem', 'Kontrol'], [
          ['Yanıcı malzemeler uzaklaştırıldı (min. 10 m)', '☐'],
          ['Yanıcı yüzeyler örtüldü / ıslatıldı', '☐'],
          ['Yangın söndürücü hazır bulunduruldu', '☐'],
          ['Gaz ölçümü yapıldı (patlayıcı ortam)', '☐'],
          ['Havalandırma sağlandı', '☐'],
          ['Gözetmen (ateş gözcüsü) atandı', '☐'],
          ['Uygun KKD (kaynak maskesi, eldiven, önlük) mevcut', '☐'],
          ['Çalışma sonrası 1 saat gözetim planlandı', '☐'],
        ]),
        h(2, 'ONAY'),
        table(['', 'Çalışan', 'Ateş Gözcüsü', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', '', ''],
        ]),
        p('6331 sayılı İSG Kanunu ve Patlayıcı Ortamların Tehlikelerinden Çalışanların Korunması Hakkında Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'yuksekte-is-izni',
    groupKey: 'diger-kayitlar',
    title: 'Yüksekte Çalışma İzni Formu',
    description: 'Yüksekte çalışma (1.8 m üzeri) izin belgesi',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'YÜKSEKTE ÇALIŞMA İZNİ FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'İŞ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Yapılacak İş', ''],
          ['Çalışma Yüksekliği', ''],
          ['Çalışma Alanı', ''],
          ['Tarih', '{{bugun}}'],
          ['Çalışacak Personel', ''],
        ]),
        h(2, 'GÜVENLİK ÖNLEMLERİ'),
        table(['Önlem', 'Kontrol'], [
          ['Yüksekte çalışma eğitimi alındı', '☐'],
          ['Emniyet kemeri / yaşam hattı bağlandı', '☐'],
          ['İskele / platform kurulumu kontrol edildi', '☐'],
          ['Korkuluk sistemi mevcut', '☐'],
          ['Çalışma alanı altı bariyerle kapatıldı', '☐'],
          ['Malzeme düşme önlemi alındı', '☐'],
          ['Hava koşulları uygun (rüzgar < 40 km/s)', '☐'],
          ['Acil kurtarma planı hazır', '☐'],
        ]),
        h(2, 'ONAY'),
        table(['', 'Çalışan', 'İSG Uzmanı', 'İşveren Vekili'], [
          ['Ad Soyad', '', '{{uzman_adi}}', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', '', ''],
        ]),
        p('Yapı İşlerinde İş Sağlığı ve Güvenliği Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'kapali-alan-izni',
    groupKey: 'diger-kayitlar',
    title: 'Kapalı Alan Çalışma İzni Formu',
    description: 'Kapalı / sınırlı alan giriş ve çalışma izni',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KAPALI ALAN ÇALIŞMA İZNİ FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ALAN BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Kapalı Alan Tanımı', ''],
          ['Yapılacak İş', ''],
          ['Tarih / Saat', '{{bugun}}'],
          ['Giriş Yapacak Personel', ''],
          ['Gözetmen (Delik Bekçisi)', ''],
        ]),
        h(2, 'GAZ ÖLÇÜM SONUÇLARI'),
        table(['Parametre', 'Ölçüm Değeri', 'Sınır Değer', 'Uygun'], [
          ['Oksijen (O₂)', '', '%19.5-23.5', '☐'],
          ['Alt Patlama Sınırı (LEL)', '', '<%10', '☐'],
          ['Karbon Monoksit (CO)', '', '<25 ppm', '☐'],
          ['Hidrojen Sülfür (H₂S)', '', '<10 ppm', '☐'],
        ]),
        h(2, 'GÜVENLİK ÖNLEMLERİ'),
        table(['Önlem', 'Kontrol'], [
          ['Havalandırma sağlandı', '☐'],
          ['İletişim sistemi kuruldu', '☐'],
          ['Kurtarma ekipmanları hazır', '☐'],
          ['LOTO uygulandı', '☐'],
          ['Uygun KKD (solunum cihazı, emniyet kemeri)', '☐'],
          ['Acil kurtarma planı hazır', '☐'],
        ]),
        h(2, 'ONAY'),
        table(['', 'Giriş Yapan', 'Gözetmen', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'kazi-is-izni',
    groupKey: 'diger-kayitlar',
    title: 'Kazı İşleri İzni Formu',
    description: 'Kazı çalışması güvenlik izin belgesi',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KAZI İŞLERİ ÇALIŞMA İZNİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'İŞ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Kazı Alanı', ''],
          ['Kazı Derinliği', ''],
          ['Yapılacak İş', ''],
          ['Tarih', '{{bugun}}'],
          ['Çalışacak Personel', ''],
        ]),
        h(2, 'GÜVENLİK ÖNLEMLERİ'),
        table(['Önlem', 'Kontrol'], [
          ['Yeraltı tesisatları (elektrik, gaz, su) tespit edildi', '☐'],
          ['İksa / şev açısı uygulandı', '☐'],
          ['Kenar korkulukları / bariyerler yerleştirildi', '☐'],
          ['Giriş-çıkış merdiveni konuldu', '☐'],
          ['Kazı malzemesi kenardan min. 60 cm uzakta', '☐'],
          ['İşaret ve uyarı levhaları yerleştirildi', '☐'],
          ['Hava koşulları uygun', '☐'],
        ]),
        h(2, 'ONAY'),
        table(['', 'İş Sorumlusu', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('Yapı İşlerinde İş Sağlığı ve Güvenliği Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'ortam-olcum',
    groupKey: 'diger-kayitlar',
    title: 'Ortam Ölçüm Raporu',
    description: 'Genel çalışma ortamı ölçüm sonuç raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'ORTAM ÖLÇÜM RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÖLÇÜM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Ölçüm Tarihi', '{{bugun}}'],
          ['Ölçüm Yapan Kuruluş', ''],
          ['Ölçüm Türü', '☐ Gürültü  ☐ Toz  ☐ Aydınlatma  ☐ Termal Konfor  ☐ Titreşim  ☐ Kimyasal'],
        ]),
        h(2, 'ÖLÇÜM SONUÇLARI'),
        table(['Ölçüm Noktası', 'Parametre', 'Ölçüm Değeri', 'Sınır Değer', 'Uygunluk'], [
          ['', '', '', '', '☐ Uygun  ☐ Uygun Değil'],
          ['', '', '', '', '☐ Uygun  ☐ Uygun Değil'],
          ['', '', '', '', '☐ Uygun  ☐ Uygun Değil'],
          ['', '', '', '', '☐ Uygun  ☐ Uygun Değil'],
          ['', '', '', '', '☐ Uygun  ☐ Uygun Değil'],
        ]),
        h(2, 'DEĞERLENDİRME VE ÖNERİLER'),
        p(''),
        h(2, 'ONAY'),
        table(['', 'Ölçüm Sorumlusu', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('İş Hijyeni Ölçüm, Test ve Analizi Yapan Laboratuvarlar Hakkında Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'gurultu-haritasi',
    groupKey: 'diger-kayitlar',
    title: 'Gürültü Haritası ve Ölçüm Raporu',
    description: 'İşyeri gürültü haritası ve maruziyet değerlendirmesi',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'GÜRÜLTÜ HARİTASI VE ÖLÇÜM RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÖLÇÜM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Ölçüm Tarihi', '{{bugun}}'],
          ['Ölçüm Cihazı', ''],
          ['Kalibrasyon Tarihi', ''],
          ['Ölçüm Yapan', ''],
        ]),
        h(2, 'GÜRÜLTÜ ÖLÇÜM SONUÇLARI'),
        table(['Bölüm', 'Ölçüm Noktası', 'dB(A)', 'Maruziyet Süresi', 'LEX,8h', 'Risk'], [
          ['', '', '', '', '', ''],
          ['', '', '', '', '', ''],
          ['', '', '', '', '', ''],
          ['', '', '', '', '', ''],
          ['', '', '', '', '', ''],
        ]),
        p('Maruziyet Eylem Değerleri: Alt: 80 dB(A), Üst: 85 dB(A), Maruziyet Sınır Değeri: 87 dB(A)'),
        h(2, 'ÖNERİLEN TEDBİRLER'),
        bullet([
          '80-85 dB(A): Kulak koruyucu temin edilmeli',
          '85 dB(A) üzeri: Kulak koruyucu kullanımı zorunlu, sağlık gözetimi yapılmalı',
          'Teknik önlemler (ses yalıtımı, bakım) değerlendirilmeli',
        ]),
        h(2, 'ONAY'),
        table(['', 'Ölçüm Sorumlusu', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('Çalışanların Gürültü ile İlgili Risklerden Korunmalarına Dair Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'aydinlatma-olcum',
    groupKey: 'diger-kayitlar',
    title: 'Aydınlatma Ölçüm Raporu',
    description: 'İşyeri aydınlatma seviyesi ölçüm raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'AYDINLATMA ÖLÇÜM RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÖLÇÜM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Ölçüm Tarihi', '{{bugun}}'],
          ['Ölçüm Cihazı (Lüksmetre)', ''],
          ['Kalibrasyon Tarihi', ''],
        ]),
        h(2, 'ÖLÇÜM SONUÇLARI'),
        table(['Bölüm', 'Ölçüm Noktası', 'Ölçülen (Lux)', 'Olması Gereken (Lux)', 'Uygun'], [
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
        ]),
        h(2, 'REFERANS DEĞERLER'),
        bullet([
          'Koridorlar ve merdivenler: min. 100 Lux',
          'Genel ofis alanları: min. 300 Lux',
          'Detaylı iş yapılan alanlar: min. 500 Lux',
          'Hassas iş yapılan alanlar: min. 750 Lux',
        ]),
        h(2, 'ONAY'),
        table(['', 'Ölçüm Sorumlusu', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('İşyeri Bina ve Eklentilerinde Alınacak Sağlık ve Güvenlik Önlemlerine İlişkin Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'termal-konfor',
    groupKey: 'diger-kayitlar',
    title: 'Termal Konfor Ölçüm Raporu',
    description: 'İşyeri sıcaklık, nem ve hava akım hızı ölçüm raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'TERMAL KONFOR ÖLÇÜM RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÖLÇÜM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Ölçüm Tarihi', '{{bugun}}'],
          ['Dış Ortam Sıcaklığı', ''],
          ['Ölçüm Cihazları', ''],
        ]),
        h(2, 'ÖLÇÜM SONUÇLARI'),
        table(['Bölüm', 'Sıcaklık (°C)', 'Nem (%)', 'Hava Akım Hızı (m/s)', 'Uygun'], [
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
        ]),
        h(2, 'REFERANS DEĞERLER'),
        bullet([
          'Hafif işlerde sıcaklık: 20-24 °C',
          'Ağır işlerde sıcaklık: 17-21 °C',
          'Bağıl nem: %40-60',
          'Hava akım hızı: 0.1-0.3 m/s',
        ]),
        h(2, 'ONAY'),
        table(['', 'Ölçüm Sorumlusu', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'toz-olcum',
    groupKey: 'diger-kayitlar',
    title: 'Toz Ölçüm Raporu',
    description: 'İşyeri havadaki toz konsantrasyonu ölçüm raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'TOZ ÖLÇÜM RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÖLÇÜM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Ölçüm Tarihi', '{{bugun}}'],
          ['Ölçüm Yöntemi', ''],
          ['Ölçüm Cihazı', ''],
          ['Kalibrasyon Tarihi', ''],
        ]),
        h(2, 'ÖLÇÜM SONUÇLARI'),
        table(['Bölüm', 'Toz Türü', 'Ölçülen (mg/m³)', 'Sınır Değer (mg/m³)', 'Uygun'], [
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
        ]),
        h(2, 'ÖNERİLEN TEDBİRLER'),
        p(''),
        h(2, 'ONAY'),
        table(['', 'Ölçüm Sorumlusu', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('Tozla Mücadele Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'titresim-olcum',
    groupKey: 'diger-kayitlar',
    title: 'Titreşim Ölçüm Raporu',
    description: 'İşyeri el-kol ve bütün vücut titreşim ölçüm raporu',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'TİTREŞİM ÖLÇÜM RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ÖLÇÜM BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Ölçüm Tarihi', '{{bugun}}'],
          ['Ölçüm Cihazı', ''],
          ['Ölçüm Türü', '☐ El-Kol Titreşimi  ☐ Bütün Vücut Titreşimi'],
        ]),
        h(2, 'ÖLÇÜM SONUÇLARI'),
        table(['Ekipman/Bölüm', 'Ölçüm Değeri (m/s²)', 'Maruziyet Süresi', 'A(8) Değeri', 'Uygun'], [
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
          ['', '', '', '', '☐'],
        ]),
        h(2, 'SINIR DEĞERLER'),
        bullet([
          'El-Kol: Eylem değeri 2.5 m/s², Sınır değer 5 m/s²',
          'Bütün Vücut: Eylem değeri 0.5 m/s², Sınır değer 1.15 m/s²',
        ]),
        h(2, 'ONAY'),
        table(['', 'Ölçüm Sorumlusu', 'İSG Uzmanı'], [
          ['Ad Soyad', '', '{{uzman_adi}}'],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('Çalışanların Titreşimle İlgili Risklerden Korunmalarına Dair Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
];

// ============================================================
// GROUP 19 — Yangın / Kimyasal
// ============================================================

export const GROUP19_TEMPLATES: P1Template[] = [
  {
    id: 'yangin-risk-analizi',
    groupKey: 'yangin-kimyasal',
    title: 'Yangın Risk Analizi',
    description: 'İşyeri yangın risk değerlendirme raporu',
    variables: ['firma_adi', 'firma_adresi', 'firma_sehir', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'YANGIN RİSK ANALİZİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'İŞYERİ BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['İşyeri', '{{firma_adi}}'],
          ['Adres', '{{firma_adresi}}, {{firma_sehir}}'],
          ['Değerlendirme Tarihi', '{{bugun}}'],
          ['Hazırlayan', '{{uzman_adi}}'],
        ]),
        h(2, 'YANGIN TEHLİKELERİ'),
        table(['Sıra', 'Tehlike Kaynağı', 'Bölüm', 'Risk Seviyesi', 'Mevcut Önlem'], [
          ['1', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
          ['2', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
          ['3', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
          ['4', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
          ['5', '', '', '☐ Yüksek  ☐ Orta  ☐ Düşük', ''],
        ]),
        h(2, 'MEVCUT YANGIN GÜVENLİK SİSTEMLERİ'),
        table(['Sistem', 'Mevcut', 'Yeterli', 'Açıklama'], [
          ['Yangın algılama ve ihbar sistemi', '☐', '☐', ''],
          ['Otomatik söndürme sistemi (sprinkler)', '☐', '☐', ''],
          ['Yangın tüpleri', '☐', '☐', ''],
          ['Yangın dolapları', '☐', '☐', ''],
          ['Acil aydınlatma', '☐', '☐', ''],
          ['Tahliye yönlendirme işaretleri', '☐', '☐', ''],
          ['Yangın merdiveni', '☐', '☐', ''],
        ]),
        h(2, 'ÖNERİLEN TEDBİRLER'),
        table(['Sıra', 'Tedbir', 'Öncelik', 'Sorumlu', 'Termin'], [
          ['1', '', '', '', ''],
          ['2', '', '', '', ''],
          ['3', '', '', '', ''],
        ]),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan', 'İşveren Vekili'], [
          ['Ad Soyad', '{{uzman_adi}}', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
        p('Binaların Yangından Korunması Hakkında Yönetmelik ve 6331 sayılı İSG Kanunu gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'yangin-sondurme-plani',
    groupKey: 'yangin-kimyasal',
    title: 'Yangın Söndürme Planı',
    description: 'İşyeri yangın söndürme ve müdahale planı',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'YANGIN SÖNDÜRME VE MÜDAHALE PLANI'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'YANGIN SÖNDÜRME EKİBİ'),
        table(['Görev', 'Adı Soyadı', 'Departman', 'Telefon'], [
          ['Ekip Başı', '', '', ''],
          ['Söndürme Görevlisi', '', '', ''],
          ['Söndürme Görevlisi', '', '', ''],
          ['Söndürme Görevlisi', '', '', ''],
        ]),
        h(2, 'SÖNDÜRME EKİPMANLARI'),
        table(['Ekipman', 'Tür', 'Adet', 'Konum'], [
          ['Yangın tüpü (kuru kimyevi)', '', '', ''],
          ['Yangın tüpü (CO₂)', '', '', ''],
          ['Yangın dolabı', '', '', ''],
          ['Otomatik söndürme sistemi', '', '', ''],
        ]),
        h(2, 'MÜDAHALE PROSEDÜRÜ'),
        bullet([
          '1. Yangın ihbar butonuna basılır veya 110 aranır',
          '2. Tahliye alarmı verilir',
          '3. Söndürme ekibi müdahale eder',
          '4. Elektrik kesilir (gerekli ise)',
          '5. Tahliye planına göre bina boşaltılır',
          '6. İtfaiye ekibi karşılanır ve bilgilendirilir',
          '7. Toplanma alanında sayım yapılır',
        ]),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan', 'İşveren Vekili'], [
          ['Ad Soyad', '{{uzman_adi}}', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
      ],
    },
  },
  {
    id: 'kimyasal-envanter',
    groupKey: 'yangin-kimyasal',
    title: 'Kimyasal Madde Envanteri',
    description: 'İşyerinde kullanılan kimyasal maddelerin envanter listesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KİMYASAL MADDE ENVANTERİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'ENVANTER BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Düzenleme Tarihi', '{{bugun}}'],
          ['Düzenleyen', ''],
        ]),
        h(2, 'KİMYASAL LİSTESİ'),
        table(['No', 'Ürün Adı', 'CAS No', 'Tehlike Piktogramı', 'Miktar', 'Depolama Yeri', 'GBF Mevcut'], [
          ['1', '', '', '', '', '', '☐'],
          ['2', '', '', '', '', '', '☐'],
          ['3', '', '', '', '', '', '☐'],
          ['4', '', '', '', '', '', '☐'],
          ['5', '', '', '', '', '', '☐'],
          ['6', '', '', '', '', '', '☐'],
          ['7', '', '', '', '', '', '☐'],
          ['8', '', '', '', '', '', '☐'],
          ['9', '', '', '', '', '', '☐'],
          ['10', '', '', '', '', '', '☐'],
        ]),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan', 'İSG Uzmanı'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('Kimyasal Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'kimyasal-risk',
    groupKey: 'yangin-kimyasal',
    title: 'Kimyasal Risk Değerlendirmesi',
    description: 'Kimyasal maddelere maruz kalma risk değerlendirmesi',
    variables: ['firma_adi', 'uzman_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KİMYASAL RİSK DEĞERLENDİRMESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'DEĞERLENDİRME BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Değerlendirme Tarihi', '{{bugun}}'],
          ['Değerlendiren', '{{uzman_adi}}'],
          ['Bölüm', ''],
        ]),
        h(2, 'KİMYASAL MARUZİYET DEĞERLENDİRME'),
        table(['Kimyasal', 'Maruziyet Yolu', 'Süre/Sıklık', 'MED/Sınır Değer', 'Risk Seviyesi', 'Önlem'], [
          ['', '☐ Soluma ☐ Cilt ☐ Yutma', '', '', '', ''],
          ['', '☐ Soluma ☐ Cilt ☐ Yutma', '', '', '', ''],
          ['', '☐ Soluma ☐ Cilt ☐ Yutma', '', '', '', ''],
          ['', '☐ Soluma ☐ Cilt ☐ Yutma', '', '', '', ''],
        ]),
        h(2, 'KONTROL TEDBİRLERİ'),
        bullet([
          'Mühendislik kontrolleri (havalandırma, kapalı sistem)',
          'İdari kontroller (prosedür, eğitim, iş rotasyonu)',
          'Kişisel koruyucu donanım (maske, eldiven, gözlük)',
          'Acil durum malzemeleri (göz duşu, duş, nötralizasyon)',
        ]),
        h(2, 'ONAY'),
        table(['', 'Değerlendiren', 'İşveren Vekili'], [
          ['Ad Soyad', '{{uzman_adi}}', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
        p('Kimyasal Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'kimyasal-depolama',
    groupKey: 'yangin-kimyasal',
    title: 'Kimyasal Depolama Kontrol Formu',
    description: 'Kimyasal madde depolama alanı kontrol formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'KİMYASAL DEPOLAMA KONTROL FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'DEPO BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Depo Adı / Konumu', ''],
          ['Kontrol Tarihi', '{{bugun}}'],
          ['Kontrol Eden', ''],
        ]),
        h(2, 'KONTROL NOKTALARI'),
        table(['Sıra', 'Kontrol Kalemi', 'Uygun', 'Uygun Değil', 'Açıklama'], [
          ['1', 'Uyumsuz kimyasallar ayrı depolanıyor', '☐', '☐', ''],
          ['2', 'Tüm kaplar etiketli ve kapalı', '☐', '☐', ''],
          ['3', 'GBF dosyası erişilebilir durumda', '☐', '☐', ''],
          ['4', 'Havalandırma yeterli', '☐', '☐', ''],
          ['5', 'Döküntü toplama kabı/havuzu mevcut', '☐', '☐', ''],
          ['6', 'Yangın söndürme ekipmanı mevcut', '☐', '☐', ''],
          ['7', 'Göz duşu ve acil duş erişilebilir', '☐', '☐', ''],
          ['8', 'Uyarı işaretleri ve levhalar mevcut', '☐', '☐', ''],
          ['9', 'Sıcaklık ve nem uygun', '☐', '☐', ''],
          ['10', 'Genel düzen ve temizlik', '☐', '☐', ''],
        ]),
        h(2, 'SONUÇ'),
        p('☐ Uygun  ☐ Koşullu uygun  ☐ Uygun değil'),
        table(['', 'Kontrol Eden'], [
          ['Ad Soyad', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
      ],
    },
  },
  {
    id: 'yangin-tatbikat',
    groupKey: 'yangin-kimyasal',
    title: 'Yangın Tatbikat Raporu',
    description: 'Yangın ve tahliye tatbikatı değerlendirme raporu',
    variables: ['firma_adi', 'uzman_adi', 'personel_sayisi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'YANGIN TATBİKAT RAPORU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'TATBİKAT BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Tatbikat Tarihi', '{{bugun}}'],
          ['Tatbikat Türü', '☐ Yangın  ☐ Deprem  ☐ Tahliye  ☐ Kombine'],
          ['Katılımcı Sayısı', '{{personel_sayisi}}'],
          ['Senaryo', ''],
        ]),
        h(2, 'TATBİKAT DEĞERLENDİRME'),
        table(['Kriter', 'Süre / Değer', 'Hedef', 'Uygun'], [
          ['İhbar süresi', '', '< 1 dk', '☐'],
          ['Tahliye süresi', '', '< 3 dk', '☐'],
          ['Toplanma süresi', '', '< 5 dk', '☐'],
          ['Sayım tamamlanma', '', '%100', '☐'],
          ['Söndürme müdahalesi', '', '< 2 dk', '☐'],
        ]),
        h(2, 'TESPİTLER VE İYİLEŞTİRME'),
        table(['Tespit', 'İyileştirme Önerisi', 'Sorumlu'], [
          ['', '', ''],
          ['', '', ''],
          ['', '', ''],
        ]),
        h(2, 'ONAY'),
        table(['', 'İSG Uzmanı', 'İşveren Vekili'], [
          ['Ad Soyad', '{{uzman_adi}}', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
        p('6331 sayılı İSG Kanunu ve İşyerlerinde Acil Durumlar Hakkında Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'yangin-ekipman-kontrol',
    groupKey: 'yangin-kimyasal',
    title: 'Yangın Ekipmanları Genel Kontrol Formu',
    description: 'Tüm yangın güvenlik ekipmanlarının toplu kontrol formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'YANGIN EKİPMANLARI GENEL KONTROL FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'KONTROL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Kontrol Tarihi', '{{bugun}}'],
          ['Kontrol Eden', ''],
        ]),
        h(2, 'EKİPMAN KONTROL LİSTESİ'),
        table(['Ekipman', 'Konum', 'Adet', 'Son Bakım', 'Durum', 'Açıklama'], [
          ['Yangın tüpü (ABC)', '', '', '', '☐ Uygun ☐ Değil', ''],
          ['Yangın tüpü (CO₂)', '', '', '', '☐ Uygun ☐ Değil', ''],
          ['Yangın dolabı', '', '', '', '☐ Uygun ☐ Değil', ''],
          ['Algılama dedektörü', '', '', '', '☐ Uygun ☐ Değil', ''],
          ['İhbar butonu', '', '', '', '☐ Uygun ☐ Değil', ''],
          ['Acil aydınlatma', '', '', '', '☐ Uygun ☐ Değil', ''],
          ['Yönlendirme tabelası', '', '', '', '☐ Uygun ☐ Değil', ''],
          ['Sprinkler sistemi', '', '', '', '☐ Uygun ☐ Değil', ''],
        ]),
        h(2, 'GENEL SONUÇ'),
        p('☐ Tüm ekipmanlar uygun  ☐ Eksiklikler mevcut (yukarıda belirtildi)'),
        table(['', 'Kontrol Eden', 'Onaylayan'], [
          ['Ad Soyad', '', ''],
          ['Tarih', '{{bugun}}', '{{bugun}}'],
          ['İmza', '', ''],
        ]),
        p('Binaların Yangından Korunması Hakkında Yönetmelik gereğince düzenlenmiştir.'),
      ],
    },
  },
];

// ============================================================
// GROUP 20 — İlkyardım
// ============================================================

export const GROUP20_TEMPLATES: P1Template[] = [
  {
    id: 'ilkyardim-egitim-plani',
    groupKey: 'ilkyardim',
    title: 'İlkyardım Eğitim Planı',
    description: 'İlkyardım eğitimi yıllık plan ve takip belgesi',
    variables: ['firma_adi', 'personel_sayisi', 'isyeri_hekimi', 'bugun', 'yil'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İLKYARDIM EĞİTİM PLANI'),
        p('{{firma_adi}} — {{yil}} Yılı'),
        { type: 'horizontalRule' },
        h(2, 'GENEL BİLGİLER'),
        table(['Bilgi', 'Değer'], [
          ['Toplam Çalışan Sayısı', '{{personel_sayisi}}'],
          ['Olması Gereken İlkyardımcı Sayısı', ''],
          ['Mevcut Sertifikalı İlkyardımcı Sayısı', ''],
          ['İşyeri Hekimi', '{{isyeri_hekimi}}'],
        ]),
        h(2, 'EĞİTİM PLANI'),
        table(['Eğitim', 'Hedef Kitle', 'Süre', 'Planlanan Tarih', 'Eğitimci', 'Durum'], [
          ['Temel İlkyardım Eğitimi', 'Tüm çalışanlar', '16 saat', '', '', '☐'],
          ['İlkyardımcı Sertifika Eğitimi', 'Seçilen personel', '18 saat', '', '', '☐'],
          ['Sertifika Yenileme Eğitimi', 'Süresi dolanlar', '8 saat', '', '', '☐'],
          ['Uygulamalı Tatbikat', 'İlkyardımcılar', '2 saat', '', '', '☐'],
        ]),
        h(2, 'YASAL GEREKLİLİK'),
        bullet([
          'Az tehlikeli sınıf: Her 20 çalışan için 1 ilkyardımcı',
          'Tehlikeli sınıf: Her 15 çalışan için 1 ilkyardımcı',
          'Çok tehlikeli sınıf: Her 10 çalışan için 1 ilkyardımcı',
          'İlkyardımcı sertifikası 3 yılda bir yenilenir',
        ]),
        h(2, 'ONAY'),
        table(['', 'İşyeri Hekimi', 'İşveren Vekili'], [
          ['Ad Soyad', '{{isyeri_hekimi}}', ''],
          ['Tarih', '{{bugun}}', ''],
          ['İmza', '', ''],
        ]),
        p('İlkyardım Yönetmeliği ve 6331 sayılı İSG Kanunu Madde 11 gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'ilkyardimci-listesi',
    groupKey: 'ilkyardim',
    title: 'İlkyardımcı Listesi',
    description: 'Sertifikalı ilkyardımcı personel listesi',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'SERTİFİKALI İLKYARDIMCI LİSTESİ'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'İLKYARDIMCI LİSTESİ'),
        table(['Sıra', 'Adı Soyadı', 'Departman', 'Sertifika No', 'Sertifika Tarihi', 'Geçerlilik Bitiş', 'Telefon'], [
          ['1', '', '', '', '', '', ''],
          ['2', '', '', '', '', '', ''],
          ['3', '', '', '', '', '', ''],
          ['4', '', '', '', '', '', ''],
          ['5', '', '', '', '', '', ''],
          ['6', '', '', '', '', '', ''],
          ['7', '', '', '', '', '', ''],
          ['8', '', '', '', '', '', ''],
        ]),
        h(2, 'NOTLAR'),
        bullet([
          'İlkyardımcı sertifikaları 3 yılda bir yenilenmelidir',
          'Bu liste güncel tutulmalı ve çalışanlara duyurulmalıdır',
          'İlkyardımcı isimleri ve telefonları işyerinde görünür yerde asılmalıdır',
        ]),
        h(2, 'ONAY'),
        table(['', 'Hazırlayan'], [
          ['Ad Soyad', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
        p('İlkyardım Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
  {
    id: 'ilkyardim-malzeme',
    groupKey: 'ilkyardim',
    title: 'İlkyardım Malzeme Kontrol Formu',
    description: 'İlkyardım çantası / dolabı malzeme kontrol ve eksik takip formu',
    variables: ['firma_adi', 'bugun'],
    content: {
      type: 'doc',
      content: [
        h(1, 'İLKYARDIM MALZEME KONTROL FORMU'),
        p('{{firma_adi}}'),
        { type: 'horizontalRule' },
        h(2, 'KONTROL BİLGİLERİ'),
        table(['Bilgi', 'Değer'], [
          ['Kontrol Tarihi', '{{bugun}}'],
          ['Kontrol Eden', ''],
          ['Çanta / Dolap Konumu', ''],
        ]),
        h(2, 'MALZEME KONTROL LİSTESİ'),
        table(['Sıra', 'Malzeme', 'Olması Gereken', 'Mevcut', 'SKT Uygun', 'Eksik'], [
          ['1', 'Elastik bandaj (çeşitli)', '5 adet', '', '☐', '☐'],
          ['2', 'Gazlı bez (steril)', '10 adet', '', '☐', '☐'],
          ['3', 'Flaster (rulo)', '2 adet', '', '☐', '☐'],
          ['4', 'Yara bandı (çeşitli)', '20 adet', '', '☐', '☐'],
          ['5', 'Üçgen sargı bezi', '4 adet', '', '☐', '☐'],
          ['6', 'Makas', '1 adet', '', '—', '☐'],
          ['7', 'Tek kullanımlık eldiven', '10 çift', '', '☐', '☐'],
          ['8', 'Antiseptik solüsyon', '1 adet', '', '☐', '☐'],
          ['9', 'Buz torbası (anlık)', '2 adet', '', '☐', '☐'],
          ['10', 'Göz yıkama solüsyonu', '1 adet', '', '☐', '☐'],
          ['11', 'Turnike', '1 adet', '', '—', '☐'],
          ['12', 'CPR maskesi', '1 adet', '', '☐', '☐'],
        ]),
        h(2, 'EKSİK MALZEME TAKİBİ'),
        table(['Eksik Malzeme', 'Temin Tarihi', 'Temin Eden'], [
          ['', '', ''],
          ['', '', ''],
        ]),
        h(2, 'ONAY'),
        table(['', 'Kontrol Eden'], [
          ['Ad Soyad', ''],
          ['Tarih', '{{bugun}}'],
          ['İmza', ''],
        ]),
        p('İlkyardım Yönetmeliği gereğince düzenlenmiştir.'),
      ],
    },
  },
];
